-- HomeoAssist — bcomplain Seed Data (from acid.mdb → bcomplain table)
-- 7,289 symptom entries from the Homeopathic Repertory
-- Chapters: 1=Mind, 2=Head, 3=Eye, 4=Ear, 5=Nose, 6=Face, 7=Mouth,
--           8=Teeth(Tongue), 9=Taste, 10=Gums, 11=Teeth, 12=Throat,
--           13=Stomach, 14=Abdomen, 15=Bladder/Urinary, 16=Male Sexual,
--           17=Female Sexual, 18=Circulatory, 19=Locomotor, 20=Respiratory,
--           21=Skin, 22=Fever, 23=Nervous, 24=Generalities, 25=Modalities
--
-- Run AFTER schema.sql and rubrics_seed.sql:
--   psql -U postgres -d homeoassist -f backend/bcomplain_seed.sql

ALTER SEQUENCE IF EXISTS bcomplain_s_id_seq RESTART WITH 1;

INSERT INTO bcomplain (s_id, d_id, rub_id, s_bname, s_name, sbr_id) VALUES
(1,1,1,'AKzkjZv','AWKWARD-Lets things fall from hand –',1),
(2,2,1,'মস্তিষ্কের ক্লান্তি','BRAIN-FAG (See NEURASTHENIA - Nervous system.) –',1),
(3,3,1,'নিস্পন্দ বায়ু-মোহময় ভাব','CATALEPSY(Trance )',1),
(4,4,1,'w`e¨`র্শন','CLAIRVOYANCE (See Hallucinations.',1),
(5,5,1,'হৃদয়ংগম','COMPREHENSION Difficult (See Memory.) –',1),
(6,5,2,'Abyaveb','COMPREHENSION Easy –',1),
(7,7,1,'চৈতন্য','CONSCIOUSNESS Loss –',1),
(8,8,1,'শারিরীক বিকৃতি ও জড়বুদ্ধি-প্রাপ্তি','CRETINISM Imbecility, Idiocy –',1),
(9,9,1,'বিকার মাদকদ্রব্যের কুফলহেতু কম্পপ্রলাপ','DELIRIUM Alcoholic (delirium tremens) –',1),
(10,9,2,'বিছানার চাদর প্রভৃতি খোঁটা','Carphologia (picking at bed clothes, flocks) –',1),
(11,9,2,'উম্নীলিত চোখ,অচৈতন্য ভাব','Coma Vigil –',1),
(12,9,2,'ধ্বংসাত্নক কার্যের প্রবণতা','Destructive (desire to bark, bite, strike, tear things) –',1),
(13,9,2,'বিকারবশত শয্যা ত্যাগ করিবার অথবা লুকাইয়া থাকিবার প্রচেষ্টা','Effort to escape from bed, or hide –',1),
(14,9,2,'উন্মত্তভাব, ক্রোধোন্মত্ততা, চিৎকার','Furor, frenzy, ravings –',1),
(15,9,2,'কামোন্মাদ','Lascivious furor –',1),
(16,9,2,'†ekx K_v ejv','Loquacity, talks incessantly –',1),
(17,9,2,'উতফুল্ল, নর্তন, গান গাওয়া','Merry, dancing, singing –',1),
(18,9,2,'weoweo Kwiqv e‡K','Muttering, low, incoherently –',1),
(19,9,2,'তাড়াতাড়ি উত্তরদান','Rapid answering –',1),
(20,9,2,'cÖ‡kœi DËi w`‡Z ‡`wi nq','Slow answering, relapses –',1),
(21,9,2,'আচ্ছন্নতা, অচৈতন্য নিদ্রা','Sopor, stupor, coma –',1),
(22,22,1,'বুদ্ধিবিনাশ','DEMENTIA –',1),
(23,22,2,'মৃগীরোগ সংক্রান্ত','Epileptic –',1),
(24,22,2,'হস্তমৈথুন হেতু','Masturbatic –',1),
(25,22,2,'আংশিক পক্ষাNvত হেতু','Paretic –',1),
(26,22,2,'বার্ধক্যহেতু','Senile –',1),
(27,22,2,'উপদংশজাত','Syphilitic –',1),
(28,28,1,'মানসিক উত্তেজনা','EMOTIONS Effects: Anger, bad news, disappointment, vexation --',1),
(29,28,2,'fq †c‡q','Fright, fear –',1),
(30,28,2,'দুঃখ বিষাদ হেতু','Grief, sorrow –',1),
(31,28,2,'হিংসাহেতু অত্যাধিক আনন্দ হেতু','Jealousy – excessive',1),
(32,28,2,'গৃহকারতা','Nostalgia (homesickness) –',1),
(33,28,2,'লজ্জা, মনস্তাপ, বিরক্তিচাপা হেতু','Shame, mortification, reserved displeasure –',1),
(34,34,1,'ভয়, আতঙ্কহেতু','FEARS, DREAD Being carried or raised –',1),
(35,34,2,'রাস্তা পার হইবার সময়ে, ভীড়ে উত্তেজনায়','Crossing streets, crowds, excitement –',1),
(36,34,2,'অন্ধকার, ভূতপ্রেত বিষয়ে fq','Dark, ghosts –',1),
(37,34,2,'মৃত্যু, মারাত্নক রোগ, অমঙ্গল ইত্যাদির ভয়','Death, fatal diseases, impending evil –',1),
(38,34,2,'নিম্নগতির ভয়, ভয়ে পড়ে যাবার ভয়','Downward motion, falling –',1),
(39,34,2,'হৃদস্পন্দন বলিয়া নড়াচড়া করিতে বাধ্য হয়','Heart ceases beating, must move -- Gels. (reverse Dig.).',1),
(40,34,2,'kh¨vq','Lectophobia –',1),
(41,34,2,'বুদ্ধি লোপ পাবার ভয়','Loss of reason –',1),
(42,34,2,'গতি হেতু ভয়','Motion –',1),
(43,34,2,'সঙ্গীতে ভয়','Music –',1),
(44,34,2,'গোলমালে ভয়','Noises –',1),
(45,34,2,'লোক দেখিয়া ভয়','People (anthropophobia) –',1),
(46,34,2,'বদ্ধস্থানে ভয়','Places closed –',1),
(47,34,2,'সূক্ষ্মাগ্রবিশিষ্ট বস্তদর্শনে','Pointed objects –',1),
(48,34,2,'বিষপ্রয়োগ আশঙ্কায়','Poison –',1),
(49,34,2,'বৃষ্টি হইবে বলিয়া ভয়','Rain –',1),
(50,34,2,'নির্জনতায়, নির্জনতায় বিরক্তি','Solitude Aversion to –',1),
(51,34,2,'নির্জনতা, কামনা করিলে','Desire for –',1),
(52,34,2,'জনতা-ভীতি','Space (agoraphobia) –',1),
(53,34,2,'রঙ্গমঞ্চে দাঁড়ালে ভয়','Stage-fright –',1),
(54,34,2,'উপদংশে আক্রান্ত হবে বলে ভয়','Syphilis –',1),
(55,34,2,'বজ্রপাতসহ ঝড়বৃষ্টি কালে ভয়','Thunderstorms – Electricitas,',1),
(56,34,2,'স্পর্শে ,সংস্পর্শে ভয়',' Touch, contact –',1),
(57,34,2,'জলাতঙ্ক','Water (hydrophobia) –',1),
(58,58,1,'অবসাদ বায়ু','HYPOCHONDRIASIS –',1),
(59,59,1,'মূর্চ্ছাবায়ু রোগ','HYSTERIA –',1),
(60,60,1,'ভ্রান্তিবিলাস, খেয়াল, বিভ্রান্তি, অবাস্তব দর্শন, সুস্পষ্ট','MAGINATION Fancies, hallucinations, illusions: Acute vivid (See Hallucinations.) –',1),
(61,60,2,'বাড়ী হতে দুরে আছে','Away from home, must get there –',1),
(62,60,2,'অপর কোন ব্যাক্তি যেন তার পাশে শুয়ে আছে','Bed occupied by another person –',1),
(63,60,2,'তাঁর বিছানা যেন ডুবে যাচ্ছে','Bed sinking –',1),
(64,60,2,'শয্যা অতীব কঠীন বলিয়া অনুভূতি','Bed too hard –',1),
(65,60,2,'যেন কেহ তিরষ্কার বা সমালোচনা করছে','Abused or criticized [being] –',1),
(66,60,2,'যেন কেহ তাকে হত্যা করিবে','Assassinated [being] –',1),
(67,60,2,'যেন তাকে টুকরা টুকরা করে ভেঙ্গে ফেলা হচ্ছে','Broken in fragments, scattered about [being] –',1),
(68,60,2,'ঘর চাপা পরে যেন নিস্পেষিত হচ্ছে','Crushed by houses [being] –',1),
(69,60,2,'মৃতু হচ্ছে','Dead [being] –',1),
(70,60,2,'যেন দৈত্যে পরিণত হচ্ছে, অভিশাপ দেয়, শপথ করে','Demon, curses, swears [being] –',1),
(71,60,2,'যেন পরকাল নষ্ট হয়ে গেল, মুক্তিলাভে আশাশূন্যতা','Doomed, lost to salvation [being] –',1),
(72,60,2,'যেন তার দুটি দেহ আছে(দ্বৈতব্যক্তিত্ত)','Double, (dual personality) [being] –',1),
(73,60,2,'যেন পৃথিবী ঘন মেঘে আবৃত, জগতটা যেন কাল ও কপটতাপূর্ণ','Enveloped in dark cloud, world black and sinister [being] –',1),
(74,60,2,'তার চেয়ারের নীচ থেকে ইঁদুর দৌড়াচ্ছে এবং তাতে ভয় পায়','Frightened by a mouse running from under a chair [being] –',1),
(75,60,2,'মনে হয় যেন কোন পাপের কাজ করছে','Guilty of some committed crime [being] --',1),
(76,60,2,'তার অঙ্গপ্রত্যঙ্গ ফাঁপা','Hollow in organs [being] –',1),
(77,60,2,'যেন অপরিচিত পরিবেশে আছে','In strange surroundings [being] –',1),
(78,60,2,'হালকা ভূতের মত, যেন বাতাসে ভেসে বেড়াচ্ছে','Light, spirit-like, hovering in the air [being] –',1),
(79,60,2,'মনে হয় যেন তার দেহ কাঁচ বা কাষ্টদ্বারা নির্মিত','Made of glass, wood, etc. [being] –',1),
(80,60,2,'যেন বিশেষ কাজে ব্যস্ত আছে','Occupied about business [being] –',1),
(81,60,2,'যেন শÎæMÖণের দ্বারা নির্যাতিত হচ্ছে','Persecuted by his enemies [being] –',1),
(82,60,2,'যেন তাকে কেহ বিষপ্রয়োগ করছে','Poisoned [being] –',1),
(83,60,2,'যেন দুই প্রকার ইচ্ছাশক্তি দ্বারা সে পরিচালিত','Possessed of two wills [being] –',1),
(84,60,2,'যেন মস্তিষ্ক পাকস্থলীতে অবস্থিত','Possessed of brain in stomach [being] –',1),
(85,60,2,'যেন দুইটি নাক আছে','Possessed of two noses [being] –',1),
(86,60,2,'যেন গর্ভবতী হয়েছে অথবা তলপেটে জীবন্ত কিছু আছে','Pregnant, or something alive in the abdomen [being] –',1),
(87,60,2,'যেন কেহ তাকে অনুসরণ করছে','Pursued [being] –',1),
(88,60,2,'যেন তার দেহ ও আত্না বিচ্ছিন্ন','Separated body and soul [being] –',1),
(89,60,2,'যেন স্ফীত হয়েছে','Swollen [being] –',1),
(90,60,2,'যেন অমানুষিক শক্তিদ্বারা পরিচালিত','Under superhuman control [being] –',1),
(91,60,2,'যেন খুব রুগ্ন অবস্থাপ্রাপ্ত','Very sick [being] –',1),
(92,60,2,'যেন সে খুব ধনী','Very wealthy [being] –',1),
(93,60,2,'বস্তসমূহের আয়তন বাস্তব অপেক্ষা যেন বৃহত্তর','Dimensions of things larger',1),
(94,60,2,'বস্তসমূহের আয়তন বাস্তব অপেক্ষা যেন উল্টো','Dimensions of things reversed',1),
(95,60,2,'বস্তসমূহের আয়তন বাস্তব অপেক্ষা যেন ক্ষুদ্রতর','Dimensions of things Smaller –',1),
(96,60,2,'সময় ও স্থানের পরিমাপ সম্বন্ধে ভূল','Duration of time and space lost or confused –',1),
(97,60,2,'সময়ের পরিমাণ যেন পরিবরতিত, সময় দ্রুতগতিশীল','Duration of time changed Passes too rapidly',1),
(98,60,2,'সময়ের পরিমাণ যেন পরিবরতিত,সময়ের গতি অতীব ধীর','Duration of time changed Passes too slowly –',1),
(99,60,2,'ভুল','Hallucinations –',1),
(100,60,2,'ভুল, শোনা(ঘন্টাধ্বনি, গানবাজনা স্বর)','Hallucinations –Auditory (bells, music, voices) –',1),
(101,60,2,'ভুল, আঘ্রাণ বিষয়ে','Hallucinations –Olfactory –',1),
(102,60,2,'ভুল, স্পর্শ সম্বন্ধীয়','Hallucinations –Tactile –',1),
(103,60,2,'ভুলদর্শন সম্বন্ধীয়','Hallucinations –Visual (animals, bugs, faces) –',1),
(104,104,1,'উন্মত্ততা','INSANITY (See Mania, Melancholia, Dementia).',1),
(105,105,1,'উন্মাদনা বিষাদোন্মত্ততা, বুদ্ধিনাশ প্রসঙ্গ দোষ','LOQUACITY –',1),
(106,106,1,'বাচালতা','MANIA –',1),
(107,106,2,'অতিরিক্ত কামভাব( পুরুষ এবং স্ত্রীলোকদিগের)','Erotomania (nymphomania, satyriasis) –',1),
(108,106,2,'বিষাদোন্মাদ','Lypemania –',1),
(109,106,2,'বিষয় বিশেষে অযথা মত্ততা ( চুরি করার জন্য দুর্দম্য প্রবৃত্তি )','Monomania (kleptomania, etc.) –',1),
(110,106,2,'সূতিকা উন্মাদ','Puerneral –',1),
(111,111,1,'বিষাদোন্মত্ততা','MELANCHOLIA –',1),
(112,111,2,'ধাতু ও উদ্গমণকালে','Pubertic',1),
(113,111,2,'প্রসবান্তিক','Puberty –Puerperal –',1),
(114,111,2,'ধর্মবিষয়ক','Religious –',1),
(115,111,2,'যৌন সম্বন্ধীয়','Sexual',1),
(116,116,1,'স্মৃতিশক্তি সবকিছু ভূলে যায় দুর্বল অথবা লুপ্ত','MEMORY  Forgetful, weak or lost –',1),
(117,116,2,'পরিচিত পথগুলি মনে করতে পারে না','Familiar streets [cannot remember] –',1),
(118,116,2,'নাম মনে না থাকা','Names [cannot remember] –',1),
(119,116,2,'সঠিক শব্দ মনে না আসা (বাকরোধ বেখাপ্পা শব্দ প্রয়োগ)','Right words (amnesic aphasia, paraphasia) [cannot remember] –',1),
(120,116,2,'মনসংযোগ করতে পারে না','Difficulty or inability of fixing attention –',1),
(121,116,2,'লিখতে অক্ষর অথবা কথা বাদ পড়ে যায়','Omits letters, words –',1),
(122,116,2,'দ্রুত চিন্তা করে','Thoughts Rapid –',1),
(123,116,2,'চিন্তাধারা,ধীর','Thoughts Slow',1),
(124,116,2,'পড়ার সময় কথা বলার ও লিখবার সময় চিন্তাধারা বিলুপ্ত হয়','Vanish while reading, talking, writing –',1),
(125,116,2,'চিন্তা করতে পারে না','Unable to think –',1),
(126,116,2,'যৌন অত্যাচার হেতু স্ম্রিতীশক্তির দুর্বলতা','Weak from sexual abuse –',1),
(127,127,1,'মানসিক অবস্থা, অন্যমনষ্কতা','MIND Absence –',1),
(128,127,2,'নৈতিক ও ইচ্ছাশক্তির অভাব','Absence of moral and will power –',1),
(129,127,2,'মানসিক আচ্ছন্নতা, বিভ্রান্তি, শৈথিল্য, অবসাদ','Cloudiness, confusion, depression, dullness –',1),
(130,127,2,'উত্তেজনা, অতিশয় আনন্দ','Excitement, exhilaration –',1);

INSERT INTO bcomplain (s_id, d_id, rub_id, s_bname, s_name, sbr_id) VALUES
(131,131,1,'মেজাজ, মনোভাব বিদ্যুতসহ ঝড়বৃষ্টির সময়ে উদ্বেগ','MOOD, DISPOSITION Anxiety – Thunderstorm, during –',1),
(132,131,2,'পাকস্থলীতে অস্থিরতাবোধ',' Anxiety –Felt Stomach, in –',1),
(133,131,2,'অস্থিরতা','Anxious',1),
(134,131,2,'উদাসীনতা, সব কিছুর প্রতি বিরাগ','Apathetic, indifferent to everything –',1),
(135,131,2,'মানসিক ও শারিরীক শ্রমে বিরক্তি','Averxion to mental and physical works',1),
(136,131,2,'মানসিক ও শারিরীক শ্রমে বিরক্তি','Bashful, timid –',1),
(137,131,2,'খুঁতখুঁতে মন, অসুখী ও অসন্তষ্ট','Complaining, discontented, dissatisfied –',1),
(138,131,2,'সহজেই হতাশ, নিরাশ, ভগ্নোৎসাহ, বিস্বাসের অভাব','Despairing, hopeless, discouraged easily, lack of confidence –',1),
(139,131,2,'অন্যের দোষ ধরে অতিমাত্রায় সুক্ষ্মদর্শী,সতর্ক','Fault-finding, finicky, cautious –',1),
(140,131,2,'নির্ভয়, অতি সাহসী','Fearlessness, daring –',1),
(141,131,2,'খিটখিটে, রাগপ্রবণ, কোপনস্বভাব, ঝগড়াটে এবং ঘ্যান-ঘ্যানে স্বভাব','Fretful Cross, irritable, peevish, quarrelsome, whining –',1),
(142,131,2,'দিনরাত খিটখিট করা, খিটখিটে স্বভাব','Fretful Day and night –',1),
(143,131,2,'কেবলমাত্র দিবসে খিটখিট করা','Fretful Day only –',1),
(144,131,2,'কেবলমাত্র রাত্রিতে খিটখিট করা','Fretful Night only –',1),
(145,131,2,'খিটখিটে, শিশু স্পর্শ, তার দিকে তাকান বা তার সঙ্গে কথা বলা কোনটাই সহ্য করতে পারে না','Fretful so that Child cannot bear to be touched, looked at, or spoken to –',1),
(146,131,2,'খিটখিটে স্বভাব, শিশু অনেক জিনিস চায় কিন্ত সবই প্রত্যাখান করে','Fretful so that Child wants different things, but petulantly rejects them –',1),
(147,131,2,'আনন্দপ্রিয়, আমোদ-প্রমোদপ্রিয়, আনন্দিত','Gay, frolicsome, hilarious –',1),
(148,131,2,'দুঃখ করে বিগত বিষয়ে চিন্তা করে দীর্ঘশ্বাস ফেলা','Grieving, introspective, sighing –',1),
(149,131,2,'উদ্বত, গোয়ার, গর্বিত','Haughty ,Arrogant, prideful –',1),
(150,131,2,'উদ্বত, অপরের প্রতি অবজ্ঞা','Haughty, Contempt of others –',1),
(151,131,2,'উদ্বত, নিজের প্রতি অবজ্ঞা','Haughty, Contempt of self –',1),
(152,131,2,'অতি অনুভূতি, প্রতিবাদ সহ্য করতে পারে না, সামান্য কারণে চটে যায়','Hypersensitive, cannot bear contradiction, vexed at trifles –',1),
(153,131,2,'অতিরিক্ত আবেগ প্রবণ (পরিবর্তনশীল, মানসিক অস্থিরতা)','Hysterical (changeable, vacillatory) –',1),
(154,131,2,'অতিশয় আবেগময়','Impatient, impulsive –',1),
(155,131,2,'বিবেচনাহীন, অপমান করার স্বভাব, দ্বেষপরায়ন, প্রতিহিংসাপরায়ন, হিংসুক','Impudent, insulting, malicious, revengeful, spiteful –',1),
(156,131,2,'অবিবেচক, বিরক্ত করা স্বভাব, বকলেও হাসে','Impudent, teasing, laugh at reproof –',1),
(157,131,2,'কোন সিদ্বান্ত পৌঁছাতে পারেনা, মতিস্থিরতার অভাব','Indecisive, irresolute –',1),
(158,131,2,'অলস, অমনোযোগী, উচ্চাকাঙ্ক্ষাহীন','Indolent, listless, lethargic, ambitionless –',1),
(159,131,2,'অপরকে হিংসা করে','Jealous –',1),
(160,131,2,'বিষণ্ণ, হতাশ, অবসাদ্গ্রস্থ, নিস্তেজ, বিমর্ষ, ভবিষ্যৎ ভয়ে ভীত','Melancholic, despondent, depressed, low-spirited, gloomy, Apprehensive, blues –',1),
(161,131,2,'শান্ত স্বভাব, নম্র, নমনীয়','Mild, gentle, yielding –',1),
(162,131,2,'অমানুষ, কৃপণ, স্বার্থপর, মানুষ হিংসা করে','Misanthropic, miserly, selfish –',1),
(163,131,2,'দুর্বলচেতা, উত্তেজিত, চঞ্ছল, উদ্বিগ্ন','Nervous, excited, fidgety, worried –',1),
(164,131,2,'নির্লজ্জ, কামূক','Obscene, amative –',1),
(165,131,2,'মানসিক ও শারিরীক অস্থিরতা','Restless (mentally and physically) –',1),
(166,131,2,'অল্পে দুখিত, ভাবপ্রবণ, দীর্ঘশ্বাস ফেলা','Sad, sentimental, sighing –',1),
(167,131,2,'বিষণ্ণ, গান বাজনা শুনলে কাঁদে','Sad, weeping from music –',1),
(168,131,2,'কুরুচিসম্পন্ন, অপরিচ্ছন্ন, নোংরা','Slovenly, filthy –',1),
(169,131,2,'জেদী, অবাধ্য, দূরদমনীয়, স্বেচ্ছাচার','Stubborn, obstinate, self-willed –',1),
(170,131,2,'বোকা','Stupid –',1),
(171,131,2,'আত্নহত্যা করার প্রবণতা','Suicidal –',1),
(172,131,2,'সকলকে সন্দেহ করে, অবিশ্বাসী','Suspicious, mistrustful –',1),
(173,131,2,'অপরের দুঃখে দুখিত, সহানুভূতিশীল','Sympathetic –',1),
(174,131,2,'অল্পভাষী, বিরক্ত হতে অথা প্রশ্নের উত্তর দিতে অনিচ্ছুক','Taciturn, disinclined to be disturbed, or answer questions –',1),
(175,131,2,'স্বল্পভাষী, কথার উত্তর দিতে পছন্দ করে না','Taciturn, morose, sulky, sullen, unsociable –',1),
(176,131,2,'ক্রন্দনশীল, বিলাপপ্রবণ','Tearful, weeping –',1),
(177,177,1,'নৈশভীতি','NIGHT-TERRORS –',1),
(178,178,1,'স্বাভাবিক প্রবৃত্তি','PROPENSITY Abusive, curse, swear [to be] –',1),
(179,178,2,'বিনা কাজে ব্যস্ত থাকা','Aimlessly busy [to be] –',1),
(180,178,2,'কেবল কোলে চড়তে চায়','Carried [to be] –',1),
(181,178,2,'wb`©q, ঊগ্র, এবং অমানুষিক হতে চায়','Cruel, violent, inhuman [to be] –',1),
(182,178,2,'সবকিছু ভেঙ্গেচুরে ফেলতে, কামড়াইতে, আঘাত করতে এবংবস্ত্রাদি ছিন্ন করতে চায়','Destructive, bite, strike, tear clothes [to be] –',1),
(183,178,2,'আগোছালো ভাব, মলিন অপরিপাটি ও নোংরা হয়ে যেতে চায়','Dirty, untidy, filthy [to be] –',1),
(184,178,2,'অনায়াসে অভিভুত হয়','Magnetized [to be] –',1),
(185,178,2,'অশ্লীল আচরণে','Obscene [to be] –',1),
(186,178,2,'আত্নহত্যা করতে চায়','Suicide, to commit –',1),
(187,178,2,'নাচতে চায়','Dance, to –',1),
(188,178,2,'অদ্ভুত ও অসঙ্গত কার্য করতে চায়','Absurd things, to do –',1),
(189,178,2,'বেশি খেতে চায়','Eat greedily, to –',1),
(190,178,2,'লিঙ্গ ধরে থাকে','Handle organs, to –',1),
(191,178,2,'নিজে খুব তাড়াতাড়ি করে','Hurry, to –',1),
(192,178,2,'অপরকে তাড়াতাড়ি করতে বলে','Hurry others, to –',1),
(193,178,2,'প্রিয়জনদিগকে হত্যা করতে চায়','Kill beloved ones, to –',1),
(194,178,2,'সামান্য ব্যাপারে অতিশয় হাসে','Laugh immoderately at trifles, to –',1),
(195,178,2,'wg_¨v K_v e‡j','Lie, to –',1),
(196,178,2,'হাত পা কেটে ফেলতে চায়','Mutilate body, to –',1),
(197,178,2,'মহান কিছু করার বাসনা','Perform great things, to –',1),
(198,178,2,'এক কথা বার বার বলে','Repeat everything, to –',1),
(199,178,2,'অপরকে গালমন্দ করতে চায়','Scold, to –',1),
(200,178,2,'গান করতে চায়','Sing, to –',1),
(201,178,2,'বিছানার নিচের দিকে গড়িয়ে পড়ে','Slide down in bed, to –',1),
(202,178,2,'অনবরত হাই তোলা ও আড়মোড়া ভাঙ্গে','Stretch and yawn incessantly, to –',1),
(203,178,2,'কবিতা আবৃত্তি করা ও ভবিষ্যতবাণী করা','Talk in rhymes, repeat verses, prophecy, to –',1),
(204,178,2,'জিনিসপত্র ছিড়ে ফেলার ইচ্ছা','Tear things, to –',1),
(205,178,2,'কষ্ট দেয়, গালাগালি করলে হাসে','Tease, laugh at reproofs, to –',1),
(206,178,2,'মনে মনে শুধু কল্পনা করে','Theorize or meditate, to –',1),
(207,178,2,'যেকোন জিনিস দেখলেই স্পর্শ করতে চায়','Touch different things, to –',1),
(208,178,2,'বাড়ি থেকে দূরে বেড়াতে যেতে চায়','Wander from home, to –',1),
(209,178,2,'কাজ করতেই থাকে','Work, to –',1),
(210,210,1,'চিৎকার করে ওঠা','SCREAMS Shrill, sudden, Piercing –',1),
(211,211,1,'চেতনা শক্তি কমে যাওয়া','SENSES Dulled –',1),
(212,211,2,'চেতনা শক্তি প্রখর','Hyperacute –',1),
(213,213,1,'কথা','SPEECH Hurried –',1),
(214,213,2,'বাকশক্তি লোপ অথবা পক্ষাঘাতগ্রস্থ (স্বরলোপ)','Lost or Paralysis (aphasia) (See Nervous System.) –',1),
(215,213,2,'নাকীসুরে কথা বলা','Nasal',1),
(216,213,2,'কষ্টসাধ্য উচ্চারণ, অস্পষ্ট, তোৎলামী','Slow, difficult enunciation, inarticulate, stammering -- Æsc. gl.,',1),
(217,213,2,'বাকী খুব ধীর, একঘেয়ে, তারতম্যহীন, পরিমিত','Slow, monotonous, economical –',1),
(218,218,1,'স্বপ্নসঞ্চরন বা স্বপ্নে ভেসে বেড়ান','SOMNAMBULISM –',1),
(219,219,1,'চমকে উঠা','STARTLES Easily frightened –',1),
(220,220,1,'জীবনের প্রতি বিতৃষ্ণা','TAEDIUM VITAE (disgust of life) –',1);

-- ============================================================
-- NOTE: The above covers rows 1-220 (Mind chapter, sbr_id=1).
-- The remaining 7,069 rows span sbr_id 2-25 (Head through Modalities).
-- They are loaded automatically by generate_bcomplain.js
-- Run: node generate_bcomplain.js  (creates bcomplain_full_seed.sql)
-- Then: psql -U postgres -d homeoassist -f backend/bcomplain_full_seed.sql
-- ============================================================
