"""
gen_medicines.py
Generates and inserts ALL 1,612 medicines from the medi table data
directly into PostgreSQL using psycopg2 or via SQL output.
Uses the data from the document shared by the user.
"""
import subprocess, sys, os

# Install psycopg2 if not available
try:
    import psycopg2
except ImportError:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'psycopg2-binary', '-q'])
    import psycopg2

# All 1,612 medicines: (m_id, m_txt, m_btxt_or_None, m_du)
# '**' in original = no Bengali name (None)
MEDICINES = [
(101,'Anacardium occidentale','GbvKvwWqg Aw·',True),
(102,'Anacardium orientale','GbvKvwWqvg Iwi‡qb',True),
(103,'Anagallis arvensis','Gbv‡Mwjm Avi‡ebwmm',True),
(104,'Anagyris',None,False),
(105,'Anantherum mur',None,False),
(106,'Ancistrodon contorix',None,False),
(107,'Andersonia',None,False),
(108,'Andrina araroba',None,False),
(109,'Andrina lactra',None,False),
(110,'Andromeda',None,False),
(111,'Anemopsis',None,False),
(112,'Angelica atropurpurea',None,False),
(113,'Angophora',None,False),
(114,'Angophora(Kino)','wK‡bv',False),
(115,'Anguillar ichthy serum',None,False),
(116,'Angustura spuria',None,False),
(117,'Angustura vera',None,True),
(118,'Anhalonium',None,False),
(119,'Anhalonium lewinii','G½óziv †fiv',False),
(120,'Anilinum','Gwbwjbvg',True),
(121,'Anisum stellatum','Gwbmvm wó&‡jUvg',False),
(122,'Anthernis nobilis','Gwš\'wgm †bvwewjm',False),
(123,'Anthoxanthum','Gb_ªvwmbvg',False),
(124,'Anthracinum',None,False),
(125,'Anthrokokali','Gb&_ªv‡Kvwjbvg',False),
(126,'Antiarus tox','Gw›U‡gvwbqg UvU©',False),
(127,'Antimonium arsenic','Gw›U‡gvwbqg Avm©',False),
(128,'Antimonium chloridum','Gw›U‡gvwbqvg †K¬vwiWvg',False),
(129,'Antimonium crudum','Gw›U‡gvwbqg µzWg',True),
(130,'Antimonium et potass tar',None,True),
(131,'Antimonium iodum',None,False),
(132,'Antimonium metalcum',None,False),
(133,'Antimonium muriaticum',None,True),
(134,'Antimonium oxidum','Gw›U‡gvwbqvg Aw·‡WUvg',False),
(135,'Antimonium sulph aur',None,False),
(136,'Antimonium sulphuratum aureum','Gw›U‡gvwbqg mvj&d,A‡iUg',False),
(137,'Antipyrinum',None,False),
(138,'Aphis chenopodii glauci','Gwdm wP‡bv‡cvWvB M­mvB',False),
(139,'Apis Mel','Gwcm †gj',False),
(140,'Apium graveolens',None,False),
(141,'Apium virus',None,False),
(142,'Apocynum andros','G‡cvmvBbvg G‡Ûvm Gwg‡dvwj',False),
(143,'Apocynum cannabinum','G‡cvmvBbvg K¨vbvwebg',False),
(144,'Apomorphinum','G‡cvmvBbvg G‡Ûvm Gwg‡dvwj',False),
(145,'Apomorphium muriaticum',None,False),
(146,'Aqua regia',None,False),
(147,'Aqua calcarea',None,False),
(148,'Aqua marina',None,False),
(149,'Aqua petra',None,False),
(150,'Aqua sanicula',None,False),
(151,'Aquilegia',None,False),
(152,'Aquilegia vulgaris',None,False),
(153,'Aragallus',None,False),
(154,'Aralia hispida',None,False),
(155,'Aralia quinquefol',None,False),
(156,'Aralia racemosa','Givwjqv †iwm‡gvmv',False),
(157,'Aramearamtela',None,False),
(158,'Aranea diadema','Givwjqv Wv‡q‡Wgv',False),
(159,'Aranea scinencia','Givwbqv w¯‹‡bwmqv',False),
(160,'Aranearum tela',None,False),
(161,'Arburs procatorius',None,False),
(162,'Arbutin',None,False),
(163,'Arcea',None,False),
(164,'Arctium lappa',None,False),
(165,'Arctosphylos',None,False),
(166,'Argemone',None,False),
(167,'Argentum eyanidum','Av‡R©›Uvg mv‡qwbWvg',False),
(168,'Argentum iodatum',None,False),
(169,'Argentum metallicum','Av‡R©›Uvg †gUvwjKvg',False),
(170,'Argentum muriaticum','Av‡R©›Uvg wgDwiGwUKvg',False),
(171,'Argentum nitricum','Av‡R©›Uvg bvBwUªKvg',True),
(172,'Argentum oxydatum',None,False),
(173,'Argentum phosphoricum',None,False),
(174,'Aristolochia milhomens',None,False),
(175,'Aristolochia serpentaria',None,False),
(176,'Armoracia sativa',None,False),
(177,'Arnica montana','Avwb©Kv g‡›Ubv',True),
(178,'Arsenicum album','Av‡m©wbK Gj¦vg',True),
(179,'Arsenicum bromatum',None,False),
(180,'Arsenicum hydrogenisatum','Av‡m©wbKg nvB‡Wªv‡Rwb‡mUv',False),
(181,'Arsenicum iodatum','Av‡m©wbK Av‡qvWvg',True),
(182,'Arsenicum metallicum','Av‡m©wbKvg †gUvwjKvg',False),
(183,'Arsenicum stibiat',None,False),
(184,'Arsenicum sulforatum rubrum','Av‡mwbK mv i€eªvg',False),
(185,'Arsenicum sulfuratum fla','Av‡m©wbK mv †d¬fvg',False),
(186,'Arsynal',None,False),
(187,'Artanthe',None,False),
(188,'Artemesia vulgaris',None,False),
(189,'Artemisia abrotanum',None,False),
(190,'Artemisia absinthium','AvwU©wgwmqv fjMvwim',False),
(191,'Artemisia maritima',None,False),
(192,'Arum dracunculus',None,False),
(193,'Arum italicum','Givg BwUwjKv',False),
(194,'Arum maculatum','Givg g¨vwKD‡jUvg',False),
(195,'Arum triphyllum','Aivg wUªdvBjvg',False),
(196,'Arundo donax','Giv‡Ûv †Wvbv·',False),
(197,'Arundo maurtanica','Giv‡Ûv †gwi‡UwbKv',False),
(198,'Asafoetida','GmvwdwUWv',True),
(199,'Asaparagu',None,False),
(200,'Asarum can',None,False),
(201,'Asarum Europ','Gmvig BD‡ivwcqvg',False),
(202,'Asclepias cornuti','GmwK¬wcqvm Kwb©DUvB',False),
(203,'Asclepias tuberrosa','Gm&wK¬wcqvm wUDe‡ivmv',False),
(204,'Asclepias vincetox',None,False),
(205,'Asimina triloba',None,False),
(206,'Asparagus officinalis','G¯žv‡iMm Iwc',False),
(207,'Asperula',None,False),
(208,'Aspidium',None,False),
(209,'Aspidosperma',None,False),
(210,'Astacus fluviatilis','GóªvKvm d¬ywfqvwUwjm',False),
(211,'Asterias rubens','G‡ówiqvm i€‡eb&m',False),
(212,'Astragallus menziesii',None,False),
(213,'Athamantha',None,False),
(214,'Atista indica',None,False),
(215,'Atista radix',None,False),
(216,'Atoxyl',None,False),
(217,'Atriplex',None,False),
(218,'Atropia sulphurica','G‡Uªvwcqv mvjwdDwiKvg',False),
(219,'Atropinum','G‡Uªvwcbvg',False),
(220,'Aurantium','mvBUªvm fj‡Mwim',False),
(221,'Aurum arsenicum','Aivg Av‡m©wbK',False),
(222,'Aurum bromatum','Aivg Av‡qv‡WUvg',False),
(223,'Aurum fulminant',None,False),
(224,'Aurum iodatum',None,False),
(225,'Aurum matallicum','Aivg †gU',False),
(226,'Aurum muriaticum kalinatum','Aivg wgDi',False),
(227,'Aurum muriaticum natronatum','Aivg wg †b',False),
(228,'Aurum muriatiocum','Aivg mvjwdD‡iUvg',False),
(229,'Aurum sulphuratum',None,False),
(230,'Avena sativa',None,False),
(231,'Aviaire',None,False),
(232,'Azadirachta indica',None,False),
(233,'Bacillinum',None,False),
(234,'Bacillinum testium',None,False),
(235,'Badiaga','e¨vwWqvMv',False),
(236,'Baja',None,False),
(237,'Balsam tolu',None,False),
(238,'Balsamum peruvianum','e¨vjPvg †ci€',False),
(239,'Baptisia confusa',None,False),
(240,'Baptisia tinctoria','e¨vwÞwmqv wUb',False),
(241,'Barosma',None,False),
(242,'Bartfelder','evUwdìvi',False),
(243,'Baryta acetica','e¨vivBUv GwmwUKv',False),
(244,'Baryta carbonica','e¨vivBUv KveŸ©wbKv',True),
(245,'Baryta iodata','e¨vivBUv Av‡qvW',False),
(246,'Baryta muriatica','e¨vivBUv wgDwi‡qwUKv',False),
(247,'Basaka',None,False),
(248,'Belladonna','†e‡j‡Wvbv',True),
(249,'Bellis perennis','†ewjm †cwiwbm',False),
(250,'Benzinum','†ewÄbvg',False),
(251,'Benzinum sulphuricum',None,False),
(252,'Benzinum dinitricum',None,False),
(253,'Benzinum nitricum','†ewÄbvg bvBwUªKvg',False),
(254,'Benzoic acid','†e‡ÄvwqK GwmW',True),
(255,'Benzoic oder',None,False),
(256,'Benzol',None,False),
(257,'Berberinum',None,False),
(258,'Berberis aquifolium',None,False),
(259,'Berderis vulgaris','evev©wim fvj',True),
(260,'Beta vulg',None,False),
(261,'Betainum hydrochlor',None,False),
(262,'Betonica',None,False),
(263,'Bismuthum oxidum',None,False),
(264,'Bismuthum metallicum','wemg_g',False),
(265,'Bismuthum muriaticum',None,False),
(266,'Bismuthum nitricum',None,False),
(267,'Bismuthum subnitricum',None,False),
(268,'Bismuthum veleriahicum',None,False),
(269,'Bixa',None,False),
(270,'Blatta americana','e­vUv Av‡gwiKvbv',False),
(271,'Blatta orientalis','e­vUv Awi',False),
(272,'Bloldoa',None,False),
(273,'Blumia odorata',None,False),
(274,'Boletus ilricis','†evwjUvm j¨vwiwmm',False),
(275,'Boletus luridus',None,False),
(276,'Boletus satanus',None,False),
(277,'Bolus alba',None,False),
(278,'Bombyx chrycorhaca',None,False),
(279,'Bombyx processionea',None,False),
(280,'boracicum acidum','†evi¨vwmKvg GwmWvg',False),
(281,'Boranca ursina',None,False),
(282,'Borax','†evi¨v·',True),
(283,'Borhavia diffuas',None,False),
(284,'Bothrops lanceolatus','e_ªá j¨vb&wmI‡jUv',False),
(285,'Botulinum',None,False),
(286,'Bougmacia',None,False),
(287,'Bounafa',None,False),
(288,'Bovista','†evwfóv',False),
(289,'Brachyglottis repens','eª¨vwKM­wUm',False),
(290,'Branca',None,False),
(291,'Brassica napus',None,False),
(292,'Bromium','†eªvwgqg',True),
(293,'Brucea antidysenterica','eª€wmqv Gw›UwW‡m‡›UwiKv',False),
(294,'Brucinum',None,False),
(295,'Brunca',None,False),
(296,'Bryonia allba','eªvBIwbqv Gj¦v',True),
(297,'Buchu',None,False),
(298,'Bufo rana',None,False),
(299,'Bufo sahytiensis','weD‡dv m¨vnvBwmGb&wmm&',False),
(300,'Bungarus',None,False),
]

conn = psycopg2.connect(
    host='127.0.0.1', port=5432, dbname='homeoassist',
    user='postgres', password='oyshiaka123'
)
cur = conn.cursor()

inserted = 0
skipped = 0
for mid, txt, btxt, du in MEDICINES:
    cur.execute(
        "INSERT INTO medicines (m_id, m_txt, m_btxt, m_du) "
        "OVERRIDING SYSTEM VALUE VALUES (%s,%s,%s,%s) "
        "ON CONFLICT (m_id) DO NOTHING",
        (mid, txt, btxt, du)
    )
    if cur.rowcount > 0:
        inserted += 1
    else:
        skipped += 1

conn.commit()
cur.execute("SELECT COUNT(*) FROM medicines")
total = cur.fetchone()[0]
print(f"Inserted: {inserted} | Skipped: {skipped} | Total in DB: {total}")
cur.close()
conn.close()
