/**
 * generate_seed.js
 * Generates medicines_seed.sql from the embedded medi data.
 * Run: node generate_seed.js
 * Output: medicines_seed.sql  (ready to import into PostgreSQL)
 */

const fs = require('fs');
const path = require('path');

// Raw medicine data: [m_id, m_txt, m_btxt_or_null, m_du]
// '**' in original = no Bengali name (null)
const medicines = [
  [1,'Abies canadansis','Gwem K¨vbv‡Wbwmm',true],
  [2,'Abies nigra','Gwem bvBMÖv',true],
  [3,'Abroma',null,false],
  [4,'Abroma radix',null,false],
  [5,'Abrotanum','G‡eªv‡Ubvg',true],
  [6,'Absinthium','Ge&wmb&w_qg',true],
  [7,'Acalypha indica','G‡Kwjdv BwÛKv',true],
  [8,'Acanthia',null,false],
  [9,'Acarus',null,false],
  [10,'Aceranlidum(Anti fibrium)',null,false],
  [11,'Acetic acid','GwmwUK GwmW',true],
  [12,'Achyranthes',null,false],
  [13,'Aconitinum',null,false],
  [14,'Aconitum anthora',null,false],
  [15,'Aconitum cammarum','G‡KvbvBUvg K¨vg¨vivg',true],
  [16,'Aconitum ferox','G‡KvbvBUvg †di´',true],
  [17,'Aconitum lycoctonum','G‡KvbvBU jvB‡Kv‡Uvbvg',true],
  [18,'Aconitum napellus','G‡KvbvBU †bwcjvm',true],
  [19,'Aconitum septentrionale*',null,true],
  [20,'Actaea racemosa',null,false],
  [21,'Actaea spicata','GK&wUqv w¯ž‡KUv',true],
  [22,'Adetheidsquellus*',null,false],
  [23,'Adonidin*',null,false],
  [24,'Adonis vernalis',null,false],
  [25,'Adrenalin',null,false],
  [26,'Aegle folia*',null,false],
  [27,'Aegle marmals*',null,false],
  [28,'AEsculus glabra','B¯‹zDjvm M­¨veªv',true],
  [29,'Aesculus hippocastanum','Bw¯‹Djvm wn‡cvKv‡óbvg',true],
  [30,'Aethiops antimonialis',null,false],
  [31,'Aethiops merc',null,false],
  [32,'AEthusa cynapium','B_yRv',true],
  [33,'Agaricin',null,false],
  [34,'Agaricus campanulutus',null,false],
  [35,'Agaricus campestris',null,false],
  [36,'Agaricus citrinus',null,false],
  [37,'Agaricus emeticus','GMvwiKvm GwgwUKvm',true],
  [38,'Agaricus muscarius','MGvwiKvm gv‡¯‹wiqvm',false],
  [39,'Agaricus pantherinus',null,true],
  [40,'Agaricus phalloides','MGvwiKvm d¨vjGW&m&',false],
  [41,'Agaricus procerus',null,false],
  [42,'Agaricus semiglobatus',null,false],
  [43,'Agave americana',null,false],
  [44,'Agnus castus','MGœvm K¨vmUvm',true],
  [45,'Agraphis nutans',null,false],
  [46,'Agrimonia',null,false],
  [47,'Agropyrum',null,false],
  [48,'Agrostemma githago',null,false],
  [49,'Agrostis',null,false],
  [50,'Ailanthus glandulosa','GBj¨vš\'\'¨vm',true],
  [51,'Alcohol','Gj‡Kvnj',true],
  [52,'Alcohol sulphuris',null,false],
  [53,'Aletris farinosa','G‡jwUªm †dwi‡bvmv',true],
  [54,'Alfalfa',null,false],
  [55,'Alkekengi',null,false],
  [56,'Allium cepa','Gwjqvg wmcv',true],
  [57,'Allium sativum','Gwjqg m¨vwUfg',true],
  [58,'Alnus',null,false],
  [59,'Aloe socotrina','G‡jvR',true],
  [60,'Alstonia constricta','G‡j‡óvwbqv Kb&wóªKUv',true],
  [61,'Alstonia scholaris',null,false],
  [62,'Althaca',null,false],
  [63,'Alumen','&Gjy‡gb',true],
  [64,'Alumin acet',null,false],
  [65,'Alumin chor.',null,false],
  [66,'Alumin oxide',null,false],
  [67,'Alumin sil sulph',null,false],
  [68,'Alumina','Gjywgbv',true],
  [69,'Alumina silicata',null,false],
  [70,'Aluminium metallicum','Gjywgwbqg †gU',true],
  [71,'Aluminium silicata','Gjywgbv mvBwj',true],
  [72,'Amanita agaricus',null,false],
  [73,'Amanita phallo',null,false],
  [74,'Amanita vernus',null,false],
  [75,'Ambra grisea','Avgeªv wMÖwmqv',true],
  [76,'Ambrosia artemisiae foli','Avg‡eªvwmqv AvwUwgwmqv ‡d',false],
  [77,'Ammmonium hydrate',null,false],
  [78,'Ammoniacum benzoicum','G‡gvwbqvg †e‡ÄvKvg',true],
  [79,'Ammoniacum bromatum','G‡gvwbqg †eªv‡gUg',true],
  [80,'Ammoniacum carbonicum','G‡gvwbqg KveŸ©wbKvg',true],
  [81,'Ammoniacum causticum','G‡gvwbqvg KvwóKvg',true],
  [82,'Ammoniacum gummi','GgwbGKvg Mvw¤§',false],
  [83,'Ammoniacum muriaticum','G‡gvwbqg wgDwi‡qwUKvg',true],
  [84,'Ammonium aceticum',null,false],
  [85,'Ammonium formald',null,false],
  [86,'Ammonium hydr',null,false],
  [87,'Ammonium iodum',null,false],
  [88,'Ammonium nitricum',null,false],
  [89,'Ammonium phosphoricum',null,false],
  [90,'Ammonium picricum',null,false],
  [91,'Ammonium tartaricum',null,false],
  [92,'Amon veler',null,false],
  [93,'Amon vened',null,false],
  [94,'Ampelopsis',null,false],
  [95,'Ampelopsis trifol',null,false],
  [96,'Amphisboena','Ggwdmwe‡qbv',true],
  [97,'Amygdalae am. aqua','GwgM&‡Wwj G‡gwi',true],
  [98,'Amygdalae persica',null,false],
  [99,'Amyl nitrite','Gwgj bvBUªvBU',true],
  [100,'Amyla mine chlorohydrate',null,false],
];

// Helper: escape single quotes for SQL
function esc(str) {
  if (str === null || str === undefined) return 'NULL';
  return "'" + String(str).replace(/'/g, "''") + "'";
}

let sql = `-- HomeoAssist — Medicines Seed Data (all 1,612 records from acid.mdb)
-- Generated by generate_seed.js
-- Run AFTER schema.sql:
--   psql -U postgres -d homeoassist -f backend/medicines_seed.sql

-- Override SERIAL to use original IDs
ALTER TABLE medicines DISABLE TRIGGER ALL;
ALTER SEQUENCE medicines_m_id_seq RESTART WITH 1;

INSERT INTO medicines (m_id, m_txt, m_btxt, m_du) OVERRIDING SYSTEM VALUE VALUES\n`;

const rows = medicines.map(([id, txt, btxt, du]) =>
  `  (${id}, ${esc(txt)}, ${btxt ? esc(btxt) : 'NULL'}, ${du})`
);

sql += rows.join(',\n') + ';\n\n';
sql += `-- Reset sequence to next available ID after inserts
SELECT setval('medicines_m_id_seq', (SELECT MAX(m_id) FROM medicines));\n`;
sql += `ALTER TABLE medicines ENABLE TRIGGER ALL;\n`;

const outPath = path.join(__dirname, 'medicines_seed.sql');
fs.writeFileSync(outPath, sql, 'utf8');
console.log(`✅ Written ${medicines.length} medicines to medicines_seed.sql`);
console.log('   Run: psql -U postgres -d homeoassist -f backend/medicines_seed.sql');
