/**
 * HomeoAssist — bcomplain Full Seed Generator
 *
 * This script generates bcomplain_full_seed.sql from the raw data.
 * The raw data is embedded here directly from acid.mdb bcomplain table.
 *
 * Usage: node generate_bcomplain.js
 * Output: bcomplain_full_seed.sql
 *
 * The sbr_id mapping matches acid.mdb sbr01 chapter numbers:
 * 1=Mind, 2=Head, 3=Eye, 4=Ear, 5=Nose, 6=Face, 7=Mouth,
 * 8=Tongue, 9=Taste, 10=Gums, 11=Teeth, 12=Throat,
 * 13=Stomach, 14=Abdomen, 15=Bladder/Urinary, 16=Male Sexual,
 * 17=Female Sexual, 18=Circulatory, 19=Locomotor,
 * 20=Respiratory, 21=Skin, 22=Fever, 23=Nervous,
 * 24=Generalities, 25=Modalities
 */

const fs = require('fs');
const path = require('path');

// Helper: escape single quotes in SQL strings
function esc(str) {
  if (str === null || str === undefined) return 'NULL';
  return "'" + String(str).replace(/'/g, "''") + "'";
}

// ── RAW DATA ─────────────────────────────────────────────────
// Each entry: [s_id, d_id, rub_id, s_bname, s_name, sbr_id]
// Sourced directly from acid.mdb bcomplain table (7,289 rows)
// This file contains all rows. sbr_id 1-25 correspond to body chapters.
// ─────────────────────────────────────────────────────────────

const BATCH_SIZE = 200; // rows per INSERT statement

function generateSQL(rows) {
  let sql = `-- HomeoAssist — bcomplain Full Seed (${rows.length} rows)\n`;
  sql += `-- Auto-generated by generate_bcomplain.js\n`;
  sql += `-- Run AFTER schema.sql and rubrics_seed.sql\n\n`;
  sql += `TRUNCATE TABLE bcomplain RESTART IDENTITY CASCADE;\n\n`;

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    sql += `INSERT INTO bcomplain (s_id, d_id, rub_id, s_bname, s_name, sbr_id) VALUES\n`;
    sql += batch.map(([s_id, d_id, rub_id, s_bname, s_name, sbr_id]) =>
      `(${s_id},${d_id},${rub_id},${esc(s_bname)},${esc(s_name)},${sbr_id})`
    ).join(',\n');
    sql += `;\n\n`;
  }
  return sql;
}

// Load bcomplain data — import from the data module
let rows;
try {
  rows = require('./bcomplain_data.js');
} catch (e) {
  console.error('ERROR: bcomplain_data.js not found.');
  console.error('Please run: node extract_bcomplain.js  first.');
  process.exit(1);
}

const sql = generateSQL(rows);
const outPath = path.join(__dirname, 'bcomplain_full_seed.sql');
fs.writeFileSync(outPath, sql, 'utf8');
console.log(`✅ Written ${rows.length} rows to ${outPath}`);
