"""
insert_all_medicines.py  — inserts ALL 1,612 medicines from acid.mdb into PostgreSQL
"""
import subprocess, sys
try:
    import psycopg2
except ImportError:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'psycopg2-binary', '-q'])
    import psycopg2

MEDICINES = [
(301,'Butyric acid',None,False),(302,'Buxus',None,False),(303,'Cacaodyl soda',None,False),
(304,'Cacsalpinia','K¨vwisKv',False),(305,'Cactus grandiflorus','K¨v±m †MÖwÛ',True),
(306,'Cadmium Bromatum',None,False),(307,'Cadmium iodat',None,False),(308,'Cadmium oxide',None,False),
(309,'Cadmium suiphuratum','K¨vWwgqg mvjwdD‡iUvg',False),(310,'Caffein',None,False),
(311,'Cahinca',None,False),(312,'Cainca','KvBb&Kv',False),(313,'Cajuputum','K¨vRycyUg',False),
(314,'Caladium','K¨vWwgqv †¯‹',False),(315,'Calcarea acetica','K¨v‡éwiqv GwmwUKv',False),
(316,'Calcarea arsenicum','K¨vj&‡Kwiqv Avm©',False),(317,'Calcarea bromatum',None,False),
(318,'Calcarea caleinata',None,False),(319,'Calcarea carbonica','K¨vj&‡Kwiqv KveŸ©',True),
(320,'Calcarea caustica','K¨vj&‡Kwiqv KwóKvg',False),(321,'Calcarea chlorinata',None,False),
(322,'Calcarea fluorata','K¨vj&‡Kwiqv d¬yI‡iUv',True),(323,'Calcarea hyphosporosa',None,False),
(324,'Calcarea iodata','K¨vj&‡Kwiqv Av‡qv‡WUv',False),(325,'Calcarea muriatica',None,False),
(326,'Calcarea ovi testae',None,False),(327,'Calcarea oxalica',None,False),
(328,'Calcarea phosphorica','K¨vj&‡Kwiqv dùwiKv',True),(329,'Calcarea picrica',None,False),
(330,'Calcarea renalis',None,False),(331,'Calcarea silcica','K¨v‡éwiqvg wmwj‡KU',False),
(332,'Calcarea sulphurica',None,False),(333,'Calcarea sulphuricum sti','K¨vj&‡Kwiqv mvjwdDwiKv',False),
(334,'Calculus',None,False),(335,'Calendula officinalis','K¨v‡jÛzjv Iwc',True),
(336,'Calliandra houstoni',None,False),(337,'Calotropis',None,False),
(338,'Camphora bromata',None,False),(339,'Camphora officinarum','K¨v‡ùviv Iwc',True),
(340,'Camphoric acid',None,False),(341,'Cancer astacus',None,False),
(342,'Canchalagua','K¨vš\'v‡j‡Mv',False),(343,'Cannabis indica','K¨vbvwem BwÛK',True),
(344,'Cannabis satiba','K¨vbvwem ‡mUv',False),(345,'Cantharidon',None,False),
(346,'Cantharis','K¨vš\'vwim',True),(347,'Capparis',None,False),(348,'Capsella',None,False),
(349,'Capsicum','K¨vwáKg',True),(350,'Carbamide',None,False),
(351,'Carbo animalis','Kv‡eŸ©v Gwb‡gwjm',True),(352,'Carbo vegetabilis','Kv‡eŸ©v †fwR‡Uewjm',True),
(353,'Carbolic acid','KveŸ©wjK GwmW',False),(354,'Carbon hydrogenisatum','KveŸ©wbqg nvB‡Wªv‡Rwb‡mUv',False),
(355,'Carbon tetrachol','KveŸ©wbqg mvjwdD‡iUvg',False),(356,'Carboneum',None,False),
(357,'Carboneum oxygenisatum','KveŸ©wbqg Aw´‡Rwb‡mUvg',False),(358,'Carboneum sulphuratum',None,False),
(359,'Carcinosin',None,False),(360,'Carduus benedictus',None,False),
(361,'Carduus marianus','KvWz©qvm †gwi‡qbvm',False),(362,'Carissa schim',None,False),
(363,'Carlsbad','Kvj©me¨vW',False),(364,'Carya alba',None,False),(365,'Cascarilla',None,False),
(366,'Cascars sagrads',None,False),(367,'Cassada','K¨v¯‹vwijv',False),
(368,'Cassia acutif',None,False),(369,'Castanea vesca','K¨vóvwbqv †f®‹v',False),
(370,'Castor equi','K¨vói BKzB',False),(371,'Castoreum','K¨v‡óvwiqg',False),
(372,'Catalpa',None,False),(373,'Cataria',None,False),
(374,'Caulophyllum','K‡jvdvBjvg',True),(375,'Causticum','KwóKg',True),
(376,'Ceanothus americanus','wm‡q‡iv_vm G‡gwiKvbvm',False),
(377,'Ceanothus thrysif','wm‡q‡iv_vm G‡gwiKvbvm',False),
(378,'Cedron','wm‡Wªvb',False),(379,'Cenchris contortrix','wmbwµm K‡›Uv',False),
(380,'Centaurea tagana','wm‡š\'wiqv',False),(381,'Cep',None,False),
(382,'Cephalandra indica',None,False),(383,'Cephalanthus',None,False),
(384,'Cerefolius',None,False),(385,'Cereus bonplandii','wmwiqvm ebe­¨vÛvB',False),
(386,'Cereus serpentaria','wmwiqvm mvi‡cb‡Uwiqvm',False),(387,'Cerium Oxalicum',None,False),
(388,'Cervus',None,False),(389,'Cetonia',None,False),
(390,'Cetrararia islandia','†m‡Uª‡iwiqv AvBj¨vÛ',False),
(391,'Chamomilla','K¨v‡gvwgjv',True),(392,'Champarro oemargoso',None,False),
(393,'Chaulmeogra',None,False),(394,'Cheiranthus',None,False),
(395,'Cheiranthus cheiri',None,False),(396,'Chelidonin',None,False),
(397,'Chelidonium majus','†Pwj‡Wvwbqg †gRvm',True),(398,'Chelone',None,False),
(399,'Chenopod aphis','†P‡bv‡cvwWqvg M­ywm Avwdm',False),
(400,'Chenopodium anthelminticum','†P‡bv‡cvwWqg q¨vb‡_jwgw›U',False),
(401,'Chenopodium vulvaria','‡P‡bv‡cvwWqg fvj‡fwiqv',False),
(402,'Chimaphila maculata',None,False),(403,'Chimaphila umbellata','wPgvwdjv †gKz‡jUv',False),
(404,'China boliviana',None,False),(405,'China officinalis','Pvqbv Awd',True),
(406,'Chininum arsenicosum','wPwbbvg Av‡m©wb‡Kvmvg',False),
(407,'Chininum brom','wPwbbg mjwdDwiKvg',False),
(408,'Chininum muriaticum','wPwbbvg †eªvg',False),
(409,'Chininum Salicylicum',None,False),(410,'Chininum sulphuricum',None,False),
(411,'Chiococea',None,False),(412,'Chionanthus virginica','wPIb¨vš\'m fv©wRwbKv',False),
(413,'Chloralum','†K¬v‡ijvg',False),(414,'Chloroformum','†K¬v‡ivdig',False),
(415,'Chlorum','†K¬vivg',False),(416,'Cholas terapina',None,False),
(417,'Cholesterinum','†Kv‡jw÷ªbvg',False),(418,'Choline',None,False),
(419,'Chopcheenea',None,False),(420,'Chromicum acidum','µwgKg GwmWg',False),
(421,'Chromicum oxydatum',None,False),(422,'Chromium sulphuricum',None,False),
(423,'Chrysophanicum acidum',None,False),(424,'Chrysorobinum',None,False),
(425,'Cicera arit',None,False),(426,'Cichorium',None,False),
(427,'Cicuta maculata',None,False),(428,'Cicuta virosa','wmwKDUv fvB‡ivmv',True),
(429,'Cimex','wmwgwmwdDMv',False),(430,'Cimicifuga','wmwgwmwdDMv',False),
(431,'Cina','wmbv',True),(432,'Cinararia maritima',None,False),
(433,'Cinchona bolviana',None,False),(434,'Cinchonium sulphuricum','wm‡¯‹vwbqg mjwdDwiKg',False),
(435,'Cinnabaris','wmbv‡ewim',False),(436,'Cinnamomum','wm‡i‡gvgvg',False),
(437,'Cisstus canadensis','wmóvm K¨v‡Wvwbmvm',False),(438,'Citric acid','mvBwUK GwmW',False),
(439,'Citrus decumana',None,False),(440,'Citrus limonum','mvBUªvm wj‡gvbvm',False),
(441,'Clematis erecta','wK¬‡gwUm B‡iKUv',False),(442,'Clematis vrtalba',None,False),
(443,'Clorodendron infortunatu',None,False),(444,'Clotho arictans',None,False),
(445,'Cltha palustris','K¨vjLv ‡cjvw÷ªqv',False),(446,'Cobaltum','†Kve¨vjUg',False),
(447,'Coca','†KvKv',False),(448,'Cocanum muriatcum','†Kvwm‡bjv †mÞvg',False),
(449,'Coccinella septemupunotata','†KvwWbg',False),(450,'Cocculus indicus','KwKDjvm',True),
(451,'Coccus cacti','K°m K¨vKUvB',False),(452,'Cochlearia armoracia',None,False),
(453,'Codenum','KjwPKvg',False),(454,'Coffea cruda','Kwdq µzo',True),
(455,'Coffea tosta','Kwdqv †Uvóv',False),(456,'Coffeinum',None,False),
(457,'Colchicin',None,False),(458,'Colchicum',None,False),
(459,'Collinsonia canadensis','Kwjm‡mv‡mqv K¨vbv',False),(460,'Colocynthinum',None,False),
(461,'Colocynthis','K‡jvwmw&¯\'m',True),(462,'Colostrum','†Kv‡jvm&Uªvg',False),
(463,'Comocladia dendata','†Kv‡gv‡K¬wWqv †WbWvUv',False),
(464,'Conbalaria majalis','Kbf¨v‡jwiqv †gR¨vwjm',False),(465,'Conbullus duartinus',None,False),
(466,'Conchiolinum',None,False),(467,'Condurango',None,False),
(468,'Coniinum bromatum',None,False),(469,'Conium maculatum','†Kv‡Kbvg wgDwiwUKvg',True),
(470,'Convallaria',None,False),(471,'Convulvus arvensis',None,False),
(472,'Copiva officinalis','†Kv‡cBfv Awd',False),(473,'Coqueluchin',None,False),
(474,'Corallium rubrum','†Kvi¨vwjqvg iƒeªvg',False),(475,'Corolorhiza',None,False),
(476,'Coriaria ruscifolia','‡Kvwiqvwiqv iƒwm‡dvwjqv',False),
(477,'Cornus alternifolia','KYv©m wmwiwmqv',False),(478,'Cornus circinata','KY©vm mviwmbvUv',False),
(479,'Cornus florida','KY©vm †d¬vwiWv',False),(480,'Corolorhiza',None,False),
(481,'Corydalis',None,False),(482,'Cota bark',None,False),
(483,'Cotyledon','†KvUvB‡jÛb Avg‡ewjKvm',False),(484,'Coumarin',None,False),
(485,'Covolvulusduartinus',None,False),(486,'Crataegus oxyacantha',None,False),
(487,'Crocus sativus','†µvKvm †mU',False),(488,'Crotalus cascavella','†µv‡Ujm K¨vm&Kvwfjv',False),
(489,'Crotalus horridus','†µv‡Ujvm nwiWvm',True),(490,'Croton chloral',None,False),
(491,'Croton tiglium','†µvUm wUwM­qvg',True),(492,'Cryptopinum',None,False),
(493,'Cubeba officinalis','wKD‡eev Awd',False),(494,'Cucarbita citrellus',None,False),
(495,'Cucarbita pepo',None,False),(496,'Culex moscae','wKD‡j´ gm&wm',False),
(497,'Cundurango','KwÛDi¨v‡½v',False),(498,'Cuphea viscossima',None,False),
(499,'Cupressus austral',None,False),(500,'Cupressus lawson',None,False),
(501,'Cuprum arsenicosum','KzcÖvg Av‡m©wb‡Kvbvgq',False),(502,'Cuprum nitricum',None,False),
(503,'Cuprum aceticum','KzcÖvg GwmwUKvg',False),(504,'Cuprum ammonia sulph',None,False),
(505,'Cuprum cyanatum',None,False),(506,'Cuprum metallicum',None,False),
(507,'Cuprum sulphuricum','KzcÖvg mvjwdDwiKvm',False),(508,'Curare','wKDivi',False),
(509,'Cuscus',None,False),(510,'Cusparia',None,False),
(511,'Cyclamen europaeum','mvBK¬v‡gb G‡iv',False),(512,'Cydonia',None,False),
(513,'Cymarin',None,False),(514,'Cynanchum',None,False),
(515,'Cypripedium pubescens','mvBwcÖwcwWqg cve',False),(516,'Cysticin',None,False),
(517,'Cystisus laburnum',None,False),(518,'Cystisus scopar',None,False),
(519,'Dapdne indica','W¨vcwW BwÛKv',False),(520,'Datura arborea',None,False),
(521,'Datura ferox',None,False),(522,'Datura metel',None,False),
(523,'Delphinus',None,False),(524,'Dematium petroeum','†Wwim wcbœvUv',False),
(525,'Derris pinnata',None,False),(526,'Desmodium gangeticum',None,False),
(527,'Dicentra',None,False),(528,'Dictamnus',None,False),
(529,'Digitalis purputea','wWwR‡Uwjm cvi',True),(530,'Digitoxinum',None,False),
(531,'Dioscorea villosa','Wvq‡¯‹vwiqv wf‡jv',True),(532,'Diosma',None,False),
(533,'Diphtherinum',None,False),(534,'Diphtherotoxin',None,False),
(535,'Dipodium',None,False),(536,'Diptrix',None,False),
(537,'Dirca palusris',None,False),(538,'Ditain',None,False),
(539,'Dolichos pruriens','†WvwjKvm cÖ€yiGÝ',False),(540,'Doorba',None,False),
(541,'Dorema',None,False),(542,'Doryphora','†Wvwi‡dviv',False),
(543,'Drosera rotundifolis','Wª‡miv †ivUz',True),(544,'Duboisia sulph',None,False),
(545,'Duboisinum','wW‡evqwmbvg',False),(546,'Dulcamara','Wvj&Kvgviv',True),
(547,'Echinacea angustifolia','BwP‡bwmqv Av‡Mwó‡dvwj',False),
(548,'Echinacea purpurea',None,False),(549,'Egg vaccine',None,False),
(550,'Elaeis',None,False),(551,'Elaeis guineensis','Bj¨vá',False),
(552,'Elaps corallinus',None,False),(553,'Elaterium','Bj¨vwUwiqvg',False),
(554,'Electricitas',None,False),(555,'Electron',None,False),
(556,'Elemuy',None,False),(557,'Emetine',None,False),
(558,'Enlexing',None,False),(559,'Eosin',None,False),
(560,'Ephedra vulgaris',None,False),(561,'Epigea repens','GwcwRhv wi‡cÝ',False),
(562,'Epilobium palustre',None,False),(563,'Epiphegus',None,False),
(564,'Equisetum','BKzB‡RUvg',False),(565,'Eranthis hyemale','BwiPw_wUm wnivwm‡dvwjqv',False),
(566,'Erechthites hieracifolia',None,False),(567,'Ergot',None,False),
(568,'Ergotin',None,False),(569,'Erigeron canadense',None,False),
(570,'Eriodictyon glutinosum',None,False),(571,'Erodium',None,False),
(572,'Eryngium aquaticum','Bwiwbqvg GKzwU‡qKvg',False),(573,'Eryngium maritinum',None,False),
(574,'Erythrac chiron','BwiwR‡ivb',False),(575,'Erythrinus',None,False),
(576,'Eschscholtzia',None,False),(577,'Escoba amargo',None,False),
(578,'Eserinum',None,False),(579,'Ether','B_vi',False),
(580,'Ethylum nitricum',None,False),(581,'Eucalyptol',None,False),
(582,'Eucalyptol rostr.',None,False),(583,'Eucalyptus globulus',None,False),
(584,'Eucalyptus tereticoris','BDK¨vwjÞvm',False),(585,'Eugenia chekum',None,False),
(586,'Eugenia jambos','BDwRwbqv R¨v‡¤^vm',False),(587,'Euonymin',None,False),
(588,'Euonymus astropur purea',None,False),(589,'Euonymus europaeus','BIbxgm BD‡ivwcqvm',False),
(590,'Eupatorium aromat',None,False),
(591,'Eupatorium perfoliatum','BD‡c‡Uvwiqvg cv‡dv©wj‡qUv',True),
(592,'Eupatorium purpur','BD‡c‡UBiqv cvwcDwiqvg',False),
(593,'Euphorbia amygdal',None,False),(594,'Euphorbia corollata',None,False),
(595,'Euphorbia cyparissias',None,False),(596,'Euphorbia heterodoxa',None,False),
(597,'Euphorbia hypericifolia',None,False),(598,'Euphorbia ipecacuanha',None,False),
(599,'Euphorbia pilulifera',None,False),(600,'Euphorbia resinifera',None,False),
(601,'Euphorbium','BDdiweqg',False),(602,'Euphorbium lathyris',None,False),
(603,'Euphorbium marg',None,False),(604,'Euphorbium peplus',None,False),
(605,'Euphorbium pilulifera',None,False),(606,'Euphrasia officinalis','BD‡d«wmqv Iwc',True),
(607,'Eupionum','BDwcIb',False),(608,'Fabiana',None,False),
(609,'Fagopyrum','d¨v‡MvcvBivm',False),(610,'Fagus syivatica',None,False),
(611,'Fel tauri',None,False),(612,'Ferrum Aeeticum',None,False),
(613,'Ferrum arsenicicum','†divg Av‡m©wbKvg',False),(614,'Ferrum Bromatum',None,False),
(615,'Ferrum carbonicum',None,False),(616,'Ferrum citric',None,False),
(617,'Ferrum cyanatum',None,False),(618,'Ferrum lacticum',None,False),
(619,'Ferrum magneticum','†divg g¨vM‡bwUKvg',False),(620,'Ferrum pernitricum','†divg dm&dwiKvg',False),
(621,'Ferrum phosphoricum',None,False),(622,'Ferrum phosphoricum hydricum',None,False),
(623,'Ferrum picricum','†divg wcKw&µK',False),(624,'Ferrum poryphos',None,False),
(625,'Ferrum protoxal',None,False),(626,'Ferrum sulphuricum','†divg mjwdDwiKvg',False),
(627,'Ferrum tertaricum',None,False),(628,'Ferula glauca',None,False),
(629,'Ferula sumbul',None,False),(630,'Ferum iodatum','†divg Av‡qvW',False),
(631,'Ferum metallicum','†divg †gU',True),(632,'Ferum muriaticum','†divg wgDwiGwUKvg',False),
(633,'Ficus religiosa',None,False),(634,'Ficus indica',None,False),
(635,'Ficus venosa',None,False),(636,'Filix mas','wdwj· gvm',False),
(637,'Floroform',None,False),(638,'Fluoricum acidum','d¬yIwiKg GwmW',True),
(639,'Formalin',None,False),(640,'Formica rufa','dw¤§©Kv',False),
(641,'Formic acid',None,False),(642,'Fragaria vesca',None,False),
(643,'Franciscea uniflora',None,False),(644,'Frangula','d«b&‡Mwiqv †fmKv',False),
(645,'Franzensbad',None,False),(646,'Fraxinus americana',None,False),
(647,'Fucus vesiculosus',None,False),(648,'Fugus',None,False),
(649,'Fuligo ilgni',None,False),(650,'Fushina',None,False),
(651,'Gadus morrhus',None,False),(652,'Gaertner',None,False),
(653,'Galanlhusniv',None,False),(654,'Galega',None,False),
(655,'Galega officinalis',None,False),(656,'Galipea',None,False),
(657,'Galium aparine',None,False),(658,'Gallicum acidum','M¨vwjKvg GwmW',False),
(659,'Galvanismus',None,False),(660,'Gambogia',None,False),
(661,'Garcina morella',None,False),(662,'Gastein',None,False),
(663,'Gaultheria',None,False),(664,'Gelsemium sempervirens','†Rjwmwgqg',True),
(665,'Genista tinctoria','†Rwbóv',False),(666,'Gentiana cruciata','†Rb&wmAvbv jywmqv',False),
(667,'Gentiana lutea','†Rb&wmAvbv jywmqv',False),(668,'Gentiana quinqueflora','†Rb&wmAvbv µzwmqvUv',False),
(669,'Geranin',None,False),(670,'Geranium maculatum',None,False),
(671,'Gettisburg water','†MwUm&ev©M',False),(672,'Gettysburg',None,False),
(673,'Geum rival',None,False),(674,'Ginseng','wRb&‡m½',False),
(675,'Glanderine','M­¨vÛvwib',False),(676,'Gle chomahed',None,False),
(677,'Glonoin','y‡M­vwbqb',True),(678,'Glycerinum',None,False),
(679,'Gnaphalium','b¨vdvwjqvg',False),(680,'Golondrina',None,False),
(681,'Gossypium herbaceum','Mwmwcqg',False),(682,'Granatum punica','MÖ¨v‡bUvg',False),
(683,'Graphites','MÖ¨vdvBwUm',True),(684,'Gratiola officinalis','MÖ¨vwUIjv',False),
(685,'Grindelia robusta','wMÖ‡Ûwjqv',False),(686,'Guaca','¸qBKvg',False),
(687,'Guaco','†Mvqv‡Kv',False),(688,'Guaiacum',None,False),
(689,'Guano',None,False),(690,'Guao',None,False),
(691,'Guarana','¸qvivbv',False),(692,'Guarea',None,False),
(693,'Guipsine',None,False),(694,'Gummigutti',None,False),
(695,'Gunpowder',None,False),(696,'Gymnema sylvestre',None,False),
(697,'Gymnocladus canadensis','‡Rg&‡bv‡K¬Wvm',False),(698,'Haematoxylon',None,False),
(699,'Hagenia abys',None,False),(700,'Hall',None,False),
(701,'Hamamelis virginica','n¨vgv‡gwjm',True),(702,'Heamatoxylan','wn‡gUw´‡jvb',False),
(703,'Hecla lava','†nK&jv jvfv',False),(704,'Hedeoma','†nwW‡qvgv cy‡jwR‡qWvm',False),
(705,'Hedeoma pulegioides',None,False),(706,'Hedera helix',None,False),
(707,'Hedysarum',None,False),(708,'Helianthus',None,False),
(709,'Heliotropium',None,False),(710,'Helix tosta',None,False),
(711,'Hellebborus niger','†nwj‡evivm bvBRvi',True),(712,'Helleborns orientalis',None,False),
(713,'Helleborus foetidus',None,False),(714,'Helledonus viridis',None,False),
(715,'Heloderma','wn‡jvWvigv †nvwiWvm',False),(716,'Helonias dioica','wn‡jvwbqvm',False),
(717,'Hemintochortos',None,False),(718,'Henchera',None,False),
(719,'Hepatica',None,False),(720,'Heper sulphuris calcareum','wncvi mvjd',True),
(721,'Heraclcum',None,False),(722,'Hippomanes','wn‡cv‡gbwm',False),
(723,'Hippozaenium','wn‡cvwRwbb&',False),(724,'Hippuric acid',None,False),
(725,'Hoang nan',None,False),(726,'Hoitza',None,False),
(727,'Homaria',None,False),(728,'Homarus','†nvgvivm',False),
(729,'Humea elegeans',None,False),(730,'Humulus lupulus',None,False),
(731,'Hura braziliensis','nviv †eªwRwjGbwmm&',False),(732,'Hura crepitans',None,False),
(733,'Hydrangea','nvBWª¨vwÄqv',False),(734,'Hydrangea arborescens',None,False),
(735,'Hydrargyrum',None,False),(736,'Hydrast sulph',None,False),
(737,'Hydrastininum muriaticum acid',None,False),(738,'Hydrastinum mur',None,False),
(739,'Hydrastis canadensis','nvBWªvm&wUm K¨vb',True),(740,'Hydrobromic acid',None,False),
(741,'Hydrocotyle asiatica','nvB‡WWªv‡KvUvBj',False),(742,'Hydrofluoricum',None,False),
(743,'Hydrophobinum','jvBwmb',False),(744,'Hydrophylum virginianum',None,False),
(745,'Hydropiper',None,False),(746,'Hyocin hydrobrom',None,False),
(747,'Hyoscyaminum','nvBIqvGgvm',False),(748,'Hyoseyamus',None,False),
(749,'Hyoxyaminum sulphuricum',None,False),(750,'Hypericum perforatum','nvBwcwiKvg',True),
(751,'Iberis amara','AvB‡ewim',False),(752,'Ichthyotoxin',None,False),
(753,'Ictodes foetida','BK&‡UvWvm †dwUWvm',False),(754,'Ignatia amara','B‡Mœwmqv',True),
(755,'Ikshugandha',None,False),(756,'Ilex aquif',None,False),
(757,'Ilex cassine',None,False),(758,'Illicium','Bwj­Kvg',False),
(759,'Illicium anisatum',None,False),(760,'Imperatoria',None,False),
(761,'Indigo','BwÛ‡Mv',False),(762,'Indium metallicum','BwÛqvg †gUv',False),
(763,'Indol',None,False),(764,'Ingluvin',None,False),
(765,'Insulin',None,False),(766,'Inula helenium','BwbDjv',False),
(767,'Iodium','AvBIWvg',True),(768,'Iodoformum',None,False),
(769,'Iodothyrine',None,False),(770,'Ioduretted potass iod',None,False),
(771,'Ipecacuanha','BwcKvKzqvbv',True),(772,'Ipomea purpurea','AvB‡cvwgqv cviwcDwiqv',False),
(773,'Iridium','BwiwWqvg',False),(774,'Iridium chlor',None,False),
(775,'Iris florentina','AvBwim wdwUwWwmgv',False),(776,'Iris foetidissima','AvBwim †d¬v‡i›Ubv',False),
(777,'Iris Gemanica','AvBwim †R‡gwbKv',False),(778,'Iris minor',None,False),
(779,'Iris tenax',None,False),(780,'Iris versicolor','AvBwim fvwm‡Kvjvi',True),
(781,'Isotonic plasma',None,False),(782,'Itu',None,False),
(783,'Jaborandi','R¨v‡evi¨vwÛ',False),(784,'Jacaranda gualandai','R¨v‡Kv‡iwÛqv †K‡ivev',False),
(785,'Jacarandia caroba','R¨v‡KvivwÛqv',False),(786,'Jacea',None,False),
(787,'Jalapa','R¨vjvcv',False),(788,'Jambosa',None,False),
(789,'Jasminum',None,False),(790,'Jatropha curcas','R¨v‡Uªvdv KviKvm',False),
(791,'Jatropha urens',None,False),(792,'Jequiritol',None,False),
(793,'Jequirity',None,False),(794,'Jonosia',None,False),
(795,'Juglans cinerea','RyM­vÝ wm‡bvwiqv',False),(796,'Juglans regia','RyM­vÝ wiwRqv',False),
(797,'Juglendin',None,False),(798,'Jumcus effusus','RvgKvm BwdDKvm',False),
(799,'Juniperus communis',None,False),(800,'Juniperus virginianus','†Rwbcvivm fvwR©wbbv',False),
(801,'Justica',None,False),(802,'Justicia adhatoda',None,False),
(803,'Justicia rubrom',None,False),(804,'Kalagua',None,False),
(805,'Kali aceticum','†Kwj GwmwUKvg',False),(806,'Kali arsenicosum','†Kwj Av‡m©',False),
(807,'Kali bichromicum','†Kwj evB‡µvwgKg',True),(808,'Kali bromatum','†Kwj †eªv‡gUvg',True),
(809,'Kali carbonicum','†Kwj Kv‡eŸ©vwbKvg',True),(810,'Kali causticum',None,False),
(811,'Kali chloricum','†Kwj †K¬vwiKg',False),(812,'Kali chlorosum',None,False),
(813,'kali citricum',None,False),(814,'Kali cyanatum','†Kwj mv‡q‡bUvg',False),
(815,'Kali ferrocyanitum','†Kwj †d‡iv mv‡qvbvBU',False),(816,'Kali hydriodicum',None,False),
(817,'Kali hypophosphite',None,False),(818,'Kali iodatum','†Kwj AvBI‡WUg',True),
(819,'Kali maganicum','†Kwj g¨v‡½wbg',False),(820,'Kali muriaticum','†Kwj wgD†qwiwUKvg',True),
(821,'Kali nitricum','†Kwj bvBwUªKg',True),(822,'Kali oxalicum','†Kwj Aw·wjKvg',False),
(823,'Kali permanganum',None,False),(824,'Kali phosphoricum','†Kwj dùwiKvg',True),
(825,'Kali picricum',None,False),(826,'Kali picro nitricum',None,False),
(827,'Kali salicylicum',None,False),(828,'Kali silicum',None,False),
(829,'Kali sulph chrom',None,False),(830,'Kali sulphuratum',None,False),
(831,'Kali sulphuricum','†Kwj mvjwdDwiKvg',True),(832,'Kali tartaricum',None,False),
(833,'Kali telluricum',None,False),(834,'Kalmegh',None,False),
(835,'Kalmia latifolia','K¨vj&wgqv',True),(836,'Kaolinum','KvIwjb',False),
(837,'Karaka',None,False),(838,'Kava kava',None,False),
(839,'Keroselenum',None,False),(840,'Kissingen','wK‡mÄb',False),
(841,'Koch\'s lymph',None,False),(842,'Kola',None,False),
(843,'Kousso',None,False),(844,'Krameria',None,False),
(845,'Kreosotum','wµ‡qv‡RvU',True),(846,'Laburnum',None,False),
(847,'Lac canium','j¨vK& K¨vbvBbg',False),(848,'Lac defloratum','j¨vK& wW‡d¬v‡iUvg',False),
(849,'Lac felinum','j¨vK &‡dwjbvg',False),(850,'Lac vacc coagulatum',None,False),
(851,'Lac vacc floc',None,False),(852,'Lac vaccinum',None,False),
(853,'Lacerta',None,False),(854,'Lachesis lanceolat',None,False),
(855,'Lachessis','j¨v‡Kwmm',True),(856,'Lachnathes tinctoria','j¨vK&‡bb&w_m',False),
(857,'Lactic acid','j¨vK&wcK GwmW',False),(858,'Lactuca virosa','j¨vK‡UvKv wf‡ivmv',False),
(859,'Laffa acutang','j¨vcv Av‡iKwUqvg',False),(860,'Lamium album','j¨vwgqg',False),
(861,'Lapathum',None,False),(862,'Lapis albus','j¨vwcm Gj¦vg',False),
(863,'Lapis renalis',None,False),(864,'Lappa major',None,False),
(865,'Lapsana communis',None,False),(866,'Lathyrus sativus','j¨vw_ig',False),
(867,'Latrodectus hssetti','j¨vK&‡Uv‡WK&Uvm g¨vK‡Ubvm',False),
(868,'Latrodectus katipo',None,False),(869,'Latrodectus mactans',None,False),
(870,'Laurocerasus','j‡ivwm‡imvm',False),(871,'Laurustinus',None,False),
(872,'Lava scoriac',None,False),(873,'Lctodos',None,False),
(874,'Lecithin','j¨vwmw_b',False),(875,'Ledum palustre','wjWg',True),
(876,'Lemna minor','j¨vgbv gvBbi',False),(877,'Leonurus cordiaca',None,False),
(878,'Lepidium bonariense','wjwcwWqvg †evbvwiGbvwm',False),
(879,'Leptandra virginca','†jÞÊªv fvwR©wbKv',False),(880,'Leptilon',None,False),
(881,'Levico',None,False),(882,'Liatris spicata',None,False),
(883,'Lignum vitac',None,False),(884,'Lilium tigrinum','wjwjqg wUwMÖbg',True),
(885,'Limulus',None,False),(886,'Linaria',None,False),
(887,'Linum catharticum','wjbvg K¨v_vi',False),(888,'Linum usitatissimum',None,False),
(889,'Lippia mexicana',None,False),(890,'Lippspringe',None,False),
(891,'Lithium benzoicum',None,False),(892,'Lithium bromatum',None,False),
(893,'Lithium carbonicum','wjw_qg KveŸ©wbKg',False),(894,'Lithium lacticum','wjw_qb wgDwiGwUKg',False),
(895,'Lithium muriaticum',None,False),(896,'Lob inflata','†jvwewjqv Bb&d¬vUv',True),
(897,'Lobelia acetum.',None,False),(898,'Lobelia cardinalis','†jvwewjqv KvwW©‡bwj',False),
(899,'Lobelia dortmanna',None,False),(900,'Lobelia erinus',None,False),
(901,'Lobelia purpurascens',None,False),(902,'Lobelia syphilitica','†jvwewjqv wmwdwjwUK',False),
(903,'Lolium temulentum',None,False),(904,'Lonicera',None,False),
(905,'Lonicera xylostem',None,False),(906,'Lonicera pericylmenum',None,False),
(907,'Luffa amera',None,False),(908,'Luffa bindal',None,False),
(909,'Luna',None,False),(910,'Lupulin',None,False),
(911,'Lupulus','wjDcyjm',False),(912,'Lycopersicum','jvB‡KvcvwmKvg',False),
(913,'Lycopodium clavatum','jvB‡Kv‡cvwWg',True),(914,'Lycopus virginicus','jvB‡KvWvm fvwnwbKvm',False),
(915,'Lysidinum',None,False),(916,'Lysimachia',None,False),
(917,'Macrotinum',None,False),(918,'Macrotys rocemosa',None,False),
(919,'Macrozamia',None,False),(920,'Macuna',None,False),
(921,'Madura alb',None,False),(922,'Magnesia',None,False),
(923,'Magnesia carbonica','g¨vM&wbwmqv KveŸ©wbKv',True),(924,'Magnesia muriatica','g¨vM‡bwbqv wgDwi‡qwUKv',True),
(925,'Magnesia phosphorica','g¨vM‡bwmqv dùwiKvg',True),(926,'Magnesia sulphurica','g¨vM&‡bwmqv mvjwdDwiKv',True),
(927,'Magnetis poli. ambo','g¨vM‡b‡UR †cvwj Gg‡ev',False),
(928,'Magnetis polus arcticus','g¨vM‡bwURg †cvjvm AvwU©Kv',False),
(929,'Magnetis polus australis',None,False),(930,'Magnola grandiflora',None,False),
(931,'Magnolia glauca',None,False),(932,'Magresia oxydata',None,False),
(933,'Mahonia',None,False),(934,'Malandrinum','g¨v‡jwÛªbvg',False),
(935,'Malaria officinalis','g¨v‡jwiqv Awdwm‡bwjm',False),(936,'Mallein',None,False),
(937,'Manaca',None,False),(938,'Managanum aceticum',None,False),
(939,'Managanum carbonicum',None,False),(940,'Mancinella',None,False),
(941,'Mandragora',None,False),(942,'Manganum','g¨v‡½bvg',True),
(943,'Manganum colloidal',None,False),(944,'Manganum muriaticum','g¨v‡½bg wgDwiGwUKg',False),
(945,'Manganum sulphuricum',None,False),(946,'Mangifera',None,False),
(947,'Mangunum oxydatum nativum',None,False),(948,'Manzanita',None,False),
(949,'Mapato',None,False),(950,'Marum verum',None,False),
(951,'Matica',None,False),(952,'Mattahiola graeca',None,False),
(953,'Medicago',None,False),(954,'Medorrhinum','†g‡Wvwibvg',True),
(955,'Medusa',None,False),(956,'Megvet pol.austrul','g¨vM‡bwURg‡cvjvmAvm‡Uªwjm',False),
(957,'Melastoma',None,False),(958,'Melcum sale',None,False),
(959,'Melilotus','†gwj‡jvUvm',False),(960,'Melilotus alba',None,False),
(961,'Melitagrinum',None,False),(962,'Mellefolium','wgwj‡dvwjqvg',False),
(963,'Menispermum',None,False),(964,'Mentha piperita',None,False),
(965,'Mentha pulegium','†gš\'v wc‡cwiUv',False),(966,'Mentha virid',None,False),
(967,'Menthol',None,False),(968,'Menyanthes','wgwbGw¯\'m',False),
(969,'Mephitis','wgdvBwUm',False),(970,'Mercurialis',None,False),
(971,'Mercurialis perennis',None,False),(972,'Mercurirs sulphocynotus',None,False),
(973,'Mercurirs sulphuricus',None,False),(974,'Mercurius aceticus','gv©Kzwiqvm GwmwUKvm',False),
(975,'Mercurius auratus',None,False),(976,'Mercurius biniodatus',None,False),
(977,'Mercurius bromatum',None,False),(978,'Mercurius corrosivus','gvKz©wiqvm Ki',True),
(979,'Mercurius cyanatus','gv©Kzwiqvm mv‡qv‡bUvm',False),
(980,'Mercurius dulcis','gvKz©wiqvm-Wvj&wmm',False),(981,'Mercurius et.kali iodatum',None,False),
(982,'Mercurius hannemanni Sol','gv©Kzwiqvm mj',False),
(983,'Mercurius iodatus flavus','gvKzwi©qvm Av‡qv †d¬fvg',False),
(984,'Mercurius iodatus ruber','gvKzw©iqvm Av‡qv i€eªvg',False),
(985,'Mercurius nitricus','gvKz©wiqvm bvB‡Uªvmvm',False),(986,'Mercurius Oxydulatus niger',None,False),
(987,'Mercurius phosphor',None,False),(988,'Mercurius praecip ruber','gv©Kzwiqvm cÖvwm i€evi',False),
(989,'Mercurius precitatus albus',None,False),(990,'Mercurius proto.iodatus',None,False),
(991,'Mercurius sub.corros',None,False),(992,'Mercurius sulph .rub',None,False),
(993,'Mercurius tannicus',None,False),(994,'Mercurius Sol','gvKzwiqv©m fvBfvm',True),
(995,'Meriatic acid','wgDwiwUKvg GwWm',False),(996,'Methylene blue',None,False),
(997,'Methylium salicyl',None,False),(998,'Mezereum','‡g‡Rwiqvg',True),
(999,'Micania guacho',None,False),(1000,'Micromeria',None,False),
]

conn = psycopg2.connect(host='127.0.0.1', port=5432, dbname='homeoassist', user='postgres', password='oyshiaka123')
cur = conn.cursor()
inserted = skipped = 0
for mid, txt, btxt, du in MEDICINES:
    cur.execute("INSERT INTO medicines (m_id,m_txt,m_btxt,m_du) OVERRIDING SYSTEM VALUE VALUES (%s,%s,%s,%s) ON CONFLICT (m_id) DO NOTHING", (mid,txt,btxt,du))
    if cur.rowcount > 0: inserted += 1
    else: skipped += 1
conn.commit()
cur.execute("SELECT COUNT(*) FROM medicines")
print(f"Batch 2: Inserted={inserted} Skipped={skipped} Total={cur.fetchone()[0]}")
cur.close(); conn.close()
