-- HomeoAssist seed: medicines_mdb
-- Source: acid.mdb

INSERT INTO medicines_mdb (m_id, m_txt, m_btxt, m_du) VALUES
(1, 'Abies canadansis', 'Gwem K¨vbv‡Wbwmm', '1'),
(2, 'Abies nigra', 'Gwem bvBMÖv', '1'),
(3, 'Abroma', '**', NULL),
(4, 'Abroma radix', '**', NULL),
(5, 'Abrotanum', 'G‡eªv‡Ubvg', '1'),
(6, 'Absinthium', 'Ge&wmb&w_qg', '1'),
(7, 'Acalypha indica', 'G‡Kwjdv BwÛKv', '1'),
(8, 'Acanthia', NULL, NULL),
(9, 'Acarus', '**', NULL),
(10, 'Aceranlidum(Anti fibrium)', NULL, NULL),
(11, 'Acetic acid', 'GwmwUK GwmW', '1'),
(12, 'Achyranthes', NULL, NULL),
(13, 'Aconitinum', '**', NULL),
(14, 'Aconitum anthora', '**', NULL),
(15, 'Aconitum cammarum', 'G‡KvbvBUvg K¨vg¨vivg', '1'),
(16, 'Aconitum ferox', 'G‡KvbvBUvg †di´', '1'),
(17, 'Aconitum lycoctonum', 'G‡KvbvBU jvB‡Kv‡Uvbvg', '1'),
(18, 'Aconitum napellus', 'G‡KvbvBU †bwcjvm', '1'),
(19, 'Aconitum septentrionale*', '**', '1'),
(20, 'Actaea racemosa', '**', NULL),
(21, 'Actaea spicata', 'GK&wUqv w¯ž‡KUv', '1'),
(22, 'Adetheidsquellus*', '**', NULL),
(23, 'Adonidin*', '**', NULL),
(24, 'Adonis vernalis', '**', NULL),
(25, 'Adrenalin', '**', NULL),
(26, 'Aegle folia*', '**', NULL),
(27, 'Aegle marmals*', '**', NULL),
(28, 'AEsculus glabra', 'B¯‹zDjvm M­¨veªv', '1'),
(29, 'Aesculus hippocastanum', 'Bw¯‹Djvm wn‡cvKv‡óbvg', '1'),
(30, 'Aethiops antimonialis', '**', NULL),
(31, 'Aethiops merc', '**', NULL),
(32, 'AEthusa cynapium', 'B_yRv', '1'),
(33, 'Agaricin', '**', NULL),
(34, 'Agaricus campanulutus', '**', NULL),
(35, 'Agaricus campestris', '**', NULL),
(36, 'Agaricus citrinus', '**', NULL),
(37, 'Agaricus emeticus', 'GMvwiKvm GwgwUKvm', '1'),
(38, 'Agaricus muscarius', 'GMvwiKvm gv‡¯‹wiqvm', NULL),
(39, 'Agaricus pantherinus', '**', '1'),
(40, 'Agaricus phalloides', 'GMvwiKvm d¨vjGW&m&', NULL),
(41, 'Agaricus procerus', '**', NULL),
(42, 'Agaricus semiglobatus', '**', NULL),
(43, 'Agave americana', '**', NULL),
(44, 'Agnus castus', 'GMœvm K¨vmUvm', '1'),
(45, 'Agraphis nutans', '**', NULL),
(46, 'Agrimonia', '**', NULL),
(47, 'Agropyrum', '**', NULL),
(48, 'Agrostemma githago', '**', NULL),
(49, 'Agrostis', '**', NULL),
(50, 'Ailanthus glandulosa', 'GBj¨vš’¨vm', '1'),
(51, 'Alcohol', 'Gj‡Kvnj', '1'),
(52, 'Alcohol sulphuris', '**', NULL),
(53, 'Aletris farinosa', 'G‡jwUªm †dwi‡bvmv', '1'),
(54, 'Alfalfa', '**', NULL),
(55, 'Alkekengi', '**', NULL),
(56, 'Allium cepa', 'Gwjqvg wmcv', '1'),
(57, 'Allium sativum', 'Gwjqg m¨vwUfg', '1'),
(58, 'Alnus', '**', NULL),
(59, 'Aloe socotrina', 'G‡jvR', '1'),
(60, 'Alstonia constricta', 'G‡j‡óvwbqv Kb&wóªKUv', '1'),
(61, 'Alstonia scholaris', '**', NULL),
(62, 'Althaca', '**', NULL),
(63, 'Alumen', '&Gjy‡gb', '1'),
(64, 'Alumin acet', '**', NULL),
(65, 'Alumin chor.', '**', NULL),
(66, 'Alumin oxide', '**', NULL),
(67, 'Alumin sil sulph', '**', NULL),
(68, 'Alumina', 'Gjywgbv', '1'),
(69, 'Alumina silicata', '**', NULL),
(70, 'Aluminium metallicum', 'Gjywgwbqg †gU', '1'),
(71, 'Aluminium silicata', 'Gjywgbv mvBwj', '1'),
(72, 'Amanita agaricus', '**', NULL),
(73, 'Amanita phallo', NULL, NULL),
(74, 'Amanita vernus', '**', NULL),
(75, 'Ambra grisea', 'Avgeªv wMÖwmqv', '1'),
(76, 'Ambrosia artemisiae foli', 'Avg‡eªvwmqv AvwUwgwmqv ‡d', NULL),
(77, 'Ammmonium hydrate', '**', NULL),
(78, 'Ammoniacum benzoicum', 'G‡gvwbqvg †e‡ÄvKvg', '1'),
(79, 'Ammoniacum bromatum', 'G‡gvwbqg †eªv‡gUg', '1'),
(80, 'Ammoniacum carbonicum', 'G‡gvwbqg KveŸ©wbKvg', '1'),
(81, 'Ammoniacum causticum', 'G‡gvwbqvg KvwóKvg', '1'),
(82, 'Ammoniacum gummi', 'GgwbGKvg Mvw¤§', NULL),
(83, 'Ammoniacum muriaticum', 'G‡gvwbqg wgDwi‡qwUKvg', '1'),
(84, 'Ammonium aceticum', '**', NULL),
(85, 'Ammonium formald', '**', NULL),
(86, 'Ammonium hydr', NULL, NULL),
(87, 'Ammonium iodum', '**', NULL),
(88, 'Ammonium nitricum', '**', NULL),
(89, 'Ammonium phosphoricum', '**', NULL),
(90, 'Ammonium picricum', '**', NULL),
(91, 'Ammonium tartaricum', '**', NULL),
(92, 'Amon veler', '**', NULL),
(93, 'Amon vened', '**', NULL),
(94, 'Ampelopsis', '**', NULL),
(95, 'Ampelopsis trifol', '**', NULL),
(96, 'Amphisboena', 'Ggwdmwe‡qbv', '1'),
(97, 'Amygdalae am. aqua', 'GwgM&‡Wwj G‡gwi', '1'),
(98, 'Amygdalae persica', '**', NULL),
(99, 'Amyl nitrite', 'Gwgj bvBUªvBU', '1'),
(100, 'Amyla mine chlorohydrate', '**', NULL),
(101, 'Anacardium occidentale', 'GbvKvwWqg Aw·', '1'),
(102, 'Anacardium orientale', 'GbvKvwWqvg Iwi‡qb', '1'),
(103, 'Anagallis arvensis', 'Gbv‡Mwjm Avi‡ebwmm', '1'),
(104, 'Anagyris', '**', NULL),
(105, 'Anantherum mur', NULL, NULL),
(106, 'Ancistrodon contorix', '**', NULL),
(107, 'Andersonia', '**', NULL),
(108, 'Andrina araroba', '**', NULL),
(109, 'Andrina lactra', '**', NULL),
(110, 'Andromeda', NULL, NULL),
(111, 'Anemopsis', '**', NULL),
(112, 'Angelica atropurpurea', '**', NULL),
(113, 'Angophora', '**', NULL),
(114, 'Angophora(Kino)', 'wK‡bv', NULL),
(115, 'Anguillar ichthy serum', NULL, NULL),
(116, 'Angustura spuria', '**', NULL),
(117, 'Angustura vera', '**', '1'),
(118, 'Anhalonium', NULL, NULL),
(119, 'Anhalonium lewinii', 'G½óziv †fiv', NULL),
(120, 'Anilinum', 'Gwbwjbvg', '1'),
(121, 'Anisum stellatum(Illecebrum  anisatum)', 'Gwbmvm wó&‡jUvg', NULL),
(122, 'Anthernis nobilis', 'Gwš’wgm †bvwewjm', NULL),
(123, 'Anthoxanthum', 'Gb_ªvwmbvg', NULL),
(124, 'Anthracinum', '**', NULL),
(125, 'Anthrokokali', 'Gb&_ªv‡Kvwjbvg', NULL),
(126, 'Antiarus tox', 'Gw›U‡gvwbqg UvU©', NULL),
(127, 'Antimonium arsenic', 'Gw›U‡gvwbqg Avm©', NULL),
(128, 'Antimonium chloridum', 'Gw›U‡gvwbqvg †K¬vwiWvg', NULL),
(129, 'Antimonium crudum', 'Gw›U‡gvwbqg µzWg', '1'),
(130, 'Antimonium et potass tar', '**', '1'),
(131, 'Antimonium iodum', '**', NULL),
(132, 'Antimonium metalcum', NULL, NULL),
(133, 'Antimonium muriaticum', '**', '1'),
(134, 'Antimonium oxidum', 'Gw›U‡gvwbqvg Aw·‡WUvg', NULL),
(135, 'Antimonium sulph aur', '**', NULL),
(136, 'Antimonium sulphuratum aureum', 'Gw›U‡gvwbqg mvj&d,A‡iUg', NULL),
(137, 'Antipyrinum', '**', NULL),
(138, 'Aphis chenopodii glauci', 'Gwdm wP‡bv‡cvWvB M­mvB', NULL),
(139, 'Apis Mel', 'Gwcm †gj', NULL),
(140, 'Apium graveolens', '**', NULL),
(141, 'Apium virus', NULL, NULL),
(142, 'Apocynum andros', 'G‡cvmvBbvg G‡Ûvm Gwg‡dvwj', NULL),
(143, 'Apocynum cannabinum', 'G‡cvmvBbvg K¨vbvwebg', NULL),
(144, 'Apomorphinum', 'G‡cvmvBbvg G‡Ûvm Gwg‡dvwj', NULL),
(145, 'Apomorphium muriaticum', '**', NULL),
(146, 'Aqua  regia', NULL, NULL),
(147, 'Aqua calcarea', '**', NULL),
(148, 'Aqua marina', '**', NULL),
(149, 'Aqua petra', '**', NULL),
(150, 'Aqua sanicula', NULL, NULL),
(151, 'Aquilegia', '**', NULL),
(152, 'Aquilegia vulgaris', '**', NULL),
(153, 'Aragallus', '**', NULL),
(154, 'Aralia hispida', '**', NULL),
(155, 'Aralia quinquefol', '**', NULL),
(156, 'Aralia racemosa', 'Givwjqv †iwm‡gvmv', NULL),
(157, 'Aramearamtela', '**', NULL),
(158, 'Aranea diadema', 'Givwjqv Wv‡q‡Wgv', NULL),
(159, 'Aranea scinencia', 'Givwbqv w¯‹‡bwmqv', NULL),
(160, 'Aranearum tela', '**', NULL),
(161, 'Arburs procatorius', '**', NULL),
(162, 'Arbutin', '**', NULL),
(163, 'Arcea', '**', NULL),
(164, 'Arctium lappa(Lappa arctium)', '**', NULL),
(165, 'Arctosphylos', '**', NULL),
(166, 'Argemone', NULL, NULL),
(167, 'Argentum eyanidum', 'Av‡R©›Uvg mv‡qwbWvg', NULL),
(168, 'Argentum iodatum', '**', NULL),
(169, 'Argentum metallicum', 'Av‡R©›Uvg †gUvwjKvg', NULL),
(170, 'Argentum muriaticum', 'Av‡R©›Uvg wgDwiGwUKvg', NULL),
(171, 'Argentum nitricum', 'Av‡R©›Uvg bvBwUªKvg', NULL),
(172, 'Argentum oxydatum', '**', NULL),
(173, 'Argentum phosphoricum', '**', NULL),
(174, 'Aristolochia milhomens', '**', NULL),
(175, 'Aristolochia serpentaria', '**', NULL),
(176, 'Armoracia sativa', '**', NULL),
(177, 'Arnica montana', 'Avwb©Kv g‡›Ubv', NULL),
(178, 'Arsenicum album', 'Av‡m©wbK Gj¦vg', NULL),
(179, 'Arsenicum bromatum', '**', NULL),
(180, 'Arsenicum hydrogenisatum', 'Av‡m©wbKg nvB‡Wªv‡Rwb‡mUv', NULL),
(181, 'Arsenicum iodatum', 'Av‡m©wbK Av‡qvWvg', NULL),
(182, 'Arsenicum metallicum', 'Av‡m©wbKvg †gUvwjKvg', NULL),
(183, 'Arsenicum stibiat', '**', NULL),
(184, 'Arsenicum sulforatum rubrum', 'Av‡mwbK mv i€eªvg', NULL),
(185, 'Arsenicum sulfuratum fla', 'Av‡m©wbK mv †d¬fvg', NULL),
(186, 'Arsynal', '**', NULL),
(187, 'Artanthe', '**', NULL),
(188, 'Artemesia vulgaris', '**', NULL),
(189, 'Artemisia abrotanum', '**', NULL),
(190, 'Artemisia absinthium', 'AvwU©wgwmqv fjMvwim', NULL),
(191, 'Artemisia maritima', NULL, NULL),
(192, 'Arum dracunculus', '**', NULL),
(193, 'Arum italicum', 'Givg BwUwjKv', NULL),
(194, 'Arum maculatum', 'Givg g¨vwKD‡jUvg', NULL),
(195, 'Arum triphyllum', 'Aivg wUªdvBjvg', NULL),
(196, 'Arundo donax', 'Giv‡Ûv †Wvbv·', NULL),
(197, 'Arundo maurtanica', 'Giv‡Ûv †gwi‡UwbKv', NULL),
(198, 'Asafoetida', 'GmvwdwUWv', NULL),
(199, 'Asaparagu', '**', NULL),
(200, 'Asarum can', '**', NULL),
(201, 'Asarum Europ', 'Gmvig BD‡ivwcqvg', NULL),
(202, 'Asclepias cornuti(syriaca)', 'GmwK¬wcqvm Kwb©DUvB', NULL),
(203, 'Asclepias tuberrosa', 'Gm&wK¬wcqvm wUDe‡ivmv', NULL),
(204, 'Asclepias vincetox', '**', NULL),
(205, 'Asimina triloba', '**', NULL),
(206, 'Asparagus  officinalis', 'G¯žv‡iMm Iwc', NULL),
(207, 'Asperula', '**', NULL),
(208, 'Aspidium', '**', NULL),
(209, 'Aspidosperma', '**', NULL),
(210, 'Astacus fluviatilis(Cancer Fluvialis)', 'GóªvKvm d¬ywfqvwUwjm', NULL),
(211, 'Asterias rubens', 'G‡ówiqvm i€‡eb&m', NULL),
(212, 'Astragallus menziesii', '**', NULL),
(213, 'Athamantha', '**', NULL),
(214, 'Atista indica', '**', NULL),
(215, 'Atista radix', '**', NULL),
(216, 'Atoxyl', '**', NULL),
(217, 'Atriplex', '**', NULL),
(218, 'Atropia sulphurica', 'G‡Uªvwcqv mvjwdDwiKvg', NULL),
(219, 'Atropinum', 'G‡Uªvwcbvg', NULL),
(220, 'Aurantium(Citrus vulgaris)', 'mvBUªvm fj‡Mwim', NULL),
(221, 'Aurum arsenicum', 'Aivg Av‡m©wbK', NULL),
(222, 'Aurum bromatum', 'Aivg Av‡qv‡WUvg', NULL),
(223, 'Aurum fulminant', '**', NULL),
(224, 'Aurum iodatum', '**', NULL),
(225, 'Aurum matallicum', 'Aivg †gU', NULL),
(226, 'Aurum muriaticum kalinatum', 'Aivg wgDi', NULL),
(227, 'Aurum muriaticum natronatum', 'Aivg wg †b', NULL),
(228, 'Aurum muriatiocum', 'Aivg mvjwdD‡iUvg', NULL),
(229, 'Aurum sulphuratum', '**', NULL),
(230, 'Avena sativa', '**', NULL),
(231, 'Aviaire', '**', NULL),
(232, 'Azadirachta indica', '**', NULL),
(233, 'Bacillinum', '**', NULL),
(234, 'Bacillinum testium', '**', NULL),
(235, 'Badiaga', 'e¨vwWqvMv', NULL),
(236, 'Baja', '**', NULL),
(237, 'Balsam tolu', '**', NULL),
(238, 'Balsamum peruvianum', 'e¨vjPvg †ci€', NULL),
(239, 'Baptisia confusa', '**', NULL),
(240, 'Baptisia tinctoria', 'e¨vwÞwmqv wUb', NULL),
(241, 'Barosma', '**', NULL),
(242, 'Bartfelder (acid spring)', 'evUwdìvi', NULL),
(243, 'Baryta acetica', 'e¨vivBUv GwmwUKv', NULL),
(244, 'Baryta carbonica', 'e¨vivBUv KveŸ©wbKv', NULL),
(245, 'Baryta iodata', 'e¨vivBUv Av‡qvW', NULL),
(246, 'Baryta muriatica', 'e¨vivBUv wgDwi‡qwUKv', NULL),
(247, 'Basaka', '**', NULL),
(248, 'Belladonna', '†e‡j‡Wvbv', NULL),
(249, 'Bellis perennis', '†ewjm †cwiwbm', NULL),
(250, 'Benzinum', '†ewÄbvg', NULL),
(251, 'Benzinum sulphuricum', NULL, NULL),
(252, 'Benzinum dinitricum', '**', NULL),
(253, 'Benzinum nitricum', '†ewÄbvg bvBwUªKvg', NULL),
(254, 'Benzoic acid', '†e‡ÄvwqK GwmW', NULL),
(255, 'Benzoic oder', '**', NULL),
(256, 'Benzol', '**', NULL),
(257, 'Berberinum', '**', NULL),
(258, 'Berberis aquifolium', '**', NULL),
(259, 'Berderis vulgaris', 'evev©wim fvj', NULL),
(260, 'Beta vulg', '**', NULL),
(261, 'Betainum hydrochlor', '**', NULL),
(262, 'Betonica', NULL, NULL),
(263, 'Bismuthum  oxidum', '**', NULL),
(264, 'Bismuthum metallicum', 'wemg_g', NULL),
(265, 'Bismuthum muriaticum', '**', NULL),
(266, 'Bismuthum nitricum', '**', NULL),
(267, 'Bismuthum subnitricum', '**', NULL),
(268, 'Bismuthum veleriahicum', '**', NULL),
(269, 'Bixa', '**', NULL),
(270, 'Blatta americana', 'e­vUv Av‡gwiKvbv', NULL),
(271, 'Blatta orientalis', 'e­vUv Awi', NULL),
(272, 'Bloldoa', '**', NULL),
(273, 'Blumia odorata', '**', NULL),
(274, 'Boletus  ilricis', '†evwjUvm j¨vwiwmm', NULL),
(275, 'Boletus luridus', '**', NULL),
(276, 'Boletus satanus', '**', NULL),
(277, 'Bolus alba', '**', NULL),
(278, 'Bombyx chrycorhaca', '**', NULL),
(279, 'Bombyx processionea', '**', NULL),
(280, 'boracicum  acidum', '†evi¨vwmKvg GwmWvg', NULL),
(281, 'Boranca ursina', '**', NULL),
(282, 'Borax', '†evi¨v·', NULL),
(283, 'Borhavia diffuas', '**', NULL),
(284, 'Bothrops lanceolatus', 'e_ªá j¨vb&wmI‡jUv', NULL),
(285, 'Botulinum', '**', NULL),
(286, 'Bougmacia', '**', NULL),
(287, 'Bounafa', '**', NULL),
(288, 'Bovista', '†evwfóv', NULL),
(289, 'Brachyglottis repens', 'eª¨vwKM­wUm', NULL),
(290, 'Branca', '**', NULL),
(291, 'Brassica napus', '**', NULL),
(292, 'Bromium', '†eªvwgqg', NULL),
(293, 'Brucea antidysenterica', 'eª€wmqv Gw›UwW‡m‡›UwiKv', NULL),
(294, 'Brucinum', '**', NULL),
(295, 'Brunca', '**', NULL),
(296, 'Bryonia allba', 'eªvBIwbqv Gj¦v', NULL),
(297, 'Buchu', '**', NULL),
(298, 'Bufo rana', NULL, NULL),
(299, 'Bufo sahytiensis', 'weD‡dv m¨vnvBwmGb&wmm&', NULL),
(300, 'Bungarus', NULL, NULL),
(301, 'Butyric acid', NULL, NULL),
(302, 'Buxus', '**', NULL),
(303, 'Cacaodyl soda', '**', NULL),
(304, 'Cacsalpinia', 'K¨vwisKv', NULL),
(305, 'Cactus grandiflorus', 'K¨v±m †MÖwÛ', NULL),
(306, 'Cadmium Bromatum', NULL, NULL),
(307, 'Cadmium iodat', NULL, NULL),
(308, 'Cadmium oxide', NULL, NULL),
(309, 'Cadmium suiphuratum', 'K¨vWwgqg mvjwdD‡iUvg', NULL),
(310, 'Caffein', NULL, NULL),
(311, 'Cahinca', '**', NULL),
(312, 'Cainca', 'KvBb&Kv', NULL),
(313, 'Cajuputum', 'K¨vRycyUg', NULL),
(314, 'Caladium', 'K¨vWwgqv †¯‹', NULL),
(315, 'Calcarea acetica', 'K¨v‡éwiqv GwmwUKv', NULL),
(316, 'Calcarea arsenicum', 'K¨vj&‡Kwiqv Avm©', NULL),
(317, 'Calcarea bromatum', '**', NULL),
(318, 'Calcarea caleinata', NULL, NULL),
(319, 'Calcarea carbonica', 'K¨vj&‡Kwiqv KveŸ©', NULL),
(320, 'Calcarea caustica', 'K¨vj&‡Kwiqv KwóKvg', NULL),
(321, 'Calcarea chlorinata', '**', NULL),
(322, 'Calcarea fluorata', 'K¨vj&‡Kwiqv d¬yI‡iUv', NULL),
(323, 'Calcarea hyphosporosa', '**', NULL),
(324, 'Calcarea iodata', 'K¨vj&‡Kwiqv Av‡qv‡WUv', NULL),
(325, 'Calcarea muriatica', '**', NULL),
(326, 'Calcarea ovi testae(Ovi gallinae tosta)', '**', NULL),
(327, 'Calcarea oxalica', '**', NULL),
(328, 'Calcarea phosphorica', 'K¨vj&‡Kwiqv dùwiKv', NULL),
(329, 'Calcarea picrica', '**', NULL),
(330, 'Calcarea renalis', '**', NULL),
(331, 'Calcarea silcica', 'K¨v‡éwiqvg wmwj‡KU', NULL),
(332, 'Calcarea sulphurica', '**', NULL),
(333, 'Calcarea sulphuricum sti', 'K¨vj&‡Kwiqv mvjwdDwiKv', NULL),
(334, 'Calculus', '**', NULL),
(335, 'Calendula officinalis', 'K¨v‡jÛzjv Iwc', NULL),
(336, 'Calliandra houstoni', '**', NULL),
(337, 'Calotropis', NULL, NULL),
(338, 'Camphora bromata', NULL, NULL),
(339, 'Camphora officinarum', 'K¨v‡ùviv Iwc', NULL),
(340, 'Camphoric acid', '**', NULL),
(341, 'Cancer astacus', '**', NULL),
(342, 'Canchalagua', 'K¨vš’v‡j‡Mv', NULL),
(343, 'Cannabis indica', 'K¨vbvwem BwÛK', NULL),
(344, 'Cannabis satiba', 'K¨vbvwem ‡mUv', NULL),
(345, 'Cantharidon', NULL, NULL),
(346, 'Cantharis', 'K¨vš’vwim', NULL),
(347, 'Capparis', '**', NULL),
(348, 'Capsella', '**', NULL),
(349, 'Capsicum', 'K¨vwáKg', NULL),
(350, 'Carbamide', '**', NULL),
(351, 'Carbo animalis', 'Kv‡eŸ©v Gwb‡gwjm', NULL),
(352, 'Carbo vegetabilis', 'Kv‡eŸ©v †fwR‡Uewjm', NULL),
(353, 'Carbolic acid', 'KveŸ©wjK GwmW', NULL),
(354, 'Carbon hydrogenisatum', 'KveŸ©wbqg nvB‡Wªv‡Rwb‡mUv', NULL),
(355, 'Carbon tetrachol', 'KveŸ©wbqg mvjwdD‡iUvg', NULL),
(356, 'Carboneum', '**', NULL),
(357, 'Carboneum oxygenisatum', 'KveŸ©wbqg Aw´‡Rwb‡mUvg', NULL),
(358, 'Carboneum sulphuratum', '**', NULL),
(359, 'Carcinosin', '**', NULL),
(360, 'Carduus benedictus', '**', NULL),
(361, 'Carduus marianus', 'KvWz©qvm †gwi‡qbvm', NULL),
(362, 'Carissa schim', '**', NULL),
(363, 'Carlsbad', 'Kvj©me¨vW', NULL),
(364, 'Carya alba', '**', NULL),
(365, 'Cascarilla', '**', NULL),
(366, 'Cascars sagrads', NULL, NULL),
(367, 'Cassada', 'K¨v¯‹vwijv', NULL),
(368, 'Cassia acutif', NULL, NULL),
(369, 'Castanea vesca', 'K¨vóvwbqv †f®‹v', NULL),
(370, 'Castor equi', 'K¨vói BKzB', NULL),
(371, 'Castoreum', 'K¨v‡óvwiqg', NULL),
(372, 'Catalpa', '**', NULL),
(373, 'Cataria', '**', NULL),
(374, 'Caulophyllum', 'K‡jvdvBjvg', NULL),
(375, 'Causticum', 'KwóKg', NULL),
(376, 'Ceanothus americanus', 'wm‡q‡iv_vm G‡gwiKvbvm', NULL),
(377, 'Ceanothus thrysif', 'wm‡q‡iv_vm G‡gwiKvbvm', NULL),
(378, 'Cedron', 'wm‡Wªvb', NULL),
(379, 'Cenchris contortrix', 'wmbwµm K‡›Uv', NULL),
(380, 'Centaurea tagana', 'wm‡š’wiqv', NULL),
(381, 'Cep', NULL, NULL),
(382, 'Cephalandra indica', '**', NULL),
(383, 'Cephalanthus', '**', NULL),
(384, 'Cerefolius', '**', NULL),
(385, 'Cereus bonplandii', 'wmwiqvm ebe­¨vÛvB', NULL),
(386, 'Cereus serpentaria', 'wmwiqvm mvi‡cb‡Uwiqvm', NULL),
(387, 'Cerium Oxalicum', '**', NULL),
(388, 'Cervus', '**', NULL),
(389, 'Cetonia', '**', NULL),
(390, 'Cetrararia islandia', '†m‡Uª‡iwiqv AvBj¨vÛ', NULL),
(391, 'Chamomilla', 'K¨v‡gvwgjv', NULL),
(392, 'Champarro oemargoso', '**', NULL),
(393, 'Chaulmeogra', '**', NULL),
(394, 'Cheiranthus', '**', NULL),
(395, 'Cheiranthus cheiri', '**', NULL),
(396, 'Chelidonin', NULL, NULL),
(397, 'Chelidonium majus', '†Pwj‡Wvwbqg †gRvm', NULL),
(398, 'Chelone', NULL, NULL),
(399, 'Chenopod aphis', '†P‡bv‡cvwWqvg M­ywm Avwdm', NULL),
(400, 'Chenopodium anthelminticum', '†P‡bv‡cvwWqg q¨vb‡_jwgw›U', NULL),
(401, 'Chenopodium vulvaria', '‡P‡bv‡cvwWqg fvj‡fwiqv', NULL),
(402, 'Chimaphila maculata', '**', NULL),
(403, 'Chimaphila umbellata', 'wPgvwdjv †gKz‡jUv', NULL),
(404, 'China boliviana', '**', NULL),
(405, 'China officinalis', 'Pvqbv Awd', NULL),
(406, 'Chininum arsenicosum', 'wPwbbvg Av‡m©wb‡Kvmvg', NULL),
(407, 'Chininum brom', 'wPwbbg mjwdDwiKvg', NULL),
(408, 'Chininum muriaticum', 'wPwbbvg †eªvg', NULL),
(409, 'Chininum Salicylicum', NULL, NULL),
(410, 'Chininum sulphuricum(Qui)', '**', NULL),
(411, 'Chiococea', '**', NULL),
(412, 'Chionanthus virginica', 'wPIb¨vš’m fv©wRwbKv', NULL),
(413, 'Chloralum', '†K¬v‡ijvg', NULL),
(414, 'Chloroformum', '†K¬v‡ivdig', NULL),
(415, 'Chlorum', '†K¬vivg', NULL),
(416, 'Cholas terapina', '**', NULL),
(417, 'Cholesterinum', '†Kv‡jw÷ªbvg', NULL),
(418, 'Choline', '**', NULL),
(419, 'Chopcheenea', '**', NULL),
(420, 'Chromicum acidum', 'µwgKg GwmWg', NULL),
(421, 'Chromicum oxydatum', '**', NULL),
(422, 'Chromium sulphuricum', '**', NULL),
(423, 'Chrysophanicum acidum', '**', NULL),
(424, 'Chrysorobinum', '**', NULL),
(425, 'Cicera arit', '**', NULL),
(426, 'Cichorium', NULL, NULL),
(427, 'Cicuta maculata', '**', NULL),
(428, 'Cicuta virosa', 'wmwKDUv fvB‡ivmv', NULL),
(429, 'Cimex', 'wmwgwmwdDMv', NULL),
(430, 'Cimicifuga', 'wmwgwmwdDMv', NULL),
(431, 'Cina', 'wmbv', NULL),
(432, 'Cinararia maritima', '**', NULL),
(433, 'Cinchona bolviana', '**', NULL),
(434, 'Cinchonium sulphuricum', 'wm‡¯‹vwbqg mjwdDwiKg', NULL),
(435, 'Cinnabaris', 'wmbv‡ewim', NULL),
(436, 'Cinnamomum', 'wm‡i‡gvgvg', NULL),
(437, 'Cisstus canadensis', 'wmóvm K¨v‡Wvwbmvm', NULL),
(438, 'Citric acid', 'mvBwUK GwmW', NULL),
(439, 'Citrus decumana', '**', NULL),
(440, 'Citrus limonum', 'mvBUªvm wj‡gvbvm', NULL),
(441, 'Clematis erecta', 'wK¬‡gwUm B‡iKUv', NULL),
(442, 'Clematis vrtalba', '**', NULL),
(443, 'Clorodendron infortunatu', '**', NULL),
(444, 'Clotho arictans', '**', NULL),
(445, 'Cltha palustris', 'K¨vjLv ‡cjvw÷ªqv', NULL),
(446, 'Cobaltum', '†Kve¨vjUg', NULL),
(447, 'Coca', '†KvKv', NULL),
(448, 'Cocanum muriatcum', '†Kvwm‡bjv †mÞvg', NULL),
(449, 'Coccinella septemupunotata', '†KvwWbg', NULL),
(450, 'Cocculus indicus', 'KwKDjvm', NULL),
(451, 'Coccus cacti', 'K°m K¨vKUvB', NULL),
(452, 'Cochlearia armoracia', '**', NULL),
(453, 'Codenum', 'KjwPKvg', NULL),
(454, 'Coffea cruda', 'Kwdq µzo      &', NULL),
(455, 'Coffea tosta', 'Kwdqv †Uvóv', NULL),
(456, 'Coffeinum', NULL, NULL),
(457, 'Colchicin', NULL, NULL),
(458, 'Colchicum', '**', NULL),
(459, 'Collinsonia canadensis', 'Kwjm‡mv‡mqv K¨vbv', NULL),
(460, 'Colocynthinum', '**', NULL),
(461, 'Colocynthis', 'K‡jvwmw&¯’m', NULL),
(462, 'Colostrum', '†Kv‡jvm&Uªvg', NULL),
(463, 'Comocladia dendata', '†Kv‡gv‡K¬wWqv †WbWvUv', NULL),
(464, 'Conbalaria majalis', 'Kbf¨v‡jwiqv †gR¨vwjm', NULL),
(465, 'Conbullus duartinus', '**', NULL),
(466, 'Conchiolinum', '**', NULL),
(467, 'Condurango', '**', NULL),
(468, 'Coniinum bromatum', '**', NULL),
(469, 'Conium maculatum', '†Kv‡Kbvg wgDwiwUKvg', NULL),
(470, 'Convallaria', NULL, NULL),
(471, 'Convulvus arvensis', '**', NULL),
(472, 'Copiva officinalis', '†Kv‡cBfv Awd', NULL),
(473, 'Coqueluchin', '**', NULL),
(474, 'Corallium rubrum', '†Kvi¨vwjqvg iƒeªvg', NULL),
(475, 'Coralorhiza', NULL, NULL),
(476, 'Coriaria ruscifolia', '‡Kvwiqvwiqv iƒwm‡dvwjqv', NULL),
(477, 'Cornus alternifolia', 'KYv©m wmwiwmqv', NULL),
(478, 'Cornus circinata', 'KY©vm mviwmbvUv', NULL),
(479, 'Cornus florida', 'KY©vm †d¬vwiWv', NULL),
(480, 'Corolorhiza', '**', NULL),
(481, 'Corydalis', '**', NULL),
(482, 'Cota bark', '**', NULL),
(483, 'Cotyledon', '†KvUvB‡jÛb Avg‡ewjKvm', NULL),
(484, 'Coumarin', '**', NULL),
(485, 'Covolvulusduartinus', '**', NULL),
(486, 'Crataegus oxyacantha', '**', NULL),
(487, 'Crocus sativus', '†µvKvm †mU', NULL),
(488, 'Crotalus cascavella', '†µv‡Ujm K¨vm&Kvwfjv', NULL),
(489, 'Crotalus horridus', '†µv‡Ujvm nwiWvm', NULL),
(490, 'Croton chloral', '**', NULL),
(491, 'Croton tiglium', '†µvUm wUwM­qvg', NULL),
(492, 'Cryptopinum', '**', NULL),
(493, 'Cubeba officinalis', 'wKD‡eev Awd', NULL),
(494, 'Cucarbita citrellus', '**', NULL),
(495, 'Cucarbita pepo', '**', NULL),
(496, 'Culex moscae', 'wKD‡j´ gm&wm', NULL),
(497, 'Cundurango', 'KwÛDi¨v‡½v', NULL),
(498, 'Cuphea viscossima', '**', NULL),
(499, 'Cupressus austral', '**', NULL),
(500, 'Cupressus lawson', '**', NULL),
(501, 'Cuprum  arsenicosum', 'KzcÖvg Av‡m©wb‡Kvbvgq', NULL),
(502, 'Cuprum  nitricum', '**', NULL),
(503, 'Cuprum aceticum', 'KzcÖvg GwmwUKvg', NULL),
(504, 'Cuprum ammonia sulph', '**', NULL),
(505, 'Cuprum cyanatum', '**', NULL),
(506, 'Cuprum metallicum', '**', NULL),
(507, 'Cuprum sulphuricum', 'KzcÖvg mvjwdDwiKvm', NULL),
(508, 'Curare', 'wKDivi', NULL),
(509, 'Cuscus', '**', NULL),
(510, 'Cusparia', '**', NULL),
(511, 'Cyclamen  europaeum', 'mvBK¬v‡gb G‡iv', NULL),
(512, 'Cydonia', '**', NULL),
(513, 'Cymarin', '**', NULL),
(514, 'Cynanchum', '**', NULL),
(515, 'Cypripedium pubescens', 'mvBwcÖwcwWqg cve', NULL),
(516, 'Cysticin', '**', NULL),
(517, 'Cystisus laburnum', '**', NULL),
(518, 'Cystisus scopar', '**', NULL),
(519, 'Dapdne indica', 'W¨vcwW BwÛKv', NULL),
(520, 'Datura arborea', '**', NULL),
(521, 'Datura ferox', '**', NULL),
(522, 'Datura metel', '**', NULL),
(523, 'Delphinus', '**', NULL),
(524, 'Dematium petroeum', '†Wwim wcbœvUv', NULL),
(525, 'Derris pinnata', '**', NULL),
(526, 'Desmodium gangeticum', '**', NULL),
(527, 'Dicentra', NULL, NULL),
(528, 'Dictamnus', '**', NULL),
(529, 'Digitalis purputea', 'wWwR‡Uwjm cvi', NULL),
(530, 'Digitoxinum', '**', NULL),
(531, 'Dioscorea villosa', 'Wvq‡¯‹vwiqv wf‡jv', NULL),
(532, 'Diosma', '**', NULL),
(533, 'Diphtherinum', '**', NULL),
(534, 'Diphtherotoxin', '**', NULL),
(535, 'Dipodium', '**', NULL),
(536, 'Diptrix', '**', NULL),
(537, 'Dirca palusris', '**', NULL),
(538, 'Ditain', '**', NULL),
(539, 'Dolichos pruriens', '†WvwjKvm cÖ€yiGÝ', NULL),
(540, 'Doorba', '**', NULL),
(541, 'Dorema', '**', NULL),
(542, 'Doryphora', '†Wvwi‡dviv', NULL),
(543, 'Drosera rotundifolis', 'Wª‡miv †ivUz', NULL),
(544, 'Duboisia sulph', '**', NULL),
(545, 'Duboisinum', 'wW‡evqwmbvg', NULL),
(546, 'Dulcamara', 'Wvj&Kvgviv', NULL),
(547, 'Echinacea angustifolia', 'BwP‡bwmqv Av‡Mwó‡dvwj', NULL),
(548, 'Echinacea purpurea', '**', NULL),
(549, 'Egg vaccine', '**', NULL),
(550, 'Elaeis', NULL, NULL),
(551, 'Elaeis guineensis', 'Bj¨vá', NULL),
(552, 'Elaps corallinus', '**', NULL),
(553, 'Elaterium', 'Bj¨vwUwiqvg', NULL),
(554, 'Electricitas', '**', NULL),
(555, 'Electron', '**', NULL),
(556, 'Elemuy', '**', NULL),
(557, 'Emetine', '**', NULL),
(558, 'Enlexing', '**', NULL),
(559, 'Eosin', '**', NULL),
(560, 'Ephedra vulgaris', '**', NULL),
(561, 'Epigea repens', 'GwcwRhv wi‡cÝ', NULL),
(562, 'Epilobium palustre', '**', NULL),
(563, 'Epiphegus', '**', NULL),
(564, 'Equisetum', 'BKzB‡RUvg', NULL),
(565, 'Eranthis hyemale', 'BwiPw_wUm wnivwm‡dvwjqv', NULL),
(566, 'Erechthites hieracifolia', '**', NULL),
(567, 'Ergot', NULL, NULL),
(568, 'Ergotin', '**', NULL),
(569, 'Erigeron canadense', '**', NULL),
(570, 'Eriodictyon glutinosum', '**', NULL),
(571, 'Erodium', '**', NULL),
(572, 'Eryngium aquaticum', 'Bwiwbqvg GKzwU‡qKvg', NULL),
(573, 'Eryngium maritinum', '**', NULL),
(574, 'Erythrac chiron', 'BwiwR‡ivb', NULL),
(575, 'Erythrinus', NULL, NULL),
(576, 'Eschscholtzia', '**', NULL),
(577, 'Escoba amargo', '**', NULL),
(578, 'Eserinum', '**', NULL),
(579, 'Ether', 'B_vi', NULL),
(580, 'Ethylum nitricum', '**', NULL),
(581, 'Eucalyptol', '**', NULL),
(582, 'Eucalyptol rostr.', '**', NULL),
(583, 'Eucalyptus globulus', '**', NULL),
(584, 'Eucalyptus tereticoris', 'BDK¨vwjÞvm', NULL),
(585, 'Eugenia chekum', '**', NULL),
(586, 'Eugenia jambos', 'BDwRwbqv R¨v‡¤^vm', NULL),
(587, 'Euonymin', '**', NULL),
(588, 'Euonymus astropur purea', '**', NULL),
(589, 'Euonymus europaeus', 'BIbxgm BD‡ivwcqvm', NULL),
(590, 'Eupatorium aromat', '**', NULL),
(591, 'Eupatorium perfoliatum', 'BD‡c‡Uvwiqvg cv‡dv©wj‡qUv', NULL),
(592, 'Eupatorium purpur', 'BD‡c‡UBiqv cvwcDwiqvg', NULL),
(593, 'Euphorbia amygdal', '**', NULL),
(594, 'Euphorbia corollata', '**', NULL),
(595, 'Euphorbia cyparissias', '**', NULL),
(596, 'Euphorbia heterodoxa', '**', NULL),
(597, 'Euphorbia hypericifolia', '**', NULL),
(598, 'Euphorbia ipecacuanha', '**', NULL),
(599, 'Euphorbia piluliferaEu.', '**', NULL),
(600, 'Euphorbia resinifera', '**', NULL),
(601, 'Euphorbium', 'BDdiweqg', NULL),
(602, 'Euphorbium lathyris', '**', NULL),
(603, 'Euphorbium marg', '**', NULL),
(604, 'Euphorbium peplus', '**', NULL),
(605, 'Euphorbium pilulifera', '**', NULL),
(606, 'Euphrasia officinalis', 'BD‡d«wmqv Iwc', NULL),
(607, 'Eupionum', 'BDwcIb', NULL),
(608, 'Fabiana', '**', NULL),
(609, 'Fagopyrum', 'd¨v‡MvcvBivm', NULL),
(610, 'Fagus syivatica', NULL, NULL),
(611, 'Fel tauri', '**', NULL),
(612, 'Ferrum Aeeticum', '**', NULL),
(613, 'Ferrum arsenicicum', '†divg Av‡m©wbKvg', NULL),
(614, 'Ferrum Bromatum', '**', NULL),
(615, 'Ferrum carbonicum', '**', NULL),
(616, 'Ferrum citric', '**', NULL),
(617, 'Ferrum cyanatum', '**', NULL),
(618, 'Ferrum lacticum', '**', NULL),
(619, 'Ferrum magneticum', '†divg g¨vM‡bwUKvg', NULL),
(620, 'Ferrum pernitricum', '†divg dm&dwiKvg', NULL),
(621, 'Ferrum phosphoricum', '**', NULL),
(622, 'Ferrum phosphoricum hydricum', NULL, NULL),
(623, 'Ferrum picricum', '†divg wcKw& µK', NULL),
(624, 'Ferrum poryphos', '**', NULL),
(625, 'Ferrum protoxal', '**', NULL),
(626, 'Ferrum sulphuricum', '†divg mjwdDwiKvg', NULL),
(627, 'Ferrum tertaricum', '**', NULL),
(628, 'Ferula glauca', '**', NULL),
(629, 'Ferula sumbul', '**', NULL),
(630, 'Ferum iodatum', '†divg Av‡qvW', NULL),
(631, 'Ferum metallicum', '†divg †gU', NULL),
(632, 'Ferum muriaticum', '†divg wgDwiGwUKvg', NULL),
(633, 'Ficus  religiosa', '**', NULL),
(634, 'Ficus indica', '**', NULL),
(635, 'Ficus venosa', '**', NULL),
(636, 'Filix mas', 'wdwj· gvm', NULL),
(637, 'Floroform', '**', NULL),
(638, 'Fluoricum acidum', 'd¬yIwiKg GwmW', NULL),
(639, 'Formalin', '**', NULL),
(640, 'Formica rufa', 'dw¤§©Kv', NULL),
(641, 'Formic acid', '**', NULL),
(642, 'Fragaria vesca', '**', NULL),
(643, 'Franciscea   uniflora', '**', NULL),
(644, 'Frangula', 'd«b&‡Mwiqv †fmKv', NULL),
(645, 'Franzensbad', NULL, NULL),
(646, 'Fraxinus  americana', '**', NULL),
(647, 'Fucus  vesiculosus', '**', NULL),
(648, 'Fugus', '**', NULL),
(649, 'Fuligo ilgni', '**', NULL),
(650, 'Fushina', '**', NULL),
(651, 'Gadus morrhus', '**', NULL),
(652, 'Gaertner', '**', NULL),
(653, 'Galanlhusniv', '**', NULL),
(654, 'Galega', '**', NULL),
(655, 'Galega officinalis', '**', NULL),
(656, 'Galipea', NULL, NULL),
(657, 'Galium aparine', '**', NULL),
(658, 'Gallicum acidum', 'M¨vwjKvg GwmW', NULL),
(659, 'Galvanismus', '**', NULL),
(660, 'Gambogia', '**', NULL),
(661, 'Garcina morella', '**', NULL),
(662, 'Gastein', '**', NULL),
(663, 'Gaultheria', '**', NULL),
(664, 'Gelsemium sempervirens', '†Rjwmwgqg', NULL),
(665, 'Genista tinctoria', '†Rwbóv', NULL),
(666, 'Gentiana cruciata', '†Rb&wmAvbv jywmqv', NULL),
(667, 'Gentiana lutea', '†Rb&wmAvbv jywmqv', NULL),
(668, 'Gentiana quinqueflora', '†Rb&wmAvbv µzwmqvUv', NULL),
(669, 'Geranin', '**', NULL),
(670, 'Geranium maculatum', '**', NULL),
(671, 'Gettisburg water', '†MwUm&ev©M', NULL),
(672, 'Gettysburg', '**', NULL),
(673, 'Geum rival', '**', NULL),
(674, 'Ginseng', 'wRb&‡m½', NULL),
(675, 'Glanderine', 'M­¨vÛvwib', NULL),
(676, 'Gle chomahed', '**', NULL),
(677, 'Glonoin', 'y‡M­vwbqb', NULL),
(678, 'Glycerinum', '**', NULL),
(679, 'Gnaphalium', 'b¨vdvwjqvg', NULL),
(680, 'Golondrina', '**', NULL),
(681, 'Gossypium herbaceum', 'Mwmwcqg', NULL),
(682, 'Granatum punica', 'MÖ¨v‡bUvg', NULL),
(683, 'Graphites', 'MÖ¨vdvBwUm', NULL),
(684, 'Gratiola officinalis', 'MÖ¨vwUIjv', NULL),
(685, 'Grindelia robusta', 'wMÖ‡Ûwjqv', NULL),
(686, 'Guaca', '¸qBKvg', NULL),
(687, 'Guaco', '†Mvqv‡Kv', NULL),
(688, 'Guaiacum', '**', NULL),
(689, 'Guano', '**', NULL),
(690, 'Guao', NULL, NULL),
(691, 'Guarana', '¸qvivbv', NULL),
(692, 'Guarea', '**', NULL),
(693, 'Guipsine', '**', NULL),
(694, 'Gummigutti', '**', NULL),
(695, 'Gunpowder', '**', NULL),
(696, 'Gymnema sylvestre', '**', NULL),
(697, 'Gymnocladus canadensis', '‡Rg&‡bv‡K¬Wvm', NULL),
(698, 'Haematoxylon', '**', NULL),
(699, 'Hagenia abys', NULL, NULL),
(700, 'Hall', '**', NULL),
(701, 'Hamamelis virginica', 'n¨vgv‡gwjm', NULL),
(702, 'Heamatoxylan', 'wn‡gUw´‡jvb', NULL),
(703, 'Hecla lava', '†nK&jv jvfv', NULL),
(704, 'Hedeoma', '†nwW‡qvgv cy‡jwR‡qWvm', NULL),
(705, 'Hedeoma pulegioides', '**', NULL),
(706, 'Hedera helix', NULL, NULL),
(707, 'Hedysarum', NULL, NULL),
(708, 'Helianthus', '**', NULL),
(709, 'Heliotropium', '**', NULL),
(710, 'Helix tosta', '**', NULL),
(711, 'Hellebborus niger', '†nwj‡evivm bvBRvi', NULL),
(712, 'Helleborns orientalis', '**', NULL),
(713, 'Helleborus foetidus', '**', NULL),
(714, 'Helledonus viridis', '**', NULL),
(715, 'Heloderma', 'wn‡jvWvigv †nvwiWvm', NULL),
(716, 'Helonias dioica', 'wn‡jvwbqvm', NULL),
(717, 'Hemintochortos', '**', NULL),
(718, 'Henchera', NULL, NULL),
(719, 'Hepatica', '**', NULL),
(720, 'Heper sulphuris calcareum', 'wncvi mvjd', NULL),
(721, 'Heraclcum', '**', NULL),
(722, 'Hippomanes', 'wn‡cv‡gwbm', NULL),
(723, 'Hippozaenium', 'wn‡cvwRwbb&', NULL),
(724, 'Hippuric acid', '**', NULL),
(725, 'Hoang nan', '**', NULL),
(726, 'Hoitza', '**', NULL),
(727, 'Homaria', '**', NULL),
(728, 'Homarus', '†nvgvivm', NULL),
(729, 'Humea elegeans', NULL, NULL),
(730, 'Humulus lupulus', '**', NULL),
(731, 'Hura braziliensis', 'nviv †eªwRwjGbwmm&', NULL),
(732, 'Hura crepitans', NULL, NULL),
(733, 'Hydrangea', 'nvBWª¨vwÄqv', NULL),
(734, 'Hydrangea arborescens', '**', NULL),
(735, 'Hydrargyrum', '**', NULL),
(736, 'Hydrast sulph', '**', NULL),
(737, 'Hydrastininum muriaticum acid', '**', NULL),
(738, 'Hydrastinum mur', '**', NULL),
(739, 'Hydrastis canadensis', 'nvBWªvm&wUm K¨vb', NULL),
(740, 'Hydrobromic acid', '**', NULL),
(741, 'Hydrocotyle asiatica', 'nvB‡WWªv‡KvUvBj', NULL),
(742, 'Hydrofluoricum', '**', NULL),
(743, 'Hydrophobinum(Lyssinum)', 'jvBwmb', NULL),
(744, 'Hydrophylum  virginianum', '**', NULL),
(745, 'Hydropiper', '**', NULL),
(746, 'Hyocin hydrobrom', '**', NULL),
(747, 'Hyoscyaminum', 'nvBIqvGgvm', NULL),
(748, 'Hyoseyamus', NULL, NULL),
(749, 'Hyoxyaminum sulphuricum', '**', NULL),
(750, 'Hypericum perforatum', 'nvBwcwiKvg', NULL),
(751, 'Iberis amara', 'AvB‡ewim', NULL),
(752, 'Ichthyotoxin', '**', NULL),
(753, 'Ictodes foetida', 'BK&‡UvWvm †dwUWvm', NULL),
(754, 'Ignatia amara', 'B‡Mœwmqv', NULL),
(755, 'Ikshugandha', '**', NULL),
(756, 'Ilex aquif', '**', NULL),
(757, 'Ilex cassine', '**', NULL),
(758, 'Illicium', 'Bwj­Kvg', NULL),
(759, 'Illicium anisatum', NULL, NULL),
(760, 'Imperatoria', '**', NULL),
(761, 'Indigo', 'BwÛ‡Mv', NULL),
(762, 'Indium metallicum', 'BwÛqvg †gUv', NULL),
(763, 'Indol', NULL, NULL),
(764, 'Ingluvin', '**', NULL),
(765, 'Insulin', NULL, NULL),
(766, 'Inula helenium', 'BwbDjv', NULL),
(767, 'Iodium', 'AvBIWvg', NULL),
(768, 'Iodoformum', '**', NULL),
(769, 'Iodothyrine', '**', NULL),
(770, 'Ioduretted potass iod', '**', NULL),
(771, 'Ipecacuanha', 'BwcKvKzqvbv', NULL),
(772, 'Ipomea purpurea', 'AvB‡cvwgqv cviwcDwiqv', NULL),
(773, 'Iridium', 'BwiwWqvg', NULL),
(774, 'Iridium chlor', '**', NULL),
(775, 'Iris florentina', 'AvBwim wdwUwWwmgv', NULL),
(776, 'Iris foetidissima', 'AvBwim †d¬v‡i›Ubv', NULL),
(777, 'Iris Gemanica', 'AvBwim †R‡gwbKv', NULL),
(778, 'Iris minor', '**', NULL),
(779, 'Iris tenax', '**', NULL),
(780, 'Iris versicolor', 'AvBwim fvwm‡Kvjvi', NULL),
(781, 'Isotonic plasma', '**', NULL),
(782, 'Itu', '**', NULL),
(783, 'Jaborandi', 'R¨v‡evi¨vwÛ', NULL),
(784, 'Jacaranda  gualandai', 'R¨v‡Kv‡iwÛqv †K‡ivev', NULL),
(785, 'Jacarandia caroba', 'R¨v‡KvivwÛqv', NULL),
(786, 'Jacea', '**', NULL),
(787, 'Jalapa', 'R¨vjvcv', NULL),
(788, 'Jambosa', '**', NULL),
(789, 'Jasminum', '**', NULL),
(790, 'Jatropha curcas', 'R¨v‡Uªvdv KviKvm', NULL),
(791, 'Jatropha urens', '**', NULL),
(792, 'Jequiritol', '**', NULL),
(793, 'Jequirity', '**', NULL),
(794, 'Jonosia', '**', NULL),
(795, 'Juglans cinerea', 'RyM­vÝ wm‡bvwiqv', NULL),
(796, 'Juglans regia', 'RyM­vÝ wiwRqv', NULL),
(797, 'Juglendin', '**', NULL),
(798, 'Jumcus effusus', 'RvgKvm BwdDKvm', NULL),
(799, 'Juniperus communis', '**', NULL),
(800, 'Juniperus virginianus', '†Rwbcvivm fvwR©wbbv', NULL),
(801, 'Justica', '**', NULL),
(802, 'Justicia adhatoda', '**', NULL),
(803, 'Justicia rubrom', '**', NULL),
(804, 'Kalagua', '**', NULL),
(805, 'Kali aceticum', '†Kwj GwmwUKvg', NULL),
(806, 'Kali arsenicosum', '†Kwj Av‡m©', NULL),
(807, 'Kali bichromicum', '†Kwj evB‡µvwgKg', NULL),
(808, 'Kali bromatum', '†Kwj †eªv‡gUvg', NULL),
(809, 'Kali carbonicum', '†Kwj Kv‡eŸ©vwbKvg', NULL),
(810, 'Kali causticum', '**', NULL),
(811, 'Kali chloricum', '†Kwj †K¬vwiKg', NULL),
(812, 'Kali chlorosum', '**', NULL),
(813, 'kali citricum', '**', NULL),
(814, 'Kali cyanatum', '†Kwj mv‡q‡bUvg', NULL),
(815, 'Kali ferrocyanitum', '†Kwj †d‡iv mv‡qvbvBU', NULL),
(816, 'Kali hydriodicum', '**', NULL),
(817, 'Kali hypophosphite', '**', NULL),
(818, 'Kali iodatum', '†Kwj AvBI‡WUg', NULL),
(819, 'Kali maganicum', '†Kwj g¨v‡½wbg', NULL),
(820, 'Kali muriaticum', '†Kwj wgD†qwiwUKvg', NULL),
(821, 'Kali nitricum', '†Kwj bvBwUªKg', NULL),
(822, 'Kali oxalicum', '†Kwj Aw·wjKvg', NULL),
(823, 'Kali permanganum', NULL, NULL),
(824, 'Kali phosphoricum', '†Kwj dùwiKvg', NULL),
(825, 'Kali picricum', '**', NULL),
(826, 'Kali picro nitricum', '**', NULL),
(827, 'Kali salicylicum', '**', NULL),
(828, 'Kali silicum', '**', NULL),
(829, 'Kali sulph chrom', '**', NULL),
(830, 'Kali sulphuratum', '**', NULL),
(831, 'Kali sulphuricum', '†Kwj mvjwdDwiKvg', NULL),
(832, 'Kali tartaricum', '**', NULL),
(833, 'Kali telluricum', '**', NULL),
(834, 'Kalmegh', '**', NULL),
(835, 'Kalmia latifolia', 'K¨vj&wgqv', NULL),
(836, 'Kaolinum', 'KvIwjb', NULL),
(837, 'Karaka', NULL, NULL),
(838, 'Kava kava', '**', NULL),
(839, 'Keroselenum', '**', NULL),
(840, 'Kissingen', 'wK‡mÄb', NULL),
(841, 'Koch''s lymph', NULL, NULL),
(842, 'Kola', NULL, NULL),
(843, 'Kousso', NULL, NULL),
(844, 'Krameria', '**', NULL),
(845, 'Kreosotum', 'wµ‡qv‡RvU', NULL),
(846, 'Laburnum', '**', NULL),
(847, 'Lac canium', 'j¨vK& K¨vbvBbg', NULL),
(848, 'Lac defloratum', 'j¨vK& wW‡d¬v‡iUvg', NULL),
(849, 'Lac felinum', 'j¨vK &‡dwjbvg', NULL),
(850, 'Lac vacc coagulatum', '**', NULL),
(851, 'Lac vacc floc', '**', NULL),
(852, 'Lac vaccinum', '**', NULL),
(853, 'Lacerta', '**', NULL),
(854, 'Lachesis lanceolat', '**', NULL),
(855, 'Lachessis', 'j¨v‡Kwmm', NULL),
(856, 'Lachnathes tinctoria', 'j¨vK&‡bb&w_m', NULL),
(857, 'Lactic acid', 'j¨vK&wcK GwmW', NULL),
(858, 'Lactuca virosa', 'j¨vK‡UvKv wf‡ivmv', NULL),
(859, 'Laffa acutang', 'j¨vcv Av‡iKwUqvg', NULL),
(860, 'Lamium album', 'j¨vwgqg', NULL),
(861, 'Lapathum', '**', NULL),
(862, 'Lapis albus(Calcarea silica flourica)', 'j¨vwcm Gj¦vg', NULL),
(863, 'Lapis renalis', NULL, NULL),
(864, 'Lappa major', '**', NULL),
(865, 'Lapsana communis', NULL, NULL),
(866, 'Lathyrus sativus', 'j¨vw_ig', NULL),
(867, 'Latrodectus hssetti', 'j¨vK&‡Uv‡WK&Uvm g¨vK‡Ubvm', NULL),
(868, 'Latrodectus katipo', '**', NULL),
(869, 'Latrodectus mactans', '**', NULL),
(870, 'Laurocerasus', 'j‡ivwm‡imvm', NULL),
(871, 'Laurustinus', NULL, NULL),
(872, 'Lava scoriac', '**', NULL),
(873, 'Lctodos', '**', NULL),
(874, 'Lecithin', 'j¨vwmw_b', NULL),
(875, 'Ledum palustre', 'wjWg', NULL),
(876, 'Lemna minor', 'j¨vgbv gvBbi', NULL),
(877, 'Leonurus cordiaca', NULL, NULL),
(878, 'Lepidium bonariense', 'wjwcwWqvg †evbvwiGbvwm', NULL),
(879, 'Leptandra virginca', '†jÞÊªv fvwR©wbKv', NULL),
(880, 'Leptilon', '**', NULL),
(881, 'Levico', '**', NULL),
(882, 'Liatris spicata', '**', NULL),
(883, 'Lignum vitac', '**', NULL),
(884, 'Lilium tigrinum', 'wjwjqg wUwMÖbg', NULL),
(885, 'Limulus', '**', NULL),
(886, 'Linaria', '**', NULL),
(887, 'Linum catharticum', 'wjbvg K¨v_vi', NULL),
(888, 'Linum usitatissimum', '**', NULL),
(889, 'Lippia mexicana', '**', NULL),
(890, 'Lippspringe', '**', NULL),
(891, 'Lithium benzoicum', '**', NULL),
(892, 'Lithium bromatum', '**', NULL),
(893, 'Lithium carbonicum', 'wjw_qg KveŸ©wbKg', NULL),
(894, 'Lithium lacticum', 'wjw_qb wgDwiGwUKg', NULL),
(895, 'Lithium muriaticum', '**', NULL),
(896, 'Lob inflata', '†jvwewjqv Bb&d¬vUv', NULL),
(897, 'Lobelia acetum.', '**', NULL),
(898, 'Lobelia cardinalis', '†jvwewjqv KvwW©‡bwj', NULL),
(899, 'Lobelia dortmanna', '**', NULL),
(900, 'Lobelia erinus', '**', NULL),
(901, 'Lobelia purpurascens', '**', NULL),
(902, 'Lobelia syphilitica', '†jvwewjqv wmwdwjwUK', NULL),
(903, 'Lolium temulentum', '**', NULL),
(904, 'Lonicera', '**', NULL),
(905, 'Lonicera  xylostem', NULL, NULL),
(906, 'Lonicera pericylmenum', '**', NULL),
(907, 'Luffa amera', '**', NULL),
(908, 'Luffa bindal', '**', NULL),
(909, 'Luna', '**', NULL),
(910, 'Lupulin', NULL, NULL),
(911, 'Lupulus', 'wjDcyjm', NULL),
(912, 'Lycopersicum', 'jvB‡KvcvwmKvg', NULL),
(913, 'Lycopodium clavatum', 'jvB‡Kv‡cvwWg', NULL),
(914, 'Lycopus virginicus', 'jvB‡KvWvm fvwnwbKvm', NULL),
(915, 'Lysidinum', '**', NULL),
(916, 'Lysimachia', '**', NULL),
(917, 'Macrotinum', '**', NULL),
(918, 'Macrotys rocemosa', '**', NULL),
(919, 'Macrozamia', '**', NULL),
(920, 'Macuna', '**', NULL),
(921, 'Madura alb', '**', NULL),
(922, 'Magnesia', '**', NULL),
(923, 'Magnesia carbonica', 'g¨vM&wbwmqv KveŸ©wbKv', NULL),
(924, 'Magnesia muriatica', 'g¨vM‡bwbqv wgDwi‡qwUKv', NULL),
(925, 'Magnesia phosphorica', 'g¨vM‡bwmqv dùwiKvg', NULL),
(926, 'Magnesia sulphurica', 'g¨vM&‡bwmqv mvjwdDwiKv', NULL),
(927, 'Magnetis poli. ambo', 'g¨vM‡b‡UR †cvwj Gg‡ev', NULL),
(928, 'Magnetis polus arcticus', 'g¨vM‡bwURg †cvjvm AvwU©Kv', NULL),
(929, 'Magnetis polus australis', '**', NULL),
(930, 'Magnola grandiflora', NULL, NULL),
(931, 'Magnolia glauca', '**', NULL),
(932, 'Magresia oxydata', '**', NULL),
(933, 'Mahonia', '**', NULL),
(934, 'Malandrinum', 'g¨v‡jwÛªbvg', NULL),
(935, 'Malaria officinalis', 'g¨v‡jwiqv Awdwm‡bwjm', NULL),
(936, 'Mallein', NULL, NULL),
(937, 'Manaca(franciseea)', '**', NULL),
(938, 'Managanum aceticum', '**', NULL),
(939, 'Managanum carbonicum', NULL, NULL),
(940, 'Mancinella(Hippomanes)', '**', NULL),
(941, 'Mandragora', '**', NULL),
(942, 'Manganum', 'g¨v‡½bvg', NULL),
(943, 'Manganum colloidal', '**', NULL),
(944, 'Manganum muriaticum', 'g¨v‡½bg wgDwiGwUKg', NULL),
(945, 'Manganum sulphuricum', '**', NULL),
(946, 'Mangifera', '**', NULL),
(947, 'Mangunum oxydatum nativum', '**', NULL),
(948, 'Manzanita', '**', NULL),
(949, 'Mapato', '**', NULL),
(950, 'Marum verum', '**', NULL),
(951, 'Matica', '**', NULL),
(952, 'Mattahiola graeca', NULL, NULL),
(953, 'Medicago', '**', NULL),
(954, 'Medorrhinum', '†g‡Wvwibvg', NULL),
(955, 'Medusa', '**', NULL),
(956, 'Megvet pol.austrul', 'g¨vM‡bwURg‡cvjvmAvm‡Uªwjm', NULL),
(957, 'Melastoma', NULL, NULL),
(958, 'Melcum sale', '**', NULL),
(959, 'Melilotus', '†gwj‡jvUvm', NULL),
(960, 'Melilotus alba', '**', NULL),
(961, 'Melitagrinum', '**', NULL),
(962, 'Mellefolium', 'wgwj‡dvwjqvg', NULL),
(963, 'Menispermum', '**', NULL),
(964, 'Mentha piperita', '**', NULL),
(965, 'Mentha pulegium', '†gš’v wc‡cwiUv', NULL),
(966, 'Mentha virid', NULL, NULL),
(967, 'Menthol', '**', NULL),
(968, 'Menyanthes', 'wgwbGw¯’m', NULL),
(969, 'Mephitis', 'wgdvBwUm', NULL),
(970, 'Mercurialis', '**', NULL),
(971, 'Mercurialis perennis', '**', NULL),
(972, 'Mercurirs sulphocynotus', NULL, NULL),
(973, 'Mercurirs sulphuricus', '**', NULL),
(974, 'Mercurius aceticus', 'gv©Kzwiqvm GwmwUKvm', NULL),
(975, 'Mercurius auratus', '**', NULL),
(976, 'Mercurius biniodatus', '**', NULL),
(977, 'Mercurius bromatum', '**', NULL),
(978, 'Mercurius corrosivus', 'gvKz©wiqvm Ki', NULL),
(979, 'Mercurius cyanatus', 'gv©Kzwiqvm mv‡qv‡bUvm', NULL),
(980, 'Mercurius dulcis', 'gvKz©wiqvm-Wvj&wmm', NULL),
(981, 'Mercurius et.kali iodatum', '**', NULL),
(982, 'Mercurius hannemanni Sol', 'gv©Kzwiqvm mj', NULL),
(983, 'Mercurius iodatus flavus', 'gvKzwi©qvm Av‡qv †d¬fvg', NULL),
(984, 'Mercurius iodatus ruber', 'gvKzw©iqvm Av‡qv i€eªvg', NULL),
(985, 'Mercurius nitricus', 'gvKz©wiqvm bvB‡Uªvmvm', NULL),
(986, 'Mercurius Oxydulatus niger', NULL, NULL),
(987, 'Mercurius phosphor', '**', NULL),
(988, 'Mercurius praecip ruber', 'gv©Kzwiqvm cÖvwm i€evi', NULL),
(989, 'Mercurius precitatus albus', '**', NULL),
(990, 'Mercurius proto.iodatus', '**', NULL),
(991, 'Mercurius sub.corros', '**', NULL),
(992, 'Mercurius sulph .rub', '**', NULL),
(993, 'Mercurius tannicus', NULL, NULL),
(994, 'Mercurius Sol (Merc han Sul)', 'gvKzwiqv©m fvBfvm', NULL),
(995, 'Meriatic acid', 'wgDwiwUKvg GwWm', NULL),
(996, 'Methylene blue', '**', NULL),
(997, 'Methylium salicyl', '**', NULL),
(998, 'Mezereum', '‡g‡Rwiqvg', NULL),
(999, 'Micania guacho', '**', NULL),
(1000, 'Micromeria', NULL, NULL);

INSERT INTO medicines_mdb (m_id, m_txt, m_btxt, m_du) VALUES
(1001, 'Mikania', '**', NULL),
(1002, 'Millefolium', '**', NULL),
(1003, 'Mimosa', '**', NULL),
(1004, 'Mirbane', '**', NULL),
(1005, 'Mitchella repens', 'wg‡Pjv †I‡cbm', NULL),
(1006, 'Momordica bules', '**', NULL),
(1007, 'Momordica charant', '**', NULL),
(1008, 'Monsonia', '**', NULL),
(1009, 'Morphimum', 'g©wdqvg', NULL),
(1010, 'Morphium aceticum', '**', NULL),
(1011, 'Morphium muriaticum', '**', NULL),
(1012, 'Morphium sulphuricum', '**', NULL),
(1013, 'Moschus', 'g¯‹vm', NULL),
(1014, 'Muco toxin', '**', NULL),
(1015, 'Mucuna urens', '**', NULL),
(1016, 'Mulein oil', '**', NULL),
(1017, 'Murex', 'wgD‡i·', NULL),
(1018, 'Muriaticum acidum', '**', NULL),
(1019, 'Musa', NULL, NULL),
(1020, 'Muscrin', NULL, NULL),
(1021, 'Mygale lasiodora', 'gvB‡Mj j¨vwmI‡Wviv', NULL),
(1022, 'Myosotis', 'gvB‡mvwUm', NULL),
(1023, 'Myrica cerifera', 'AvBwim †R‡gwbKv', NULL),
(1024, 'Myristica sebifera', 'wgwimwUKv †mwe', NULL),
(1025, 'Myrmexine', '**', NULL),
(1026, 'Myroxylon pereirac', '**', NULL),
(1027, 'Myrtus chekan', '**', NULL),
(1028, 'Myrtus communis', '**', NULL),
(1029, 'Nabalus', '**', NULL),
(1030, 'Naja tripudians', 'b¨vRv', NULL),
(1031, 'Naphthalinum', 'b¨vc‡_wjqv', NULL),
(1032, 'Narceinum', '**', NULL),
(1033, 'Narcissus', 'bvi‡KvwUb', NULL),
(1034, 'Narcotinum', '**', NULL),
(1035, 'Nareun succinate', '**', NULL),
(1036, 'Nasturtium', '**', NULL),
(1037, 'Natrum aceticum', '**', NULL),
(1038, 'Natrum arsenicatum', '†bUªvg Av‡m©', NULL),
(1039, 'Natrum bromatum', '**', NULL),
(1040, 'Natrum carbonicum', '†bUªvg KveŸ©', NULL),
(1041, 'Natrum causticum', '**', NULL),
(1042, 'Natrum choleinicum', '**', NULL),
(1043, 'Natrum hypochlorosum', '**', NULL),
(1044, 'Natrum hyposulph', '‡bUªvg nvB‡cv‡K¬v‡iv‡mvg', NULL),
(1045, 'Natrum iodatum', '**', NULL),
(1046, 'Natrum lacticum', '**', NULL),
(1047, 'Natrum mur. bit.', '**', NULL),
(1048, 'Natrum muriaticum', '†bUªvg wgDi', NULL),
(1049, 'Natrum nitricum', '‡bUªvg bvBwUªKvg', NULL),
(1050, 'Natrum nitrosum', NULL, NULL),
(1051, 'Natrum phosphoricum', '†bUªvg dùwiKvg', NULL),
(1052, 'Natrum salicylicum', '**', NULL),
(1053, 'Natrum selenicum', '**', NULL),
(1054, 'Natrum silicofluoricum', '**', NULL),
(1055, 'Natrum silicum', '**', NULL),
(1056, 'Natrum sulphuricum', '†bUªvg mvjwdDwiKvg', NULL),
(1057, 'Natrum sulphurosum', '**', NULL),
(1058, 'Natrum telluricum', '**', NULL),
(1059, 'Nectrianinum', '**', NULL),
(1060, 'Negundium', '**', NULL),
(1061, 'Nepeta', '**', NULL),
(1062, 'Nerium odorum', '**', NULL),
(1063, 'Neurin', '**', NULL),
(1064, 'Niccolum', 'wb‡Kvjvg', NULL),
(1065, 'Niccolum carbonicum', '**', NULL),
(1066, 'Niccolum sulph', 'wb‡Kvjvg mvjd', NULL),
(1067, 'Nicotinum', 'bvi‡KvwUb', NULL),
(1068, 'Nitri spiritus dulcis', 'bvB‡Uªv w¯žwiUvm', NULL),
(1069, 'Nitricum acidum', 'bvBwUªKvg GwmW', NULL),
(1070, 'nitro muriatic acid', '‡bUªv wgDwiK GwmW', NULL),
(1071, 'Nitrogenum oxygenatum', '**', NULL),
(1072, 'Nitrum', 'b¨v‡Uªv‡Rbvg Aw·‡R‡bUvg', NULL),
(1073, 'Nuphar luteum', 'wbDdvi wjDwmqvg', NULL),
(1074, 'Nux juglans', '**', NULL),
(1075, 'Nux moschata', 'bv· g¯‹vUv', NULL),
(1076, 'Nux vomica', 'b· fwgKv', NULL),
(1077, 'Nyctanthes', NULL, NULL),
(1078, 'Nymphaea odorata', 'bvB‡dqv A‡W‡iUv', NULL),
(1079, 'Ocimum canum', 'Iwmgvg K¨vb', NULL),
(1080, 'Ocimum cariophylatum', '**', NULL),
(1081, 'Ocimum gratissimum', '**', NULL),
(1082, 'Ocimum sanctum', '**', NULL),
(1083, 'Oenanthe crocata', 'Bbvw¯’', NULL),
(1084, 'Oenothera', '**', NULL),
(1085, 'Oestrum camcle', '**', NULL),
(1086, 'Oleander', 'Iwj‡qÛvi', NULL),
(1087, 'Oleum animale', 'Iwjqg Gwb‡j', NULL),
(1088, 'Oleum cajuput', '**', NULL),
(1089, 'Oleum caryophyllum', '**', NULL),
(1090, 'Oleum jecoris aselli', 'Iwjqvg wR‡Kvwim GmjvB', NULL),
(1091, 'Oleum myristicoc', '**', NULL),
(1092, 'Oleum santali', '**', NULL),
(1093, 'Oleum succinum', '**', NULL),
(1094, 'Oleum wittne bianum', '**', NULL),
(1095, 'Oniscus', NULL, NULL),
(1096, 'Ononis', '**', NULL),
(1097, 'Ononis spinosa', '**', NULL),
(1098, 'Onosmodium', 'I‡bvm‡gvwWqvg', NULL),
(1099, 'Onsscus asellus', '**', NULL),
(1100, 'Operculina', '**', NULL),
(1101, 'Operinum', '**', NULL),
(1102, 'Ophorinum', '**', NULL),
(1103, 'Opiict ipecac', '**', NULL),
(1104, 'Opium', 'Iwcqg', NULL),
(1105, 'Opuntia', '**', NULL),
(1106, 'Orchitinum(Sperminum)', '**', NULL),
(1107, 'Oreodaphne', '**', NULL),
(1108, 'Orexinetann', '**', NULL),
(1109, 'Origanum majorana', 'AwiMvbvg †gRivbv', NULL),
(1110, 'Ornithogalum umbellayum', '**', NULL),
(1111, 'Orobanche', NULL, NULL),
(1112, 'Oronche', '**', NULL),
(1113, 'Orpiment', '**', NULL),
(1114, 'Osmium', 'Am&wgqvg', NULL),
(1115, 'Ostrya', '**', NULL),
(1116, 'Ouabain', 'Iwewbb', NULL),
(1117, 'Ovi gall. pellicula', '**', NULL),
(1118, 'Oxalicum acidum', 'AK‡RwjKvg GwmW', NULL),
(1119, 'Oxalis', '**', NULL),
(1120, 'Oxydendron', '**', NULL),
(1121, 'Oxygenium', 'I‡Rvb', NULL),
(1122, 'Oxytropis', 'Aw´‡Uªvwcm j¨v¤^viUvB', NULL),
(1123, 'Oxytropis lamberti(Loco weed)', '**', NULL),
(1124, 'Paeonia offcinalis', 'wcIwbqvg', NULL),
(1125, 'Paghalamalli', NULL, NULL),
(1126, 'Pakur', '**', NULL),
(1127, 'Palladium', 'c¨v‡jwWqvg', NULL),
(1128, 'Pambotano', '**', NULL),
(1129, 'Panacea arv', '**', NULL),
(1130, 'Panax', '**', NULL),
(1131, 'Pancrcatinum', '**', NULL),
(1132, 'Papaver somnif', '**', NULL),
(1133, 'Papaya(Asimina)', NULL, NULL),
(1134, 'Paraffinum', '**', NULL),
(1135, 'Pareira brava', '†c‡iiv †eªfv', NULL),
(1136, 'Parictaria', '**', NULL),
(1137, 'Paris quadrifolia', 'c¨vwim †KvqvwW‡dwjqv', NULL),
(1138, 'Parthenium', NULL, NULL),
(1139, 'Passiflora', '**', NULL),
(1140, 'Pastinaca', '**', NULL),
(1141, 'Paullinia(pinnata)', 'c¨vwjwbqv wc‡b›Uv', NULL),
(1142, 'Pecten', '**', NULL),
(1143, 'Pediculus capitis', 'wcwWwKDjm', NULL),
(1144, 'Pelargonium', '**', NULL),
(1145, 'Pelius', '**', NULL),
(1146, 'Pelletierine', '**', NULL),
(1147, 'Penthorum', '†c‡š’vig', NULL),
(1148, 'Peoseolus', '**', NULL),
(1149, 'Pepsinum', 'cvwm©Kv', NULL),
(1150, 'Periploca graeca', '**', NULL),
(1151, 'Persicaria UR', '**', NULL),
(1152, 'Pertussin', '**', NULL),
(1153, 'Pestinum', NULL, NULL),
(1154, 'Petiveria', 'wcwU‡fwiqv', NULL),
(1155, 'Petroleum', '‡c‡Uªvwcqvg', NULL),
(1156, 'Petroselinum', 'wc‡Uªv‡mwjbg', NULL),
(1157, 'Peumus boldus', '**', NULL),
(1158, 'Phallus impudicus', '**', NULL),
(1159, 'Phaseolus nanus', '**', NULL),
(1160, 'Phellandrium', '**', NULL),
(1161, 'Phenatnum', '**', NULL),
(1162, 'Phenazone', NULL, NULL),
(1163, 'Phenol', '**', NULL),
(1164, 'Phleum', '**', NULL),
(1165, 'Phloridzin', '**', NULL),
(1166, 'Phorizinum', '**', NULL),
(1167, 'Phosphor pentachl.', '**', NULL),
(1168, 'Phosphoricum acidum', 'dùwiKvg GwmWvg', NULL),
(1169, 'Phosphorus', 'dùivm', NULL),
(1170, 'Phosphorus hydrogen', '**', NULL),
(1171, 'Phosphorus muriaticum', '**', NULL),
(1172, 'Phosphorus rubrum', '**', NULL),
(1173, 'Physalia', '**', NULL),
(1174, 'Physostigma', 'dvB‡mvm&wUMg', NULL),
(1175, 'Phytolacca decandra', 'dvB‡Uvj°v', NULL),
(1176, 'Pichi', '**', NULL),
(1177, 'Picricum acidum', 'wcwµKvg GwmWg', NULL),
(1178, 'Picrotoxinum', '**', NULL),
(1179, 'Pilocarpinm  nitricum', '**', NULL),
(1180, 'Pilocarpinum', NULL, NULL),
(1181, 'Pilocarpinum'' muriaticum', '**', NULL),
(1182, 'Pimpernul saxifraga', '**', NULL),
(1183, 'Pinamta', '**', NULL),
(1184, 'Pinus Canadensis', '**', NULL),
(1185, 'Pinus Lambertina', '**', NULL),
(1186, 'Pinus silvestris', 'cvBbvm †mwjfvivBwUªm', NULL),
(1187, 'PinusSylvestis', NULL, NULL),
(1188, 'Piper augustifolia', '**', NULL),
(1189, 'Piper methysticum', 'cvBcvi †gwš’m&wUKg', NULL),
(1190, 'Piper nigrum', 'cvBcvi bvBMÖv', NULL),
(1191, 'Piperazinum', '**', NULL),
(1192, 'Piscidia', '**', NULL),
(1193, 'Pituitrn', NULL, NULL),
(1194, 'Pix Liguida', '**', NULL),
(1195, 'Planifolia', '**', NULL),
(1196, 'Plantago major', 'c­¨v‡›U‡Mv', NULL),
(1197, 'Platanus', '**', NULL),
(1198, 'Platina et.mur. nat. pt.', '**', NULL),
(1199, 'Platinum', '**', NULL),
(1200, 'Platinum metallicum', 'c­¨v‡›Ubvg', NULL),
(1201, 'Platinum muriaticum', 'c­¨vwUbg wgDwiGwUKg', NULL),
(1202, 'Plectranthus', '†c­K&Uª¨v¯’vm', NULL),
(1203, 'Plumbago littoralis', 'c­‡š^‡Mv wj‡Uv‡iwjm', NULL),
(1204, 'Plumbum aceticum', '**', NULL),
(1205, 'Plumbum carbonicum', '**', NULL),
(1206, 'Plumbum chromicum', '**', NULL),
(1207, 'Plumbum iodatum', '**', NULL),
(1208, 'Plumbum metallicum', 'c­¤^vg', NULL),
(1209, 'Plumbum phosphoricum', '**', NULL),
(1210, 'Plumeria cell', '**', NULL),
(1211, 'Pneumo cocin', '**', NULL),
(1212, 'Pneumo toxin', '**', NULL),
(1213, 'Pneumus boldo', '**', NULL),
(1214, 'Podophyllum peltatum', 'c‡Wvwdjvg', NULL),
(1215, 'Pollatin', '**', NULL),
(1216, 'Polygonum', '**', NULL),
(1217, 'Polygonum aviculare', 'cwj‡Mvbvg nvB‡Wªvwc‡ci GW', NULL),
(1218, 'Polygonum persicaria', '**', NULL),
(1219, 'Polygonum punctatum', '**', NULL),
(1220, 'Polygonum sagit', '**', NULL),
(1221, 'Polymnia', '**', NULL),
(1222, 'Polyporus off', '**', NULL),
(1223, 'Polyporus pinicola', '**', NULL),
(1224, 'Polytrichum junip', '**', NULL),
(1225, 'Populus candicans', 'ccyjm', NULL),
(1226, 'Populus tremulloides', '**', NULL),
(1227, 'Potass xontate', '**', NULL),
(1228, 'Pothos foetidus', 'c_m& wdwUWg', NULL),
(1229, 'Prenanthes serp', '**', NULL),
(1230, 'Primula farinosa', '**', NULL),
(1231, 'Primula obconica', '**', NULL),
(1232, 'Primula veris', '**', NULL),
(1233, 'Protargol', '**', NULL),
(1234, 'Prunclla', '**', NULL),
(1235, 'Prunus padus', '**', NULL),
(1236, 'Prunus spinosa', 'cÖ€bg ¯žvB‡bvmv', NULL),
(1237, 'Prunus virgineana', '**', NULL),
(1238, 'Psoralea', '**', NULL),
(1239, 'Psorinum', '†mvwibvg', NULL),
(1240, 'Ptelea trifoliata', 'wUwjqv wUª‡dvwjqvUv', NULL),
(1241, 'Ptuitrin', '**', NULL),
(1242, 'Pulex iritans', 'cy‡j´ BwiUvÝ', NULL),
(1243, 'Pulmo vulpis', '**', NULL),
(1244, 'Pulsatilla nigricans', 'cj‡mwUjv', NULL),
(1245, 'Pulsatilla nuttaliana', 'cj&‡mwUjv b‡Uwjqvbv', NULL),
(1246, 'Pynus', 'cvBivm Av‡gwiKvbv', NULL),
(1247, 'Pyrethrum parthenium', '**', NULL),
(1248, 'Pyrogenium(Sepsinum)', 'cvB‡iv‡Rb', NULL),
(1249, 'Pyrus americana', '**', NULL),
(1250, 'Quassi', '**', NULL),
(1251, 'Quebracho', '**', NULL),
(1252, 'Quercus', '**', NULL),
(1253, 'Querwus gland spiritus', '**', NULL),
(1254, 'Quillaya', '**', NULL),
(1255, 'Quinidin', '**', NULL),
(1256, 'Rademacher''s liquor', '**', NULL),
(1257, 'Radium', '†iwWqvg', NULL),
(1258, 'Ranunculus acris', 'i¨vbb&wKDjvm Gwµm', NULL),
(1259, 'Ranunculus bulbosus', 'i¨vbbwKDjvmK ej‡evmm', NULL),
(1260, 'Ranunculus flammula', '**', NULL),
(1261, 'Ranunculus glacialic', '**', NULL),
(1262, 'Ranunculus repens', '**', NULL),
(1263, 'Ranunculus sceleratus', 'i¨vb&bwKDjv wmwj‡iUm', NULL),
(1264, 'Raphanus', '‡i‡cbvm', NULL),
(1265, 'Ratanhia', 'i¨vUvwbqv', NULL),
(1266, 'Resorcinum', '**', NULL),
(1267, 'Rhamnus calif', '**', NULL),
(1268, 'Rhamnus eath', '**', NULL),
(1269, 'Rhamnus pursh', '**', NULL),
(1270, 'Rheum', 'wiDg', NULL),
(1271, 'Rhodallin', '**', NULL),
(1272, 'Rhodium nitri', NULL, NULL),
(1273, 'Rhododendron', 'n«‡Wv‡WÛªb', NULL),
(1274, 'Rhus aromatica', 'ivm& G‡iv‡gwUKv', NULL),
(1275, 'Rhus diversiloba', '**', NULL),
(1276, 'Rhus glabra', 'ivm M­veªv', NULL),
(1277, 'Rhus radicans', 'ivm i¨vwWK¨vb&m', NULL),
(1278, 'Rhus toxicodendron', 'ivm Uw·‡Kv‡WÛªb', NULL),
(1279, 'Rhus venenata', 'ivm †fwbbvUv', NULL),
(1280, 'Ricinus communis', '**', NULL),
(1281, 'Ricinus(Oleum ricini)', '**', NULL),
(1282, 'Robinia pseudacacia', '†ivwewbqv', NULL),
(1283, 'Rohitok', '**', NULL),
(1284, 'Rosa canina', '**', NULL),
(1285, 'Rosa damascena', '**', NULL),
(1286, 'Rosmarinus', '**', NULL),
(1287, 'Rubia tinctorum', '**', NULL),
(1288, 'Rubus vill', '**', NULL),
(1289, 'Rudbeckia', '**', NULL),
(1290, 'Rumex acete', NULL, NULL),
(1291, 'Rumex crispus', '**', NULL),
(1292, 'Rumex obtusifolia', 'i€‡g· wµmcm', NULL),
(1293, 'Russula', '**', NULL),
(1294, 'Ruta graveolens', 'i€Uv', NULL),
(1295, 'Sabadilla', 'm¨vevwWjv', NULL),
(1296, 'Sabal serrulata', '†mevj †mjy‡jUvm', NULL),
(1297, 'Sabina', 'm¨vwebv', NULL),
(1298, 'Saccharin', '**', NULL),
(1299, 'Saccharomyess', '**', NULL),
(1300, 'Saccharum 0fficinale', NULL, NULL),
(1301, 'Saccharum album', 'm¨vµvg Gj¦vg', NULL),
(1302, 'Saccharum latis', 'm¨vµvg j¨vwUm', NULL),
(1303, 'Sal morinum', '**', NULL),
(1304, 'Salaginella', '**', NULL),
(1305, 'Salamander', 'm¨v‡j‡gÛvi', NULL),
(1306, 'Salicinum', '**', NULL),
(1307, 'Salicylicum acidum', 'm¨vwjwmwjKg GwmWg', NULL),
(1308, 'Salix mollissima', '**', NULL),
(1309, 'Salix mollissima2222', NULL, NULL),
(1310, 'Salix niger', 'm¨vwj· bvBRvi', NULL),
(1311, 'Salix purpurea', '**', NULL),
(1312, 'Salol', '**', NULL),
(1313, 'Salufer', '**', NULL),
(1314, 'Salvia officinalis', '**', NULL),
(1315, 'Salvia scterata', '**', NULL),
(1316, 'Sambucus Canadensis', '**', NULL),
(1317, 'Sambucus nigra', 'm¨v¤^yKvm bvBMÖv', NULL),
(1318, 'Sanguinaria canadensis', '**', NULL),
(1319, 'Sanguinaria nitrica', '**', NULL),
(1320, 'Sanguinarinum taritaricum', '**', NULL),
(1321, 'Sanguisorba off', '**', NULL),
(1322, 'Sanguisuga', 'm¨v½yB‡bwiqv', NULL),
(1323, 'Sanicula', 'm¨vwbwKDjv G‡Kvqv', NULL),
(1324, 'Sanicula aqua', 'm¨vwbwKDjv GKzB', NULL),
(1325, 'Santolum', NULL, NULL),
(1326, 'Santoninum', '**', NULL),
(1327, 'Saponaria', '**', NULL),
(1328, 'Saponia', 'm¨vivwmwbqv', NULL),
(1329, 'Saraca indica', '**', NULL),
(1330, 'Sarcolactic acid', '**', NULL),
(1331, 'Sarracenia purpurea', '**', NULL),
(1332, 'Sarsaparilla', 'mvm©vW¨vwijv', NULL),
(1333, 'Satalum', '**', NULL),
(1334, 'Saururus', '**', NULL),
(1335, 'Saw palmtto', '**', NULL),
(1336, 'Scammonium', '**', NULL),
(1337, 'Schinus', '**', NULL),
(1338, 'Scilla maritima', '**', NULL),
(1339, 'Scirrhinum', '**', NULL),
(1340, 'Scolopendra', '**', NULL),
(1341, 'Scoparium', '**', NULL),
(1342, 'Scopolam hydrobrom', '**', NULL),
(1343, 'Scorpio', '**', NULL),
(1344, 'Scrophularia', '**', NULL),
(1345, 'Scutellaria lateriflora', '¯‹z‡U‡jwiqv j¨v‡Uwi', NULL),
(1346, 'Secale cornutum', 'wm‡Kwj Kzwb©DUvg', NULL),
(1347, 'Sedum acre', '**', NULL),
(1348, 'Sedum alpestre', '**', NULL),
(1349, 'Sedum repens', '**', NULL),
(1350, 'Sedum telephium', '**', NULL),
(1351, 'Selaginella', '**', NULL),
(1352, 'Selenium', 'wmwjwbqvg', NULL),
(1353, 'Semper vinum tector', '**', NULL),
(1354, 'Senecio aureus', 'wmwbwbI', NULL),
(1355, 'Senecio jacobaca', '**', NULL),
(1356, 'Senega', '†m‡bMv', NULL),
(1357, 'Senna', '†mbv', NULL),
(1358, 'Sepia', 'wmwcqv', NULL),
(1359, 'Sepin', '**', NULL),
(1360, 'Septiaeminum', '**', NULL),
(1361, 'Serpentaria', '**', NULL),
(1362, 'Serratula', '**', NULL),
(1363, 'Serum anguillar', '**', NULL),
(1364, 'Shucks', '**', NULL),
(1365, 'Sil phion cyrenaicum', '**', NULL),
(1366, 'Sil sul calc alum', '**', NULL),
(1367, 'Silica marina', '**', NULL),
(1368, 'Silicea', 'mvBwjwmqv', NULL),
(1369, 'Silico fluor calc', '**', NULL),
(1370, 'Silphium', '**', NULL),
(1371, 'Simaba', '**', NULL),
(1372, 'Simaruba ferr', '**', NULL),
(1373, 'Sinapis alba', 'wmbvwcm& G¤^v', NULL),
(1374, 'Sinapis nigra', 'wmbvwcm bvGMÖv', NULL),
(1375, 'Sisyrinchium', '**', NULL),
(1376, 'Sium', '**', NULL),
(1377, 'Skatol', '**', NULL),
(1378, 'Skookum chuch', '**', NULL),
(1379, 'Slag', '**', NULL),
(1380, 'Soda cacodyl', '**', NULL),
(1381, 'Soda taurocholate', '**', NULL),
(1382, 'Sodii bicarbonas', '**', NULL),
(1383, 'Sodium chloroaurate', '**', NULL),
(1384, 'Sol', '**', NULL),
(1385, 'Sol anum  carolinense', '**', NULL),
(1386, 'Solaninum', '**', NULL),
(1387, 'Solaninum aceticum', '**', NULL),
(1388, 'Solanum arrebenta', '**', NULL),
(1389, 'Solanum lycopersicum', '**', NULL),
(1390, 'Solanum mammosum', '†mv‡jbg g¨v‡gvmv', NULL),
(1391, 'Solanum nigrum', '†mv‡jbg bvBMÖvg', NULL),
(1392, 'Solanum oleraceum', '†mv‡jbg Iwe‡iwm', NULL),
(1393, 'Solanum pseudocaps', '**', NULL),
(1394, 'Solanum tuber aegrotans', '**', NULL),
(1395, 'Solanum tuberosum', '†mv‡jbg wUDev‡iv', NULL),
(1396, 'Solanum vesicarium', '†mvwjWv‡Mv wf©M& Ai', NULL),
(1397, 'Solidago virg. aur', '†mvwjWv‡Mv wf©M& Ai', NULL),
(1398, 'Sopartein sulph.', '**', NULL),
(1399, 'Spartium scaparium', '**', NULL),
(1400, 'Sphingurus', '**', NULL),
(1401, 'Spigelia anthelmia', '¯žvB‡Rwjqv Gš’v', NULL),
(1402, 'Spigelia marilandica', '¯žvBwRwjqv g¨vwijvwÛKv', NULL),
(1403, 'Spiraca', '**', NULL),
(1404, 'Spiranthes', '¯žvBi¨vwš’m', NULL),
(1405, 'Spirit. g. n.', NULL, NULL),
(1406, 'Spirit. g. q.', NULL, NULL),
(1407, 'Spirit.a.c', NULL, NULL),
(1408, 'Spongia tosta', '¯žwÄqv †Uv÷v', NULL),
(1409, 'Squilla hispanica', '¯‹zBjv wnm‡cwbKv', NULL),
(1410, 'Stachys betonica', '**', NULL),
(1411, 'Stannum iodatum', '**', NULL),
(1412, 'Stannum metallicum', 'ó¨vbvg †gU', NULL),
(1413, 'Staphisagria', 'ó¨vwd‡mwMÖqv', NULL),
(1414, 'Staphyloccin', '**', NULL),
(1415, 'Stellaria media', '†ó‡jwiqv †gwWqv', NULL),
(1416, 'Sterculia', '**', NULL),
(1417, 'Sticta pulmonaria', 'wó±v cvj‡gv‡bwiqv', NULL),
(1418, 'Stigmata maidis', '**', NULL),
(1419, 'Stillingia sylvatica', 'wówjwÄqv wmj‡fwUKv', NULL),
(1420, 'Stovain', '**', NULL),
(1421, 'Stramonnium', 'óª¨v‡gvwbqvg', NULL),
(1422, 'Streptoccumin', '**', NULL),
(1423, 'Strontia carb', '**', NULL),
(1424, 'Strontia iodatum', '**', NULL),
(1425, 'Strontia nit.', '**', NULL),
(1426, 'Strontinum nitricum', NULL, NULL),
(1427, 'Strontium bromatum', NULL, NULL),
(1428, 'Strontium car', '**', NULL),
(1429, 'Strophanthus hispidus', '‡÷v‡dš’vm wnmwcWvm', NULL),
(1430, 'Strychnin ars', NULL, NULL),
(1431, 'Strychnin et ferr cit', '**', NULL),
(1432, 'Strychnin nit', '**', NULL),
(1433, 'Strychnin valeranicum', '**', NULL),
(1434, 'Strychninum', '†óªvwÝqg', NULL),
(1435, 'Strychninum phosphoricum.', '**', NULL),
(1436, 'Strychninum sulphu ricum', '**', NULL),
(1437, 'Strychnos gaulth.', '**', NULL),
(1438, 'Strychnos tiente', '**', NULL),
(1439, 'Succinic acid', '**', NULL),
(1440, 'Succinum', '**', NULL),
(1441, 'Sucrose', '**', NULL),
(1442, 'Sulfonal', '**', NULL),
(1443, 'Sulpher terebinthinatum', '**', NULL),
(1444, 'Sulphur', 'mvjdvi', NULL),
(1445, 'Sulphur hydrogenistum', '**', NULL),
(1446, 'Sulphur iodatum', 'mvjdvi Av‡qv‡WUg', NULL),
(1447, 'Sulphuricum acidum', 'mvjwdDwiKvg GwmW', NULL),
(1448, 'Sumbul', 'm¤^vj', NULL),
(1449, 'Supra rena entract', '**', NULL),
(1450, 'Swartica chirata', '**', NULL),
(1451, 'Symphoricarpus racemosus', 'wmçv‡ivcvicvm †iwm‡gvmv', NULL),
(1452, 'Symphytum officinale', 'wmçvBUvg Awdwm‡bwj', NULL),
(1453, 'Syphilinum(Luesinum)', 'wmwdwjbvg', NULL),
(1454, 'Syzygium', '**', NULL),
(1455, 'T,n.t', '**', NULL),
(1456, 'Tabacum', 'U¨v‡eKvg', NULL),
(1457, 'Tamus', '**', NULL),
(1458, 'Tanacetum vulgare', 'U¨vbvwmUg', NULL),
(1459, 'Tanghinia', '**', NULL),
(1460, 'Tannic acid', NULL, NULL),
(1461, 'Tannin', '†Uwbbvg', NULL),
(1462, 'Taraxacum', 'U¨viv‡´Kg', NULL),
(1463, 'Tarentula cubensis', 'U¨v‡iw›UDjv wKD‡ebwmm', NULL),
(1464, 'Tarentula hispanica', 'U¨v‡iw›UDjv', NULL),
(1465, 'Tartaicum acid', 'Uv©UvwiKvg GwmW', NULL),
(1466, 'Tartar emetiens', '**', NULL),
(1467, 'Tatrdyrite', '**', NULL),
(1468, 'Taxus baccata', 'U¨v´m e¨v‡KUv', NULL),
(1469, 'Teicriummarum', 'wUDwµqvg g¨vig wfig', NULL),
(1470, 'Tela aranea', '**', NULL),
(1471, 'Tellurium', '†Ujywiqvg', NULL),
(1472, 'Teplitz', '†UcwjR', NULL),
(1473, 'Terebene', '**', NULL),
(1474, 'Terminalia', '**', NULL),
(1475, 'Terpin hydrate', '**', NULL),
(1476, 'Teridion', '**', NULL),
(1477, 'Teucrium marum verum', '**', NULL),
(1478, 'Teucrium seorodania', '**', NULL),
(1479, 'Thallium', '†_wjqvg', NULL),
(1480, 'Thaspium', '**', NULL),
(1481, 'Thea sinensis', 'w_qv', NULL),
(1482, 'Thebainum', NULL, NULL),
(1483, 'Theridion', NULL, NULL),
(1484, 'Thevetia', NULL, NULL),
(1485, 'Thiosinaminum', '**', NULL),
(1486, 'Thlaspi (bursa pastoris)', '†_jvmwc evimv †cvówiqv', NULL),
(1487, 'Thuja', '_yRv', NULL),
(1488, 'Thuja occidentalis', NULL, NULL),
(1489, 'Thymol', '**', NULL),
(1490, 'Thymus', '**', NULL),
(1491, 'Thymus gland', '**', NULL),
(1492, 'Thyrodinum', '†_wiwWIb', NULL),
(1493, 'Thyroiodinum', '**', NULL),
(1494, 'Tilia europoea', '**', NULL),
(1495, 'Tinetura acris', '**', NULL),
(1496, 'Tinospara', '**', NULL),
(1497, 'Titanium', '**', NULL),
(1498, 'Tongo', '†Uv‡½v', NULL),
(1499, 'Torula', '**', NULL),
(1500, 'Tosta pracparata', '**', NULL),
(1501, 'Toxicophis', '**', NULL),
(1502, 'Trachinus', '**', NULL),
(1503, 'Tradescentia', '**', NULL),
(1504, 'Treebinthina', '†Uwiwewš’bv', NULL),
(1505, 'Trhebainum', '**', NULL),
(1506, 'Triatema', '**', NULL),
(1507, 'Tribulus', '**', NULL),
(1508, 'Trifolium pratense', '**', NULL),
(1509, 'Trifolum repens', 'wUª‡dvwjbvg cÖ¨v‡UwÝ', NULL),
(1510, 'Trillium pendulum', 'wUªwjqg †cÛzjvg', NULL),
(1511, 'Trime', '**', NULL),
(1512, 'Trimethylamin(Propylamin)', '**', NULL),
(1513, 'Trinitrotoluene', '**', NULL),
(1514, 'Trinitrotophenol', '**', NULL),
(1515, 'Trional', NULL, NULL),
(1516, 'Triosteum', '**', NULL),
(1517, 'Triosteum perfoliatum', '**', NULL),
(1518, 'Triticum repens', '**', NULL),
(1519, 'Trombidium', 'Uªw¤^wWqvg wgDwm W‡gwó', NULL),
(1520, 'Tropaeolum', '**', NULL),
(1521, 'Trotyl(t.n.t)', '**', NULL),
(1522, 'Trychnos gaultheriana', '**', NULL),
(1523, 'Tuberculinum', 'wUDeviKzwjbvg', NULL),
(1524, 'Turnera(Damiana)', '**', NULL),
(1525, 'Turpenthum minerale', '**', NULL),
(1526, 'Tussilago fragrans', 'wUDwm‡j‡Mv d«¨vMÖv', NULL),
(1527, 'Tussilago furfara', '**', NULL),
(1528, 'Tussilago petasites', '**', NULL),
(1529, 'Tussilago retasiles', 'wUDwm‡j‡Mv wc‡UmvBUm', NULL),
(1530, 'Typha lafif', '**', NULL),
(1531, 'Ueuba(brazilian)', '**', NULL),
(1532, 'Ulmus', '**', NULL),
(1533, 'Ulmus fulva', '**', NULL),
(1534, 'Upas', 'Dcvm', NULL),
(1535, 'Upas anliaris', '**', NULL),
(1536, 'Upas tiente', '**', NULL),
(1537, 'Uranium nitricum', 'BD‡iwbqvg bvBwUªKvg', NULL),
(1538, 'Urea', '**', NULL),
(1539, 'Uricum acidum', '**', NULL),
(1540, 'Urinum', '**', NULL),
(1541, 'Urotropin', '**', NULL),
(1542, 'Urtica', '**', NULL),
(1543, 'Urtica urens', '**', NULL),
(1544, 'Usnea', '**', NULL),
(1545, 'Usnea barbata', '**', NULL),
(1546, 'Ustilago maydis', 'Avwó‡j‡Mv', NULL),
(1547, 'Uva ursi', 'BDfv AvimvB', NULL),
(1548, 'Vaccininum', 'f¨vw·wbbvg', NULL),
(1549, 'Vaccinum myrtillus', '**', NULL),
(1550, 'Valeriana', '†fwjwiqvbv', NULL),
(1551, 'Vanadium', '**', NULL),
(1552, 'Vanilla', '**', NULL),
(1553, 'Variolinum', '†fwiIwjbvg', NULL),
(1554, 'Veratrine', '**', NULL),
(1555, 'Veratrinum', '**', NULL),
(1556, 'Veratrum album', 'wf‡iUªvg Gj¦vg', NULL),
(1557, 'Veratrum nigrum', '**', NULL),
(1558, 'Veratrum viride', 'wf‡iUªvg wfwiwW', NULL),
(1559, 'Verbascum thapsus', 'fveŸ©v¯‹vg', NULL),
(1560, 'Verbena', '**', NULL),
(1561, 'Verbena hastata', '**', NULL),
(1562, 'Veronal', '**', NULL),
(1563, 'Vesicaris', '**', NULL),
(1564, 'Vespa crabro', '‡fmcv †µv‡eªv', NULL),
(1565, 'Viburnum opulus', '**', NULL),
(1566, 'Viburnum prunifolium', '**', NULL),
(1567, 'Viburnum tinus', '**', NULL),
(1568, 'Vichy', '**', NULL),
(1569, 'Vinca minor', 'wf¼v', NULL),
(1570, 'Vincctoninum', '**', NULL),
(1571, 'Viola odarata', 'fv‡qvjv IWv‡iUv', NULL),
(1572, 'Viola Tricolor', '**', NULL),
(1573, 'Vipera', 'fvB‡civ', NULL),
(1574, 'Vipera redi', '**', NULL),
(1575, 'Vipera torva', '**', NULL),
(1576, 'Viscum album', 'wf¯‹vg Gj¦vg', NULL),
(1577, 'Viter trif', '**', NULL),
(1578, 'Vitrum', '**', NULL),
(1579, 'Voeslau', '**', NULL),
(1580, 'Wiesbaden', 'BDm‡e‡Wb', NULL),
(1581, 'Wildbad', 'BDj‡eW', NULL),
(1582, 'Woorari', '**', NULL),
(1583, 'Wyethia helenioides', 'IqvBw_qv', NULL),
(1584, 'Xanhium', '**', NULL),
(1585, 'Xanthorrhiza', 'R¨vb_w·jvg', NULL),
(1586, 'Xanthorrhoca', '**', NULL),
(1587, 'Xanthoxylum fraxineum', '**', NULL),
(1588, 'Xerophyllum', '**', NULL),
(1589, 'Xiphosura', '**', NULL),
(1590, 'X-ray', '**', NULL),
(1591, 'Yatren', '**', NULL),
(1592, 'Yerba buena', '**', NULL),
(1593, 'Yerba mansa', '**', NULL),
(1594, 'Yerba santa', '**', NULL),
(1595, 'Yohimbinun', '**', NULL),
(1596, 'Yucca Flamentosa', '**', NULL),
(1597, 'Zea italica', '**', NULL),
(1598, 'Zea mays(Mais)', '**', NULL),
(1599, 'Zincum aceticum', 'wR¼vg GwmwUKvg', NULL),
(1600, 'Zincum bromatum(ZnBr2)', '**', NULL),
(1601, 'Zincum carbonicun', '**', NULL),
(1602, 'Zincum cyanatum', 'wR¼vg mvB‡qv‡bUvg', NULL),
(1603, 'Zincum metallicum', 'wR¼vg †gU', NULL),
(1604, 'Zincum muriaticum', 'wR¼vg wgDwiGwUKvg', NULL),
(1605, 'Zincum oxydatum', 'wR¼vg Aw·‡WUvg', NULL),
(1606, 'Zincum phos phoricum', '**', NULL),
(1607, 'Zincum sulphuricum', 'wR¼vg mvjwdDwiKvg', NULL),
(1608, 'Zincun arsenicum', '**', NULL),
(1609, 'Zincun picricum', '**', NULL),
(1610, 'Zincun valerianum', '**', NULL),
(1611, 'Zingiber', 'wRwÄevi', NULL),
(1612, 'Zia', 'wRwRqv Gwiqv', NULL);

