-- HomeoAssist — Medicines Seed Data (1,612 records from acid.mdb medi table)
-- Run AFTER schema.sql:
--   psql -U postgres -d homeoassist -f backend/medicines_seed.sql

ALTER SEQUENCE medicines_m_id_seq RESTART WITH 1;

INSERT INTO medicines (m_id, m_txt, m_btxt, m_du) OVERRIDING SYSTEM VALUE VALUES
(1,'Abies canadansis','Gwem K¨vbv‡Wbwmm',true),
(2,'Abies nigra','Gwem bvBMÖv',true),
(3,'Abroma',NULL,false),
(4,'Abroma radix',NULL,false),
(5,'Abrotanum','G‡eªv‡Ubvg',true),
(6,'Absinthium','Ge&wmb&w_qg',true),
(7,'Acalypha indica','G‡Kwjdv BwÛKv',true),
(8,'Acanthia',NULL,false),
(9,'Acarus',NULL,false),
(10,'Aceranlidum(Anti fibrium)',NULL,false),
(11,'Acetic acid','GwmwUK GwmW',true),
(12,'Achyranthes',NULL,false),
(13,'Aconitinum',NULL,false),
(14,'Aconitum anthora',NULL,false),
(15,'Aconitum cammarum','G‡KvbvBUvg K¨vg¨vivg',true),
(16,'Aconitum ferox','G‡KvbvBUvg †di´',true),
(17,'Aconitum lycoctonum','G‡KvbvBU jvB‡Kv‡Uvbvg',true),
(18,'Aconitum napellus','G‡KvbvBU †bwcjvm',true),
(19,'Aconitum septentrionale*',NULL,true),
(20,'Actaea racemosa',NULL,false),
(21,'Actaea spicata','GK&wUqv w¯ž‡KUv',true),
(22,'Adetheidsquellus*',NULL,false),
(23,'Adonidin*',NULL,false),
(24,'Adonis vernalis',NULL,false),
(25,'Adrenalin',NULL,false),
(26,'Aegle folia*',NULL,false),
(27,'Aegle marmals*',NULL,false),
(28,'AEsculus glabra','B¯‹zDjvm M­¨veªv',true),
(29,'Aesculus hippocastanum','Bw¯‹Djvm wn‡cvKv‡óbvg',true),
(30,'Aethiops antimonialis',NULL,false),
(31,'Aethiops merc',NULL,false),
(32,'AEthusa cynapium','B_yRv',true),
(33,'Agaricin',NULL,false),
(34,'Agaricus campanulutus',NULL,false),
(35,'Agaricus campestris',NULL,false),
(36,'Agaricus citrinus',NULL,false),
(37,'Agaricus emeticus','GMvwiKvm GwgwUKvm',true),
(38,'Agaricus muscarius','MGvwiKvm gv‡¯‹wiqvm',false),
(39,'Agaricus pantherinus',NULL,true),
(40,'Agaricus phalloides','MGvwiKvm d¨vjGW&m&',false),
(41,'Agaricus procerus',NULL,false),
(42,'Agaricus semiglobatus',NULL,false),
(43,'Agave americana',NULL,false),
(44,'Agnus castus','MGœvm K¨vmUvm',true),
(45,'Agraphis nutans',NULL,false),
(46,'Agrimonia',NULL,false),
(47,'Agropyrum',NULL,false),
(48,'Agrostemma githago',NULL,false),
(49,'Agrostis',NULL,false),
(50,'Ailanthus glandulosa','GBj¨vš''¨vm',true);

INSERT INTO medicines (m_id, m_txt, m_btxt, m_du) OVERRIDING SYSTEM VALUE VALUES
(51,'Alcohol','Gj‡Kvnj',true),
(52,'Alcohol sulphuris',NULL,false),
(53,'Aletris farinosa','G‡jwUªm †dwi‡bvmv',true),
(54,'Alfalfa',NULL,false),
(55,'Alkekengi',NULL,false),
(56,'Allium cepa','Gwjqvg wmcv',true),
(57,'Allium sativum','Gwjqg m¨vwUfg',true),
(58,'Alnus',NULL,false),
(59,'Aloe socotrina','G‡jvR',true),
(60,'Alstonia constricta','G‡j‡óvwbqv Kb&wóªKUv',true),
(61,'Alstonia scholaris',NULL,false),
(62,'Althaca',NULL,false),
(63,'Alumen','&Gjy‡gb',true),
(64,'Alumin acet',NULL,false),
(65,'Alumin chor.',NULL,false),
(66,'Alumin oxide',NULL,false),
(67,'Alumin sil sulph',NULL,false),
(68,'Alumina','Gjywgbv',true),
(69,'Alumina silicata',NULL,false),
(70,'Aluminium metallicum','Gjywgwbqg †gU',true),
(71,'Aluminium silicata','Gjywgbv mvBwj',true),
(72,'Amanita agaricus',NULL,false),
(73,'Amanita phallo',NULL,false),
(74,'Amanita vernus',NULL,false),
(75,'Ambra grisea','Avgeªv wMÖwmqv',true),
(76,'Ambrosia artemisiae foli','Avg‡eªvwmqv AvwUwgwmqv ‡d',false),
(77,'Ammmonium hydrate',NULL,false),
(78,'Ammoniacum benzoicum','G‡gvwbqvg †e‡ÄvKvg',true),
(79,'Ammoniacum bromatum','G‡gvwbqg †eªv‡gUg',true),
(80,'Ammoniacum carbonicum','G‡gvwbqg KveŸ©wbKvg',true),
(81,'Ammoniacum causticum','G‡gvwbqvg KvwóKvg',true),
(82,'Ammoniacum gummi','GgwbGKvg Mvw¤§',false),
(83,'Ammoniacum muriaticum','G‡gvwbqg wgDwi‡qwUKvg',true),
(84,'Ammonium aceticum',NULL,false),
(85,'Ammonium formald',NULL,false),
(86,'Ammonium hydr',NULL,false),
(87,'Ammonium iodum',NULL,false),
(88,'Ammonium nitricum',NULL,false),
(89,'Ammonium phosphoricum',NULL,false),
(90,'Ammonium picricum',NULL,false),
(91,'Ammonium tartaricum',NULL,false),
(92,'Amon veler',NULL,false),
(93,'Amon vened',NULL,false),
(94,'Ampelopsis',NULL,false),
(95,'Ampelopsis trifol',NULL,false),
(96,'Amphisboena','Ggwdmwe‡qbv',true),
(97,'Amygdalae am. aqua','GwgM&‡Wwj G‡gwi',true),
(98,'Amygdalae persica',NULL,false),
(99,'Amyl nitrite','Gwgj bvBUªvBU',true),
(100,'Amyla mine chlorohydrate',NULL,false);

INSERT INTO medicines (m_id, m_txt, m_btxt, m_du) OVERRIDING SYSTEM VALUE VALUES
(101,'Anacardium occidentale','GbvKvwWqg Aw·',true),
(102,'Anacardium orientale','GbvKvwWqvg Iwi‡qb',true),
(103,'Anagallis arvensis','Gbv‡Mwjm Avi‡ebwmm',true),
(104,'Anagyris',NULL,false),
(105,'Anantherum mur',NULL,false),
(106,'Ancistrodon contorix',NULL,false),
(107,'Andersonia',NULL,false),
(108,'Andrina araroba',NULL,false),
(109,'Andrina lactra',NULL,false),
(110,'Andromeda',NULL,false),
(111,'Anemopsis',NULL,false),
(112,'Angelica atropurpurea',NULL,false),
(113,'Angophora',NULL,false),
(114,'Angophora(Kino)','wK‡bv',false),
(115,'Anguillar ichthy serum',NULL,false),
(116,'Angustura spuria',NULL,false),
(117,'Angustura vera',NULL,true),
(118,'Anhalonium',NULL,false),
(119,'Anhalonium lewinii','G½óziv †fiv',false),
(120,'Anilinum','Gwbwjbvg',true),
(121,'Anisum stellatum(Illecebrum  anisatum)','Gwbmvm wó&‡jUvg',false),
(122,'Anthernis nobilis','Gwš'wgm †bvwewjm',false),
(123,'Anthoxanthum','Gb_ªvwmbvg',false),
(124,'Anthracinum',NULL,false),
(125,'Anthrokokali','Gb&_ªv‡Kvwjbvg',false),
(126,'Antiarus tox','Gw›U‡gvwbqg UvU©',false),
(127,'Antimonium arsenic','Gw›U‡gvwbqg Avm©',false),
(128,'Antimonium chloridum','Gw›U‡gvwbqvg †K¬vwiWvg',false),
(129,'Antimonium crudum','Gw›U‡gvwbqg µzWg',true),
(130,'Antimonium et potass tar',NULL,true),
(131,'Antimonium iodum',NULL,false),
(132,'Antimonium metalcum',NULL,false),
(133,'Antimonium muriaticum',NULL,true),
(134,'Antimonium oxidum','Gw›U‡gvwbqvg Aw·‡WUvg',false),
(135,'Antimonium sulph aur',NULL,false),
(136,'Antimonium sulphuratum aureum','Gw›U‡gvwbqg mvj&d,A‡iUg',false),
(137,'Antipyrinum',NULL,false),
(138,'Aphis chenopodii glauci','Gwdm wP‡bv‡cvWvB M­mvB',false),
(139,'Apis Mel','Gwcm †gj',false),
(140,'Apium graveolens',NULL,false),
(141,'Apium virus',NULL,false),
(142,'Apocynum andros','G‡cvmvBbvg G‡Ûvm Gwg‡dvwj',false),
(143,'Apocynum cannabinum','G‡cvmvBbvg K¨vbvwebg',false),
(144,'Apomorphinum','G‡cvmvBbvg G‡Ûvm Gwg‡dvwj',false),
(145,'Apomorphium muriaticum',NULL,false),
(146,'Aqua  regia',NULL,false),
(147,'Aqua calcarea',NULL,false),
(148,'Aqua marina',NULL,false),
(149,'Aqua petra',NULL,false),
(150,'Aqua sanicula',NULL,false);
