-- HomeoAssist seed: symptom_rubrics
-- Source: acid.mdb

INSERT INTO symptom_rubrics (sbr_id, sbr_btxt, sbr_txt) VALUES
(1, 'gb', 'Mind'),
(2, 'wk‡ivN~Y©b', 'Vertigo'),
(3, 'g¯—K', 'Head'),
(4, 'P¶z', 'Eye'),
(5, '`„wókw³', 'Vision'),
(6, 'KY©', 'Ear'),
(7, 'kªeYkw³', 'Hearing'),
(8, 'bvwmKv', 'Nose'),
(9, 'gyLgÊj', 'Face'),
(10, 'gyLMnŸi', 'Mouth'),
(11, '`š—', 'Teeth'),
(12, 'Mjbvjx', 'Throat'),
(13, 'evn¨Mj‡`k', 'External Throat'),
(14, 'cvK¯’jx', 'Stomach'),
(15, 'D`i', 'Abdomen'),
(16, 'mijvš¿', 'Rectum'),
(17, 'gj', 'Stool'),
(18, 'gyÎ_jx', 'Bladder'),
(19, 'gyÎMÖwš’', 'Kidneys'),
(20, 'cÖ‡óUMÖš—', 'Prostate'),
(21, 'gyÎgvM©', 'Urethra'),
(22, 'gyÎ', 'Uring'),
(23, 'Rb‡bw›`ªq', 'Genitalia Male'),
(24, '¯¿x-Rb‡bw›`ªq', 'Genitalia Female'),
(25, 'k¦vmbvjxIK', 'Larynx & Trachea'),
(26, 'k¦vmwµqv', 'Respiration'),
(27, 'Kvwk', 'Cough'),
(28, 'M‡qi DVv', 'Expectoration'),
(29, 'e¶‡`k', 'Chest'),
(30, 'c„ó', 'Back'),
(31, 'n¯’c`vw`', 'Extremities'),
(32, 'wb`ªv', 'Sleep'),
(33, 'kxZve¯’v', 'Chill'),
(34, 'R¡i', 'Fever'),
(35, 'N¤§©', 'Perspiration'),
(36, 'P¤§©', 'Sking'),
(37, 'mvaviYj¶Y', 'Generalities'),
(38, 'bZzb ms‡hvM', 'New Adision');

